% panel_C_rank_win_loss_fractions.m
% Jonathan Reinwald
%
% Standalone repository script for Figure 5C.
%
% Figure 5C plots social rank against:
%   - fraction of tube-test wins
%   - fraction of tube-test losses
%
% Only the hierarchy window relevant at the time of fMRI scanning is used:
%   NoSeMaze 1:
%       days 3-16  OR  days 8-21, depending on DaysToConsider
%   NoSeMaze 2:
%       days 1-14
%
% The calculation follows the original script:
%
%   nWins   = sum(match_matrix,2)
%   nLosses = sum(match_matrix,1)'
%
%   frWins   = nWins   / sum(nWins)
%   frLosses = nLosses / sum(nLosses)
%
% Rank is derived from David's score, with rank 1 = highest DS.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_5/
% │   └── panel_C_rank_win_loss_fractions.m
% │
% ├── data/processed/NoSeMaze/
% │   ├── 01_General_Overview.xlsx
% │   └── tubetest/
% │       ├── NoSeMaze_1/
% │       │   ├── DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       │   └── DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       └── NoSeMaze_2/
% │           └── DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │
% ├── src/matlab/
% │   └── docDataSrc.m      (optional)
% │
% └── results/main/Figure_5/Figure_5C/
%
% No fMRI/graph-analysis files are required for this panel.
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the script location. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/main/Figure_5/panel_C_rank_win_loss_fractions.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

noSeMazeDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze' ...
);

noSeMaze1Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_1' ...
);

noSeMaze2Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_2' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_5', ...
    'Figure_5C' ...
);

if isfolder(srcDir)
    addpath(genpath(srcDir));
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Input files

generalOverviewFile = fullfile( ...
    noSeMazeDir, ...
    '01_General_Overview.xlsx' ...
);

am1EarlyFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am1LateFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am2File = fullfile( ...
    noSeMaze2Dir, ...
    'DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

requiredFiles = {
    generalOverviewFile
    am1EarlyFile
    am1LateFile
    am2File
};

missingFiles = requiredFiles(~cellfun(@isfile, requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required files are missing:\n\n%s', ...
        strjoin(missingFiles, newline) ...
    );
end

%% Load overview and hierarchy data

T = readtable( ...
    generalOverviewFile, ...
    'Sheet', ...
    9, ...
    'ReadVariableNames', ...
    true, ...
    'VariableNamingRule', ...
    'modify' ...
);

tmp = load(am1EarlyFile, 'DS_info');
AM1_early = prepareHierarchy(tmp.DS_info);

tmp = load(am1LateFile, 'DS_info');
AM1_late = prepareHierarchy(tmp.DS_info);

tmp = load(am2File, 'DS_info');
AM2 = prepareHierarchy(tmp.DS_info);

%% Assemble Figure 5C data
%
% The General Overview determines which pre-scan hierarchy window belongs
% to each animal. Only Autonomouse/NoSeMaze 1 and 2 animals are retained.

animalID = strings(0,1);
animalNumber = [];
noSeMaze = [];
scanWindow = strings(0,1);

rankValue = [];
fractionWins = [];
fractionLosses = [];

for rowIndex = 1:height(T)

    autoValue = T.Autonomouse(rowIndex);

    if ~ismember(autoValue, [1, 2])
        continue;
    end

    currentID = normalizeAnimalID(T.AnimalIDCombined(rowIndex));

    if autoValue == 1

        daysValue = normalizeText(T.DaysToConsider(rowIndex));

        if contains(daysValue, '16')

            hierarchy = AM1_early;
            currentWindow = "AM1_day3to16";

        elseif contains(daysValue, '21')

            hierarchy = AM1_late;
            currentWindow = "AM1_day8to21";

        else

            error( ...
                'Could not assign a hierarchy window for AM1 animal %s.', ...
                currentID ...
            );
        end

    else

        hierarchy = AM2;
        currentWindow = "AM2_day1to14";
    end

    hierarchyIDs = string(hierarchy.ID(:));
    hierarchyIDs = upper(strtrim(hierarchyIDs));

    matchIndex = find(hierarchyIDs == currentID);

    if isempty(matchIndex)
        error( ...
            'Animal ID %s was not found in its hierarchy file.', ...
            currentID ...
        );
    end

    if numel(matchIndex) ~= 1
        error( ...
            'Animal ID %s occurs more than once in its hierarchy file.', ...
            currentID ...
        );
    end

    animalID(end+1,1) = currentID; %#ok<SAGROW>
    animalNumber(end+1,1) = getNumericScalar(T.AnimalNumber(rowIndex)); %#ok<SAGROW>
    noSeMaze(end+1,1) = autoValue; %#ok<SAGROW>
    scanWindow(end+1,1) = currentWindow; %#ok<SAGROW>

    rankValue(end+1,1) = hierarchy.Rank(matchIndex); %#ok<SAGROW>
    fractionWins(end+1,1) = hierarchy.frWins(matchIndex); %#ok<SAGROW>
    fractionLosses(end+1,1) = hierarchy.frLosses(matchIndex); %#ok<SAGROW>
end

%% Sort by animal number for deterministic source-data order

[animalNumber, sortIndex] = sort(animalNumber, 'ascend');

animalID = animalID(sortIndex);
noSeMaze = noSeMaze(sortIndex);
scanWindow = scanWindow(sortIndex);

rankValue = rankValue(sortIndex);
fractionWins = fractionWins(sortIndex);
fractionLosses = fractionLosses(sortIndex);

fprintf('\nFigure 5C input check\n');
fprintf('Animals: %d\n', numel(rankValue));
fprintf('Rank range: %.0f to %.0f\n', min(rankValue), max(rankValue));
fprintf('Variables: fraction wins, fraction losses\n\n');

%% Correlations
%
% The original Figure 1/5 plotting section used MATLAB corr() without a
% Type argument, i.e. Pearson correlations. This is retained here.

[rWins, pWins] = corr( ...
    rankValue, ...
    fractionWins, ...
    'Rows', ...
    'complete' ...
);

[rLosses, pLosses] = corr( ...
    rankValue, ...
    fractionLosses, ...
    'Rows', ...
    'complete' ...
);

%% Plot Figure 5C

fig = figure( ...
    'Name', ...
    'Figure 5C: Rank vs win/loss fractions', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 650, 600] ...
);

ax = axes(fig);
hold(ax, 'on');

scWins = scatter( ...
    ax, ...
    rankValue, ...
    fractionWins, ...
    40, ...
    'filled' ...
);

scLosses = scatter( ...
    ax, ...
    rankValue, ...
    fractionLosses, ...
    40, ...
    'filled' ...
);

scWins.MarkerEdgeColor = 'none';
scLosses.MarkerEdgeColor = 'none';

% Original colors
colorWins = [0, 0.6, 0];
colorLosses = [0.85, 0, 0];

scWins.MarkerFaceColor = colorWins;
scLosses.MarkerFaceColor = colorLosses;

%% Regression lines

lineHandles = lsline;

% lsline returns handles in reverse graphics order
if numel(lineHandles) >= 2

    lineHandles(1).Color = colorLosses;
    lineHandles(1).LineWidth = 1.5;

    lineHandles(2).Color = colorWins;
    lineHandles(2).LineWidth = 1.5;
end

%% Axis formatting

box(ax, 'off');
axis(ax, 'square');

ax.XLim = [1, 12];
ax.XTick = 1:12;

xlabel(ax, 'Rank');
ylabel(ax, 'Fraction of contests');

ax.FontSize = 11;
ax.FontWeight = 'bold';
ax.LineWidth = 1;

legend( ...
    ax, ...
    [scWins, scLosses], ...
    {'Fraction wins', 'Fraction losses'}, ...
    'Location', ...
    'best', ...
    'Box', ...
    'off' ...
);

%% Correlation annotations

xLeft = ax.XLim(1) + 0.08 * diff(ax.XLim);
xRight = ax.XLim(1) + 0.58 * diff(ax.XLim);

yWins = ax.YLim(1) + 0.10 * diff(ax.YLim);
yLosses = ax.YLim(1) + 0.18 * diff(ax.YLim);

text( ...
    ax, ...
    xLeft, ...
    yWins, ...
    sprintf('p = %.3g', pWins), ...
    'Color', ...
    colorWins, ...
    'FontWeight', ...
    'bold' ...
);

text( ...
    ax, ...
    xRight, ...
    yWins, ...
    sprintf('r = %.3f', rWins), ...
    'Color', ...
    colorWins, ...
    'FontWeight', ...
    'bold' ...
);

text( ...
    ax, ...
    xLeft, ...
    yLosses, ...
    sprintf('p = %.3g', pLosses), ...
    'Color', ...
    colorLosses, ...
    'FontWeight', ...
    'bold' ...
);

text( ...
    ax, ...
    xRight, ...
    yLosses, ...
    sprintf('r = %.3f', rLosses), ...
    'Color', ...
    colorLosses, ...
    'FontWeight', ...
    'bold' ...
);

title( ...
    ax, ...
    'Figure 5C', ...
    'Interpreter', ...
    'none' ...
);

%% Save source data

sourceData = table( ...
    animalID, ...
    animalNumber, ...
    noSeMaze, ...
    scanWindow, ...
    rankValue, ...
    fractionWins, ...
    fractionLosses, ...
    'VariableNames', {
        'AnimalID'
        'AnimalNumber'
        'NoSeMaze'
        'HierarchyWindow'
        'Rank'
        'FractionWins'
        'FractionLosses'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_5C_Rank_WinLossFractions.csv' ...
    ) ...
);

%% Save statistics

statisticsTable = table( ...
    ["Rank_vs_FractionWins"; "Rank_vs_FractionLosses"], ...
    [rWins; rLosses], ...
    [pWins; pLosses], ...
    'VariableNames', {
        'Comparison'
        'Pearson_R'
        'P'
    } ...
);

writetable( ...
    statisticsTable, ...
    fullfile( ...
        outputDir, ...
        'Statistics_Figure_5C_Rank_WinLossFractions.csv' ...
    ) ...
);

%% Save complete MATLAB result

result = struct;

result.AnimalID = animalID;
result.AnimalNumber = animalNumber;
result.NoSeMaze = noSeMaze;
result.HierarchyWindow = scanWindow;

result.Rank = rankValue;
result.FractionWins = fractionWins;
result.FractionLosses = fractionLosses;

result.WinsCorrelation.r = rWins;
result.WinsCorrelation.p = pWins;

result.LossesCorrelation.r = rLosses;
result.LossesCorrelation.p = pLosses;

save( ...
    fullfile( ...
        outputDir, ...
        'Results_Figure_5C_Rank_WinLossFractions.mat' ...
    ), ...
    'result' ...
);

%% Optional script provenance

if ~isempty(which('docDataSrc'))

    try
        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );
    catch documentationError
        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export figure

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_5C_Rank_WinLossFractions.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_5C_Rank_WinLossFractions.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

fprintf('Figure 5C completed.\n');
fprintf('Results saved to:\n%s\n', outputDir);

%% ========================================================================
% Local functions
%% ========================================================================

function hierarchy = prepareHierarchy(DS_info)
% Derive Rank and fractions of wins/losses from the tube-test match matrix.

    hierarchy = DS_info;

    [~, sortedIndex] = sort( ...
        [hierarchy.DS], ...
        'descend' ...
    );

    [~, rank] = sort(sortedIndex);

    hierarchy.Rank = rank;

    nWins = sum( ...
        hierarchy.match_matrix, ...
        2 ...
    );

    nLosses = sum( ...
        hierarchy.match_matrix, ...
        1 ...
    )';

    totalWins = sum(nWins);
    totalLosses = sum(nLosses);

    if totalWins == 0 || totalLosses == 0
        error('Hierarchy match_matrix contains zero total wins/losses.');
    end

    hierarchy.frWins = nWins ./ totalWins;
    hierarchy.frLosses = nLosses ./ totalLosses;
end


function value = normalizeAnimalID(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Animal ID cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    value = upper(strtrim(string(rawValue)));

    if numel(value) ~= 1 || ismissing(value) || strlength(value) == 0
        error('Could not convert an Animal ID to a valid string.');
    end
end


function value = normalizeText(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Text cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    value = strtrim(string(rawValue));
end


function value = getNumericScalar(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Numeric cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    if isnumeric(rawValue)
        value = double(rawValue);
    else
        value = str2double(string(rawValue));
    end

    if numel(value) ~= 1 || ~isfinite(value)
        error('Could not convert AnimalNumber to one finite numeric value.');
    end
end
