% panel_A_B_D_globalGA_social_hierarchy.m
% Jonathan Reinwald
%
% Reviewer-facing reproduction script for Figure 5A, 5B and 5D.
%
% Main displayed analyses:
%   Figure 5A: social rank vs Delta C
%   Figure 5B: social rank vs Delta L
%   Figure 5D: fraction of losses vs TEST-PRE changes in Delta C and Delta L
%
% FDR correction:
%   The manuscript reports raw Pearson-correlation p-values and applies
%   Benjamini-Hochberg FDR correction across the three predefined global
%   graph metrics:
%
%       g_delta_C
%       g_delta_L
%       g_swp
%
%   SWP is therefore included in the statistical correction families even
%   though it is not displayed as a main Figure 5 panel.
%
% For social rank, separate three-metric FDR families are defined for:
%   1. PRE correlations
%   2. TEST correlations
%   3. TEST-PRE change correlations
%
% For fraction of losses, Figure 5D uses one three-metric FDR family for
% TEST-PRE change correlations.
%
% Raw correlation p-values are shown in the figures. A dagger indicates
% that the corresponding result survives FDR correction across Delta C,
% Delta L and SWP.
%
% PRE  = TPnoPuff trials 11-40
% TEST = TPnoPuff trials 81-120
%
% Graph threshold range:
%   45-50%
%
% Only the conditioning cohort is used.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_5/
% │   └── panel_A_B_D_globalGA_social_hierarchy.m
% │
% ├── data/processed/NoSeMaze/
% │   ├── 01_General_Overview.xlsx
% │   ├── AnimalNumb_to_ID.mat
% │   └── tubetest/
% │       ├── NoSeMaze_1/
% │       │   ├── DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       │   └── DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       └── NoSeMaze_2/
% │           └── DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │
% ├── data/processed/fMRI/Figure_4/Figure_4C_E/conditioning/
% │   ├── auc_struc_TPnoPuff11to40_45to50_p.mat
% │   └── auc_struc_TPnoPuff81to120_45to50_p.mat
% │
% ├── src/matlab/
% │   └── helpers/
% │       └── docDataSrc.m          (optional; may also be elsewhere below src/matlab)
% │
% └── results/main/Figure_5/
%     ├── Figure_5A/
%     ├── Figure_5B/
%     └── Figure_5D/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/main/Figure_5/panel_A_B_D_globalGA_social_hierarchy.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

noSeMazeDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze' ...
);

noSeMaze1Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_1' ...
);

noSeMaze2Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_2' ...
);

aucDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_4', ...
    'Figure_4C_E', ...
    'conditioning' ...
);

resultsBaseDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_5' ...
);

%% Add repository MATLAB code

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for corr and lsline.' ...
    ]);
end

%% Fixed analysis settings

thresholdDisplayMin = 45;
thresholdDisplayMax = 50;

preName = 'TPnoPuff11to40';
testName = 'TPnoPuff81to120';

fdrAlpha = 0.05;

metricInfo = struct([]);

metricInfo(1).shortName = 'deltaC';
metricInfo(1).displayName = '\DeltaC';
metricInfo(1).fieldName = 'g_delta_C';
metricInfo(1).mainPanel = 'Figure_5A';
metricInfo(1).displayInMainFigure = true;

metricInfo(2).shortName = 'deltaL';
metricInfo(2).displayName = '\DeltaL';
metricInfo(2).fieldName = 'g_delta_L';
metricInfo(2).mainPanel = 'Figure_5B';
metricInfo(2).displayInMainFigure = true;

metricInfo(3).shortName = 'SWP';
metricInfo(3).displayName = 'SWP';
metricInfo(3).fieldName = 'g_swp';
metricInfo(3).mainPanel = '';
metricInfo(3).displayInMainFigure = false;

numberOfMetrics = numel(metricInfo);

%% Input files: hierarchy / animal information

generalOverviewFile = fullfile( ...
    noSeMazeDir, ...
    '01_General_Overview.xlsx' ...
);

am1EarlyFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am1LateFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am2File = fullfile( ...
    noSeMaze2Dir, ...
    'DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

animalMapFile = fullfile( ...
    noSeMazeDir, ...
    'AnimalNumb_to_ID.mat' ...
);

%% Input files: global graph AUC

aucPreFile = fullfile( ...
    aucDir, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        preName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

aucTestFile = fullfile( ...
    aucDir, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        testName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

requiredFiles = {
    generalOverviewFile
    am1EarlyFile
    am1LateFile
    am2File
    animalMapFile
    aucPreFile
    aucTestFile
};

missingFiles = requiredFiles(~cellfun(@isfile, requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required input files are missing:\n\n%s', ...
        strjoin(missingFiles, newline) ...
    );
end

if ~isfolder(resultsBaseDir)
    mkdir(resultsBaseDir);
end

%% Reconstruct hierarchy measures

% Original workflow uses sheet 9.
T = readtable( ...
    generalOverviewFile, ...
    'Sheet', ...
    9, ...
    'ReadVariableNames', ...
    true, ...
    'VariableNamingRule', ...
    'modify' ...
);

tmp = load(am1EarlyFile, 'DS_info');
DS_AM1_early = prepareHierarchy(tmp.DS_info);

tmp = load(am1LateFile, 'DS_info');
DS_AM1_late = prepareHierarchy(tmp.DS_info);

tmp = load(am2File, 'DS_info');
DS_AM2 = prepareHierarchy(tmp.DS_info);

%% Build animal-wise behavioral information

info = struct;
counter = 0;

for rowIndex = 1:height(T)

    autonomouse = getNumericScalar(T.Autonomouse(rowIndex));

    if ~ismember(autonomouse, [1, 2])
        continue;
    end

    currentID = normalizeAnimalID(T.AnimalIDCombined(rowIndex));

    if autonomouse == 1

        daysValue = normalizeText(T.DaysToConsider(rowIndex));

        if contains(daysValue, '16')

            hierarchy = DS_AM1_early;
            scanWindow = "AM1_day3to16";

        elseif contains(daysValue, '21')

            hierarchy = DS_AM1_late;
            scanWindow = "AM1_day8to21";

        else

            error( ...
                'Could not assign AM1 hierarchy window for animal %s.', ...
                currentID ...
            );
        end

    else

        hierarchy = DS_AM2;
        scanWindow = "AM2_day1to14";
    end

    hierarchyIDs = strings(numel(hierarchy.ID), 1);

    for hierarchyIndex = 1:numel(hierarchy.ID)
        hierarchyIDs(hierarchyIndex) = normalizeAnimalID( ...
            hierarchy.ID(hierarchyIndex) ...
        );
    end

    animalIndex = find(hierarchyIDs == currentID);

    if isempty(animalIndex)
        error( ...
            'Animal ID %s was not found in the assigned hierarchy file.', ...
            currentID ...
        );
    end

    if numel(animalIndex) ~= 1
        error( ...
            'Animal ID %s occurs more than once in the hierarchy file.', ...
            currentID ...
        );
    end

    counter = counter + 1;

    info.ID(counter, 1) = currentID;
    info.NoSeMaze(counter, 1) = autonomouse;
    info.HierarchyWindow(counter, 1) = scanWindow;
    info.Rank(counter, 1) = hierarchy.Rank(animalIndex);
    info.FractionLosses(counter, 1) = hierarchy.fr_loser(animalIndex);
end

if counter == 0
    error('No NoSeMaze 1/2 animals were found in the General Overview.');
end

%% Map behavioral IDs to MRI animal numbers

mapLoaded = load(animalMapFile);

if ~isfield(mapLoaded, 'AnimalNumb_to_ID')
    error( ...
        'Variable "AnimalNumb_to_ID" missing from:\n%s', ...
        animalMapFile ...
    );
end

AnimalNumb_to_ID = mapLoaded.AnimalNumb_to_ID;

mapIDs = strings(numel(AnimalNumb_to_ID), 1);

for mapIndex = 1:numel(AnimalNumb_to_ID)
    mapIDs(mapIndex) = normalizeAnimalID( ...
        AnimalNumb_to_ID(mapIndex).ID ...
    );
end

animalNumbers = nan(counter, 1);

for animalIndex = 1:counter

    targetID = info.ID(animalIndex);
    mapMatch = find(mapIDs == targetID);

    if isempty(mapMatch)
        error( ...
            'Animal ID %s was not found in AnimalNumb_to_ID.', ...
            targetID ...
        );
    end

    mappedNumbers = nan(numel(mapMatch), 1);

    for matchIndex = 1:numel(mapMatch)
        mappedNumbers(matchIndex) = getNumericScalar( ...
            AnimalNumb_to_ID(mapMatch(matchIndex)).AnimalNumb ...
        );
    end

    uniqueMappedNumbers = unique(mappedNumbers);

    if numel(uniqueMappedNumbers) ~= 1
        error( ...
            'Animal ID %s maps to multiple AnimalNumb values: %s', ...
            targetID, ...
            mat2str(uniqueMappedNumbers') ...
        );
    end

    animalNumbers(animalIndex) = uniqueMappedNumbers;
end

[animalNumbersSorted, sortIndex] = sort(animalNumbers, 'ascend');

animalIDsSorted = info.ID(sortIndex);
noSeMazeSorted = info.NoSeMaze(sortIndex);
hierarchyWindowSorted = info.HierarchyWindow(sortIndex);

rankInput = info.Rank(sortIndex);
fractionLossesInput = info.FractionLosses(sortIndex);

%% Load graph metric AUC structures

preLoaded = load(aucPreFile);
testLoaded = load(aucTestFile);

if ~isfield(preLoaded, 'auc_struc')
    error('Variable "auc_struc" missing from PRE AUC file.');
end

if ~isfield(testLoaded, 'auc_struc')
    error('Variable "auc_struc" missing from TEST AUC file.');
end

aucPre = preLoaded.auc_struc;
aucTest = testLoaded.auc_struc;

%% Extract all three predefined graph metrics

metricPre = cell(numberOfMetrics, 1);
metricTest = cell(numberOfMetrics, 1);
metricDiff = cell(numberOfMetrics, 1);

numberOfGraphAnimals = [];

for metricIndex = 1:numberOfMetrics

    fieldName = metricInfo(metricIndex).fieldName;

    if ~isfield(aucPre, fieldName) || ~isfield(aucTest, fieldName)
        error( ...
            ['Required graph metric "%s" is missing from PRE or TEST AUC ' ...
             'file. All three metrics Delta C, Delta L and SWP are required ' ...
             'for the Figure 5 FDR correction.'], ...
            fieldName ...
        );
    end

    metricPre{metricIndex} = getMetricVector(aucPre, fieldName);
    metricTest{metricIndex} = getMetricVector(aucTest, fieldName);

    if numel(metricPre{metricIndex}) ~= numel(metricTest{metricIndex})
        error( ...
            '%s: PRE and TEST sample sizes differ.', ...
            fieldName ...
        );
    end

    metricDiff{metricIndex} = ...
        metricTest{metricIndex} - metricPre{metricIndex};

    if isempty(numberOfGraphAnimals)
        numberOfGraphAnimals = numel(metricPre{metricIndex});
    elseif numel(metricPre{metricIndex}) ~= numberOfGraphAnimals
        error('Global graph metric vectors have different sample sizes.');
    end
end

if numel(rankInput) ~= numberOfGraphAnimals
    error([ ...
        'Behavior/MRI sample-size mismatch: %d behavioral animals but ' ...
        '%d graph-analysis animals.' ...
    ], ...
        numel(rankInput), ...
        numberOfGraphAnimals ...
    );
end

fprintf('\nFigure 5 input check\n');
fprintf('Displayed graph threshold range: %d-%d%%\n', ...
    thresholdDisplayMin, thresholdDisplayMax);
fprintf('Animals: %d\n', numberOfGraphAnimals);
fprintf('FDR family: Delta C, Delta L, SWP\n\n');

%% Calculate Pearson correlations for all FDR families

rankPreR = nan(numberOfMetrics, 1);
rankPreP = nan(numberOfMetrics, 1);

rankTestR = nan(numberOfMetrics, 1);
rankTestP = nan(numberOfMetrics, 1);

rankDiffR = nan(numberOfMetrics, 1);
rankDiffP = nan(numberOfMetrics, 1);

lossDiffR = nan(numberOfMetrics, 1);
lossDiffP = nan(numberOfMetrics, 1);

for metricIndex = 1:numberOfMetrics

    [rankPreR(metricIndex), rankPreP(metricIndex)] = corr( ...
        rankInput, ...
        metricPre{metricIndex}, ...
        'Type', ...
        'Pearson', ...
        'Rows', ...
        'complete' ...
    );

    [rankTestR(metricIndex), rankTestP(metricIndex)] = corr( ...
        rankInput, ...
        metricTest{metricIndex}, ...
        'Type', ...
        'Pearson', ...
        'Rows', ...
        'complete' ...
    );

    [rankDiffR(metricIndex), rankDiffP(metricIndex)] = corr( ...
        rankInput, ...
        metricDiff{metricIndex}, ...
        'Type', ...
        'Pearson', ...
        'Rows', ...
        'complete' ...
    );

    [lossDiffR(metricIndex), lossDiffP(metricIndex)] = corr( ...
        fractionLossesInput, ...
        metricDiff{metricIndex}, ...
        'Type', ...
        'Pearson', ...
        'Rows', ...
        'complete' ...
    );
end

%% Benjamini-Hochberg FDR correction across Delta C, Delta L and SWP

[rankPreQ, rankPreFDR] = bhFdrAdjustedP(rankPreP, fdrAlpha);
[rankTestQ, rankTestFDR] = bhFdrAdjustedP(rankTestP, fdrAlpha);
[rankDiffQ, rankDiffFDR] = bhFdrAdjustedP(rankDiffP, fdrAlpha);

[lossDiffQ, lossDiffFDR] = bhFdrAdjustedP(lossDiffP, fdrAlpha);

%% Save combined FDR summary

summaryMetric = string({metricInfo.shortName})';
summaryField = string({metricInfo.fieldName})';

fdrSummary = table( ...
    summaryMetric, ...
    summaryField, ...
    rankPreR, ...
    rankPreP, ...
    rankPreQ, ...
    rankPreFDR, ...
    rankTestR, ...
    rankTestP, ...
    rankTestQ, ...
    rankTestFDR, ...
    rankDiffR, ...
    rankDiffP, ...
    rankDiffQ, ...
    rankDiffFDR, ...
    lossDiffR, ...
    lossDiffP, ...
    lossDiffQ, ...
    lossDiffFDR, ...
    'VariableNames', { ...
        'Metric'
        'AUC_Structure_Field'
        'Rank_PRE_R'
        'Rank_PRE_P_Raw'
        'Rank_PRE_FDR_Q'
        'Rank_PRE_FDR_Significant'
        'Rank_TEST_R'
        'Rank_TEST_P_Raw'
        'Rank_TEST_FDR_Q'
        'Rank_TEST_FDR_Significant'
        'Rank_Delta_R'
        'Rank_Delta_P_Raw'
        'Rank_Delta_FDR_Q'
        'Rank_Delta_FDR_Significant'
        'FractionLosses_Delta_R'
        'FractionLosses_Delta_P_Raw'
        'FractionLosses_Delta_FDR_Q'
        'FractionLosses_Delta_FDR_Significant'
    } ...
);

writetable( ...
    fdrSummary, ...
    fullfile( ...
        resultsBaseDir, ...
        'Figure_5_GlobalMetrics_FDR_Summary.csv' ...
    ) ...
);

%% Figure 5A and 5B: Rank vs Delta C / Delta L

for metricIndex = 1:2

    panelName = metricInfo(metricIndex).mainPanel;
    metricShortName = metricInfo(metricIndex).shortName;
    metricDisplayName = metricInfo(metricIndex).displayName;
    fieldName = metricInfo(metricIndex).fieldName;

    currentPre = metricPre{metricIndex};
    currentTest = metricTest{metricIndex};
    currentDiff = metricDiff{metricIndex};

    outputDir = fullfile(resultsBaseDir, panelName);

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end

    fig = figure( ...
        'Name', ...
        sprintf('%s: Rank vs %s', panelName, metricShortName), ...
        'Visible', ...
        'on', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 900, 420] ...
    );

    %% Left: Rank vs PRE and TEST

    ax1 = subplot(1, 2, 1);
    hold(ax1, 'on');

    colorPre = [204/255, 51/255, 204/255];
    colorTest = [0, 160/255, 227/255];

    scPre = scatter( ...
        ax1, ...
        rankInput, ...
        currentPre, ...
        40, ...
        'filled' ...
    );

    scTest = scatter( ...
        ax1, ...
        rankInput, ...
        currentTest, ...
        40, ...
        'filled' ...
    );

    scPre.MarkerEdgeColor = 'none';
    scTest.MarkerEdgeColor = 'none';

    scPre.MarkerFaceColor = colorPre;
    scTest.MarkerFaceColor = colorTest;

    lineHandles = lsline(ax1);

    if numel(lineHandles) >= 2
        % lsline returns lines in reverse graphics order.
        lineHandles(1).Color = colorTest;
        lineHandles(1).LineWidth = 1.5;

        lineHandles(2).Color = colorPre;
        lineHandles(2).LineWidth = 1.5;
    end

    formatRankAxis(ax1, metricDisplayName);
    title(ax1, 'PRE and TEST', 'Interpreter', 'none');

    legend( ...
        ax1, ...
        [scPre, scTest], ...
        {'Pre', 'Test'}, ...
        'Location', ...
        'best', ...
        'Box', ...
        'off' ...
    );

    addTwoCorrelationAnnotations( ...
        ax1, ...
        rankPreR(metricIndex), ...
        rankPreP(metricIndex), ...
        rankPreFDR(metricIndex), ...
        rankTestR(metricIndex), ...
        rankTestP(metricIndex), ...
        rankTestFDR(metricIndex), ...
        colorPre, ...
        colorTest ...
    );

    %% Right: Rank vs TEST-PRE change

    ax2 = subplot(1, 2, 2);
    hold(ax2, 'on');

    colorDiff = (colorPre + colorTest) ./ 2;

    scDiff = scatter( ...
        ax2, ...
        rankInput, ...
        currentDiff, ...
        40, ...
        'filled' ...
    );

    scDiff.MarkerEdgeColor = 'none';
    scDiff.MarkerFaceColor = colorDiff;

    diffLine = lsline(ax2);

    if ~isempty(diffLine)
        diffLine(1).Color = colorDiff;
        diffLine(1).LineWidth = 1.5;
    end

    formatRankAxis( ...
        ax2, ...
        sprintf('%s | TEST - PRE', metricDisplayName) ...
    );

    title(ax2, 'TEST - PRE', 'Interpreter', 'none');

    addSingleCorrelationAnnotation( ...
        ax2, ...
        rankDiffR(metricIndex), ...
        rankDiffP(metricIndex), ...
        rankDiffFDR(metricIndex), ...
        colorDiff ...
    );

    sgtitle( ...
        sprintf('%s | social rank vs %s', panelName, metricDisplayName), ...
        'Interpreter', ...
        'tex' ...
    );

    %% Source data

    sourceData = table( ...
        animalIDsSorted, ...
        animalNumbersSorted, ...
        noSeMazeSorted, ...
        hierarchyWindowSorted, ...
        rankInput, ...
        currentPre, ...
        currentTest, ...
        currentDiff, ...
        'VariableNames', { ...
            'AnimalID'
            'AnimalNumber'
            'NoSeMaze'
            'HierarchyWindow'
            'Rank'
            'Pre'
            'Test'
            'Delta_TestMinusPre'
        } ...
    );

    writetable( ...
        sourceData, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_%s_%s_Rank.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Statistics

    statisticsTable = table( ...
        ["Rank_vs_PRE"; "Rank_vs_TEST"; "Rank_vs_TESTminusPRE"], ...
        [ ...
            rankPreR(metricIndex)
            rankTestR(metricIndex)
            rankDiffR(metricIndex)
        ], ...
        [ ...
            rankPreP(metricIndex)
            rankTestP(metricIndex)
            rankDiffP(metricIndex)
        ], ...
        [ ...
            rankPreQ(metricIndex)
            rankTestQ(metricIndex)
            rankDiffQ(metricIndex)
        ], ...
        [ ...
            rankPreFDR(metricIndex)
            rankTestFDR(metricIndex)
            rankDiffFDR(metricIndex)
        ], ...
        'VariableNames', { ...
            'Comparison'
            'Pearson_R'
            'P_Raw'
            'FDR_Q'
            'FDR_Significant'
        } ...
    );

    writetable( ...
        statisticsTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Statistics_%s_%s_Rank.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Complete result

    result = struct;

    result.Panel = panelName;
    result.Metric = metricShortName;
    result.FieldName = fieldName;

    result.AnimalID = animalIDsSorted;
    result.AnimalNumber = animalNumbersSorted;
    result.NoSeMaze = noSeMazeSorted;
    result.HierarchyWindow = hierarchyWindowSorted;
    result.Rank = rankInput;

    result.Pre = currentPre;
    result.Test = currentTest;
    result.Delta = currentDiff;

    result.Correlation.Pre.r = rankPreR(metricIndex);
    result.Correlation.Pre.pRaw = rankPreP(metricIndex);
    result.Correlation.Pre.qFDR = rankPreQ(metricIndex);
    result.Correlation.Pre.fdrSignificant = rankPreFDR(metricIndex);

    result.Correlation.Test.r = rankTestR(metricIndex);
    result.Correlation.Test.pRaw = rankTestP(metricIndex);
    result.Correlation.Test.qFDR = rankTestQ(metricIndex);
    result.Correlation.Test.fdrSignificant = rankTestFDR(metricIndex);

    result.Correlation.Delta.r = rankDiffR(metricIndex);
    result.Correlation.Delta.pRaw = rankDiffP(metricIndex);
    result.Correlation.Delta.qFDR = rankDiffQ(metricIndex);
    result.Correlation.Delta.fdrSignificant = rankDiffFDR(metricIndex);

    result.FDRFamily = {'g_delta_C', 'g_delta_L', 'g_swp'};
    result.FDRAlpha = fdrAlpha;

    save( ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Results_%s_%s_Rank.mat', ...
                panelName, ...
                metricShortName ...
            ) ...
        ), ...
        'result' ...
    );

    %% Metadata

    metadata = table( ...
        string(panelName), ...
        string(metricShortName), ...
        string(fieldName), ...
        thresholdDisplayMin, ...
        thresholdDisplayMax, ...
        numberOfGraphAnimals, ...
        fdrAlpha, ...
        string(generalOverviewFile), ...
        string(animalMapFile), ...
        string(aucPreFile), ...
        string(aucTestFile), ...
        'VariableNames', { ...
            'Panel'
            'Metric'
            'AUC_Structure_Field'
            'ThresholdDisplayMin'
            'ThresholdDisplayMax'
            'N'
            'FDR_Alpha'
            'GeneralOverviewFile'
            'AnimalMapFile'
            'AUC_Pre_File'
            'AUC_Test_File'
        } ...
    );

    writetable( ...
        metadata, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'AnalysisMetadata_%s_%s_Rank.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Optional source-script documentation

    if ~isempty(which('docDataSrc'))
        try
            docDataSrc(fig, outputDir, scriptFile, true);
        catch documentationError
            warning('docDataSrc failed: %s', documentationError.message);
        end
    end

    %% Export

    outputBaseName = sprintf( ...
        '%s_%s_Rank', ...
        panelName, ...
        metricShortName ...
    );

    exportgraphics( ...
        fig, ...
        fullfile(outputDir, [outputBaseName '.pdf']), ...
        'ContentType', ...
        'vector', ...
        'BackgroundColor', ...
        'white' ...
    );

    exportgraphics( ...
        fig, ...
        fullfile(outputDir, [outputBaseName '.png']), ...
        'Resolution', ...
        300, ...
        'BackgroundColor', ...
        'white' ...
    );

    fprintf('Completed %s (%s).\n', panelName, metricShortName);
end

%% Figure 5D: fraction of losses vs Delta C and Delta L changes

outputDir = fullfile(resultsBaseDir, 'Figure_5D');

if ~isfolder(outputDir)
    mkdir(outputDir);
end

fig = figure( ...
    'Name', ...
    'Figure 5D: Fraction of losses vs network adaptation', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 900, 420] ...
);

colorLoss = [0.85, 0, 0];

for metricIndex = 1:2

    ax = subplot(1, 2, metricIndex);
    hold(ax, 'on');

    scatterHandle = scatter( ...
        ax, ...
        fractionLossesInput, ...
        metricDiff{metricIndex}, ...
        40, ...
        'filled' ...
    );

    scatterHandle.MarkerEdgeColor = 'none';
    scatterHandle.MarkerFaceColor = colorLoss;

    lineHandle = lsline(ax);

    if ~isempty(lineHandle)
        lineHandle(1).Color = colorLoss;
        lineHandle(1).LineWidth = 1.5;
    end

    box(ax, 'off');
    axis(ax, 'square');

    xlabel(ax, 'Fraction of losses');
    ylabel( ...
        ax, ...
        sprintf('%s | TEST - PRE', metricInfo(metricIndex).displayName), ...
        'Interpreter', ...
        'tex' ...
    );

    ax.FontSize = 11;
    ax.FontWeight = 'bold';
    ax.LineWidth = 1;

    title( ...
        ax, ...
        metricInfo(metricIndex).displayName, ...
        'Interpreter', ...
        'tex' ...
    );

    addSingleCorrelationAnnotation( ...
        ax, ...
        lossDiffR(metricIndex), ...
        lossDiffP(metricIndex), ...
        lossDiffFDR(metricIndex), ...
        colorLoss ...
    );
end

sgtitle( ...
    'Figure 5D | fraction of losses vs TEST-PRE network change', ...
    'Interpreter', ...
    'none' ...
);

%% Figure 5D source data

sourceData = table( ...
    animalIDsSorted, ...
    animalNumbersSorted, ...
    noSeMazeSorted, ...
    hierarchyWindowSorted, ...
    rankInput, ...
    fractionLossesInput, ...
    metricDiff{1}, ...
    metricDiff{2}, ...
    metricDiff{3}, ...
    'VariableNames', { ...
        'AnimalID'
        'AnimalNumber'
        'NoSeMaze'
        'HierarchyWindow'
        'Rank'
        'FractionLosses'
        'DeltaC_TestMinusPre'
        'DeltaL_TestMinusPre'
        'SWP_TestMinusPre'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_5D_FractionLosses_GlobalMetrics.csv' ...
    ) ...
);

%% Figure 5D statistics
%
% Include SWP in the output because it is part of the FDR family,
% although only Delta C and Delta L are displayed in the main figure.

displayedInMainFigure = [true; true; false];

statisticsTable = table( ...
    string({metricInfo.shortName})', ...
    string({metricInfo.fieldName})', ...
    displayedInMainFigure, ...
    lossDiffR, ...
    lossDiffP, ...
    lossDiffQ, ...
    lossDiffFDR, ...
    'VariableNames', { ...
        'Metric'
        'AUC_Structure_Field'
        'DisplayedInMainFigure'
        'Pearson_R'
        'P_Raw'
        'FDR_Q'
        'FDR_Significant'
    } ...
);

writetable( ...
    statisticsTable, ...
    fullfile( ...
        outputDir, ...
        'Statistics_Figure_5D_FractionLosses_GlobalMetrics.csv' ...
    ) ...
);

%% Figure 5D complete result

result = struct;

result.Panel = 'Figure_5D';

result.AnimalID = animalIDsSorted;
result.AnimalNumber = animalNumbersSorted;
result.NoSeMaze = noSeMazeSorted;
result.HierarchyWindow = hierarchyWindowSorted;

result.Rank = rankInput;
result.FractionLosses = fractionLossesInput;

result.MetricInfo = metricInfo;
result.MetricDiff = metricDiff;

result.PearsonR = lossDiffR;
result.PRaw = lossDiffP;
result.QFDR = lossDiffQ;
result.FDRSignificant = lossDiffFDR;

result.FDRFamily = {'g_delta_C', 'g_delta_L', 'g_swp'};
result.FDRAlpha = fdrAlpha;

save( ...
    fullfile( ...
        outputDir, ...
        'Results_Figure_5D_FractionLosses_GlobalMetrics.mat' ...
    ), ...
    'result' ...
);

%% Figure 5D metadata

metadata = table( ...
    string('Figure_5D'), ...
    thresholdDisplayMin, ...
    thresholdDisplayMax, ...
    numberOfGraphAnimals, ...
    fdrAlpha, ...
    string(generalOverviewFile), ...
    string(animalMapFile), ...
    string(aucPreFile), ...
    string(aucTestFile), ...
    'VariableNames', { ...
        'Panel'
        'ThresholdDisplayMin'
        'ThresholdDisplayMax'
        'N'
        'FDR_Alpha'
        'GeneralOverviewFile'
        'AnimalMapFile'
        'AUC_Pre_File'
        'AUC_Test_File'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'AnalysisMetadata_Figure_5D.csv' ...
    ) ...
);

%% Optional source-script documentation

if ~isempty(which('docDataSrc'))
    try
        docDataSrc(fig, outputDir, scriptFile, true);
    catch documentationError
        warning('docDataSrc failed: %s', documentationError.message);
    end
end

%% Export Figure 5D

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_5D_FractionLosses_DeltaC_DeltaL.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_5D_FractionLosses_DeltaC_DeltaL.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

%% Save complete combined results

completeResults = struct;

completeResults.MetricInfo = metricInfo;
completeResults.FDRAlpha = fdrAlpha;

completeResults.Rank.Pre.R = rankPreR;
completeResults.Rank.Pre.PRaw = rankPreP;
completeResults.Rank.Pre.QFDR = rankPreQ;
completeResults.Rank.Pre.FDRSignificant = rankPreFDR;

completeResults.Rank.Test.R = rankTestR;
completeResults.Rank.Test.PRaw = rankTestP;
completeResults.Rank.Test.QFDR = rankTestQ;
completeResults.Rank.Test.FDRSignificant = rankTestFDR;

completeResults.Rank.Delta.R = rankDiffR;
completeResults.Rank.Delta.PRaw = rankDiffP;
completeResults.Rank.Delta.QFDR = rankDiffQ;
completeResults.Rank.Delta.FDRSignificant = rankDiffFDR;

completeResults.FractionLosses.Delta.R = lossDiffR;
completeResults.FractionLosses.Delta.PRaw = lossDiffP;
completeResults.FractionLosses.Delta.QFDR = lossDiffQ;
completeResults.FractionLosses.Delta.FDRSignificant = lossDiffFDR;

save( ...
    fullfile( ...
        resultsBaseDir, ...
        'Figure_5A_B_D_complete_results.mat' ...
    ), ...
    'completeResults', ...
    'fdrSummary' ...
);

fprintf('\nCompleted Figure 5A, 5B and 5D analyses.\n');
fprintf('Results saved under:\n%s\n', resultsBaseDir);

%% ========================================================================
% Local functions
%% ========================================================================

function hierarchy = prepareHierarchy(DS_info)
% Add hierarchy measures needed for Figure 5:
%   - Rank, with rank 1 = highest David's score
%   - fr_loser, fraction of losses within the hierarchy window

    hierarchy = DS_info;

    [~, sortedIndex] = sort( ...
        [hierarchy.DS], ...
        'descend' ...
    );

    [~, rank] = sort(sortedIndex);

    hierarchy.Rank = rank;

    lossCounts = sum( ...
        hierarchy.match_matrix, ...
        1 ...
    )';

    totalLosses = sum(lossCounts);

    if totalLosses == 0
        error('Hierarchy match_matrix contains zero total losses.');
    end

    hierarchy.fr_loser = lossCounts ./ totalLosses;
end


function values = getMetricVector(aucStructure, fieldName)
% Extract one subject-level global AUC metric as a column vector.

    if ~isfield(aucStructure, fieldName)
        error( ...
            'Metric field "%s" does not exist in auc_struc.', ...
            fieldName ...
        );
    end

    values = [aucStructure.(fieldName)];
    values = values(:);

    if ~isnumeric(values)
        error( ...
            'Metric field "%s" is not numeric.', ...
            fieldName ...
        );
    end

    if any(~isfinite(values))
        warning( ...
            'Metric field "%s" contains NaN/Inf values.', ...
            fieldName ...
        );
    end
end


function [qValues, significant] = bhFdrAdjustedP(pValues, alpha)
% Benjamini-Hochberg FDR-adjusted p-values across one predefined family.

    pValues = pValues(:);

    qValues = nan(size(pValues));
    significant = false(size(pValues));

    finiteMask = isfinite(pValues);

    if ~any(finiteMask)
        return;
    end

    pFinite = pValues(finiteMask);

    [sortedP, sortIndex] = sort(pFinite);
    m = numel(sortedP);

    adjustedSorted = sortedP .* m ./ (1:m)';

    for index = m-1:-1:1
        adjustedSorted(index) = min( ...
            adjustedSorted(index), ...
            adjustedSorted(index + 1) ...
        );
    end

    adjustedSorted = min(adjustedSorted, 1);

    adjustedFinite = nan(m, 1);
    adjustedFinite(sortIndex) = adjustedSorted;

    qValues(finiteMask) = adjustedFinite;
    significant(finiteMask) = adjustedFinite <= alpha;
end


function formatRankAxis(ax, yLabelText)

    box(ax, 'off');
    axis(ax, 'square');

    ax.XLim = [1, 12];
    ax.XTick = 1:12;

    xlabel(ax, 'Social rank');

    ylabel( ...
        ax, ...
        yLabelText, ...
        'Interpreter', ...
        'tex' ...
    );

    ax.FontSize = 11;
    ax.FontWeight = 'bold';
    ax.LineWidth = 1;
end


function addTwoCorrelationAnnotations( ...
    ax, ...
    r1, ...
    p1, ...
    fdr1, ...
    r2, ...
    p2, ...
    fdr2, ...
    color1, ...
    color2 ...
)

    xLeft = ax.XLim(1) + 0.08 * diff(ax.XLim);
    xRight = ax.XLim(1) + 0.57 * diff(ax.XLim);

    y1 = ax.YLim(1) + 0.10 * diff(ax.YLim);
    y2 = ax.YLim(1) + 0.20 * diff(ax.YLim);

    text( ...
        ax, ...
        xLeft, ...
        y1, ...
        pLabel(p1, fdr1), ...
        'Color', ...
        color1, ...
        'FontWeight', ...
        'bold', ...
        'Interpreter', ...
        'tex' ...
    );

    text( ...
        ax, ...
        xRight, ...
        y1, ...
        sprintf('r = %.3f', r1), ...
        'Color', ...
        color1, ...
        'FontWeight', ...
        'bold' ...
    );

    text( ...
        ax, ...
        xLeft, ...
        y2, ...
        pLabel(p2, fdr2), ...
        'Color', ...
        color2, ...
        'FontWeight', ...
        'bold', ...
        'Interpreter', ...
        'tex' ...
    );

    text( ...
        ax, ...
        xRight, ...
        y2, ...
        sprintf('r = %.3f', r2), ...
        'Color', ...
        color2, ...
        'FontWeight', ...
        'bold' ...
    );
end


function addSingleCorrelationAnnotation( ...
    ax, ...
    rValue, ...
    pValue, ...
    fdrSignificant, ...
    textColor ...
)

    xLeft = ax.XLim(1) + 0.08 * diff(ax.XLim);
    xRight = ax.XLim(1) + 0.57 * diff(ax.XLim);
    yPosition = ax.YLim(1) + 0.10 * diff(ax.YLim);

    text( ...
        ax, ...
        xLeft, ...
        yPosition, ...
        pLabel(pValue, fdrSignificant), ...
        'Color', ...
        textColor, ...
        'FontWeight', ...
        'bold', ...
        'Interpreter', ...
        'tex' ...
    );

    text( ...
        ax, ...
        xRight, ...
        yPosition, ...
        sprintf('r = %.3f', rValue), ...
        'Color', ...
        textColor, ...
        'FontWeight', ...
        'bold' ...
    );
end


function label = pLabel(pValue, fdrSignificant)
% Show raw p-value; dagger denotes survival of three-metric FDR correction.

    if fdrSignificant
        label = sprintf('p = %.3g  \\dagger', pValue);
    else
        label = sprintf('p = %.3g', pValue);
    end
end


function value = normalizeAnimalID(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Animal ID cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    if iscategorical(rawValue)
        rawValue = string(rawValue);
    end

    value = upper(strtrim(string(rawValue)));

    if numel(value) ~= 1 || ismissing(value) || strlength(value) == 0
        error('Could not convert an Animal ID to a valid string.');
    end
end


function value = normalizeText(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Text cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    value = strtrim(string(rawValue));
end


function value = getNumericScalar(rawValue)

    while iscell(rawValue)

        if numel(rawValue) ~= 1
            error('Numeric cell contains more than one element.');
        end

        rawValue = rawValue{1};
    end

    if isstring(rawValue) || ischar(rawValue) || iscategorical(rawValue)
        value = str2double(string(rawValue));
    else
        value = double(rawValue);
    end

    if numel(value) ~= 1 || ~isfinite(value)
        error('Could not convert value to one finite numeric scalar.');
    end
end
