function cfg = fmri_control_config(repoRoot)
% FMRI_CONTROL_CONFIG Paths and preprocessing constants for the
% reappraisal control fMRI cohort.
%
% Historical cohort:
%   reappraisal_control_2023
%
% Raw MRI acquisitions are not distributed publicly. Users with access to
% them should set:
%
%   NOSEMAZE_CONTROL_FMRI_RAW_ROOT

arguments
    repoRoot (1,:) char
end

cfg = struct();

%% Non-public raw MRI

cfg.rawMriRoot = getenv('NOSEMAZE_CONTROL_FMRI_RAW_ROOT');

%% Repository inputs

cfg.scanList = fullfile( ...
    repoRoot, ...
    'data', ...
    'reference', ...
    'fMRI', ...
    'control', ...
    'ScanList_reappraisal_control_2023.csv' ...
);

% Reference template and mask shared with the reappraisal preprocessing.
cfg.template = fullfile( ...
    repoRoot, ...
    'data', ...
    'reference', ...
    'templates', ...
    'fMRI', ...
    'DLtemplate_brain_rs1x1x1.nii' ...
);

cfg.templateMask = fullfile( ...
    repoRoot, ...
    'data', ...
    'reference', ...
    'templates', ...
    'fMRI', ...
    'DLtemplate_brainmask_rs1x1x1_polish.nii' ...
);

cfg.tpm = {
    fullfile(repoRoot,'data','reference','templates','fMRI','TPM', ...
        'sGM_template_markus_inPax_msk.nii')
    fullfile(repoRoot,'data','reference','templates','fMRI','TPM', ...
        'sWM_template_markus_inPax_msk.nii')
    fullfile(repoRoot,'data','reference','templates','fMRI','TPM', ...
        'sCSF_template_markus_inPax_msk.nii')
    fullfile(repoRoot,'data','reference','templates','fMRI','TPM', ...
        'sBackground_template_markus_msk.nii')
};

%% Working directories

cfg.workRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'interim', ...
    'fMRI', ...
    'control' ...
);

cfg.convertedDir = fullfile(cfg.workRoot,'converted');
cfg.fileListDir = fullfile(cfg.workRoot,'filelists');
cfg.dartelDir = fullfile(cfg.workRoot,'DARTEL');
cfg.motionDir = fullfile(cfg.workRoot,'motiondiagnosis');

cfg.fileList = fullfile( ...
    cfg.fileListDir, ...
    'filelist_control.mat' ...
);

%% Final preprocessing products

cfg.processedRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'preprocessing', ...
    'control' ...
);

%% Acquisition / preprocessing constants

cfg.nDummies = 5;

% The historical script selects up to 1600 task volumes for several stages.
cfg.nVolumesTask = 1600;

% Coordinates/images were historically scaled x10 for SPM compatibility.
% Thus [6 6 6] in SPM space corresponds to 0.6 mm physical FWHM.
cfg.smoothingPrimarySPM = [6 6 6];

cfg.waveletThreshold = 10;
cfg.waveletSearch = 'conservative';

% Historical control-specific brain extraction limits.
cfg.brainSizeLimits = [350 650] * 1000;

end
