% panel_B.m
% Jonathan Reinwald
%
% Reproduces Figure 2B:
% Eyelid response during conditioning block 1 versus block 3.
%
% This script:
%   1. Loads the processed eyelid data
%   2. Calculates mean responses and SEM
%   3. Generates the Figure 2B plot
%   4. Exports the plotted source data
%
% Statistical testing is performed separately in:
% figures/main/Figure_2/panel_B_statistics.R
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_2/
% │   ├── panel_B.m
% │   └── panel_B_statistics.R
% ├── data/processed/eyelid/reappraisal/
% │   └── pupil_summary_all.mat
% ├── src/matlab/
% │   └── ...
% └── results/main/Figure_2/

clear;
close all;
clc;

%% Locate repository root automatically

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of panel_B.m. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% panel_B.m is located at:
% repository/figures/main/Figure_2/panel_B.m
%
% Move upwards:
% Figure_2 -> main -> figures -> repository
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Define repository directories

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputFile = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'eyelid', ...
    'reappraisal', ...
    'pupil_summary_all.mat' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_2' ...
);

%% Add all MATLAB helper functions and subfolders

if ~isfolder(srcDir)
    error([ ...
        'MATLAB source-code directory not found:\n%s\n\n' ...
        'Expected repository location:\n' ...
        'src/matlab/' ...
    ], srcDir);
end

% Recursively add every folder below src/matlab
addpath(genpath(srcDir));

%% Check required helper functions

requiredFunctions = {
    'shadedErrorBar'
    'SEM_calc'
    'docDataSrc'
};

functionAvailable = cellfun( ...
    @(functionName) exist(functionName, 'file') == 2, ...
    requiredFunctions ...
);

missingFunctions = requiredFunctions(~functionAvailable);

if ~isempty(missingFunctions)
    error([ ...
        'The following required MATLAB functions were not found:\n\n%s\n\n' ...
        'Place these functions, and any functions they call, somewhere ' ...
        'inside src/matlab/ or one of its subfolders.' ...
    ], strjoin(missingFunctions, newline));
end

%% Check and load input data

if ~isfile(inputFile)
    error([ ...
        'Required input file not found:\n%s\n\n' ...
        'Expected repository location:\n' ...
        'data/processed/eyelid/reappraisal/' ...
        'pupil_summary_all.mat' ...
    ], inputFile);
end

loadedData = load(inputFile);

if ~isfield(loadedData, 'summary_all')
    error([ ...
        'The input MAT file does not contain the expected variable ' ...
        '"summary_all":\n%s' ...
    ], inputFile);
end

summary_all_rp = loadedData.summary_all;

if isempty(summary_all_rp)
    error('The variable "summary_all" is empty.');
end

%% Create output directory

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Select conditioning sessions and trial ranges

% Original summary_all ordering:
% 1 = conditioning/reappraisal
% 2 = 1 hour post
% 3 = 24 hours post
%
% Therefore, every third entry beginning with 1 is a conditioning session.
reappraisal_all = summary_all_rp(1:3:end);

% Trials included in the plotted blocks
block1Trials = 11:40;
block3Trials = 81:120;

%% Validate input structure

requiredFields = {
    'LidBaseDiameterMatrix_Corrected'
};

for animalIndex = 1:numel(reappraisal_all)

    for fieldIndex = 1:numel(requiredFields)

        fieldName = requiredFields{fieldIndex};

        if ~isfield(reappraisal_all(animalIndex), fieldName)
            error( ...
                'Animal/session %d is missing field "%s".', ...
                animalIndex, ...
                fieldName ...
            );
        end
    end

    lidMatrix = ...
        reappraisal_all(animalIndex).LidBaseDiameterMatrix_Corrected;

    if size(lidMatrix, 1) < max(block3Trials)
        error([ ...
            'Animal/session %d contains only %d trials. ' ...
            'At least %d trials are required.' ...
        ], ...
            animalIndex, ...
            size(lidMatrix, 1), ...
            max(block3Trials) ...
        );
    end
end

%% Concatenate block 1 and block 3 data

dataBlock1 = [];
dataBlock3 = [];

animalIDBlock1 = [];
animalIDBlock3 = [];

trialIDBlock1 = [];
trialIDBlock3 = [];

for animalIndex = 1:numel(reappraisal_all)

    lidMatrix = ...
        reappraisal_all(animalIndex).LidBaseDiameterMatrix_Corrected;

    dataBlock1 = [
        dataBlock1
        lidMatrix(block1Trials, :)
    ];

    dataBlock3 = [
        dataBlock3
        lidMatrix(block3Trials, :)
    ];

    animalIDBlock1 = [
        animalIDBlock1
        repmat(animalIndex, numel(block1Trials), 1)
    ];

    animalIDBlock3 = [
        animalIDBlock3
        repmat(animalIndex, numel(block3Trials), 1)
    ];

    trialIDBlock1 = [
        trialIDBlock1
        block1Trials(:)
    ];

    trialIDBlock3 = [
        trialIDBlock3
        block3Trials(:)
    ];
end

if isempty(dataBlock1) || isempty(dataBlock3)
    error('No eyelid data were extracted for block 1 or block 3.');
end

if size(dataBlock1, 2) ~= size(dataBlock3, 2)
    error([ ...
        'Block 1 and block 3 contain different numbers of time bins: ' ...
        '%d versus %d.' ...
    ], ...
        size(dataBlock1, 2), ...
        size(dataBlock3, 2) ...
    );
end

%% Calculate means and SEM

block1Mean = mean( ...
    dataBlock1, ...
    1, ...
    'omitnan' ...
);

block3Mean = mean( ...
    dataBlock3, ...
    1, ...
    'omitnan' ...
);

block1SEM = SEM_calc(dataBlock1);
block3SEM = SEM_calc(dataBlock3);

xValues = 1:size(dataBlock1, 2);

%% Create figure

fig = figure( ...
    'Name', ...
    'Figure 2B: Eyelid response, block 1 versus block 3' ...
);

fig.Position = [100 100 440 400];

%% Plot block 1

sd1 = shadedErrorBar( ...
    xValues, ...
    block1Mean, ...
    block1SEM ...
);

sd1.mainLine.Color = [0.7 0.25 0];
sd1.mainLine.LineWidth = 1.5;

sd1.patch.FaceColor = [0.7 0.25 0];
sd1.patch.EdgeColor = 'none';

sd1.edge(1).Color = 'none';
sd1.edge(2).Color = 'none';

hold on;

%% Plot block 3

sd2 = shadedErrorBar( ...
    xValues, ...
    block3Mean, ...
    block3SEM ...
);

sd2.mainLine.Color = [0 0.5 0.7];
sd2.mainLine.LineWidth = 1.5;

sd2.patch.FaceColor = [0 0.5 0.7];
sd2.patch.EdgeColor = 'none';

sd2.edge(1).Color = 'none';
sd2.edge(2).Color = 'none';

%% Save source data for block 1

variableNames = arrayfun( ...
    @(timeBin) sprintf('timebin_%d', timeBin), ...
    1:size(dataBlock1, 2), ...
    'UniformOutput', ...
    false ...
);

rowNamesBlock1 = arrayfun( ...
    @(rowIndex) sprintf( ...
        'An%d_Tr%d', ...
        animalIDBlock1(rowIndex), ...
        trialIDBlock1(rowIndex) ...
    ), ...
    1:size(dataBlock1, 1), ...
    'UniformOutput', ...
    false ...
);

sourceDataBlock1 = array2table( ...
    dataBlock1, ...
    'VariableNames', ...
    variableNames, ...
    'RowNames', ...
    rowNamesBlock1 ...
);

writetable( ...
    sourceDataBlock1, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2B_Block1_ConditioningCohort.csv' ...
    ), ...
    'WriteVariableNames', ...
    true, ...
    'WriteRowNames', ...
    true ...
);

%% Save source data for block 3

rowNamesBlock3 = arrayfun( ...
    @(rowIndex) sprintf( ...
        'An%d_Tr%d', ...
        animalIDBlock3(rowIndex), ...
        trialIDBlock3(rowIndex) ...
    ), ...
    1:size(dataBlock3, 1), ...
    'UniformOutput', ...
    false ...
);

sourceDataBlock3 = array2table( ...
    dataBlock3, ...
    'VariableNames', ...
    variableNames, ...
    'RowNames', ...
    rowNamesBlock3 ...
);

writetable( ...
    sourceDataBlock3, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2B_Block3_ConditioningCohort.csv' ...
    ), ...
    'WriteVariableNames', ...
    true, ...
    'WriteRowNames', ...
    true ...
);

%% Save summarized plotted values

summarySourceData = table( ...
    xValues(:), ...
    block1Mean(:), ...
    block1SEM(:), ...
    block3Mean(:), ...
    block3SEM(:), ...
    'VariableNames', {
        'TimeBin'
        'Block1Mean'
        'Block1SEM'
        'Block3Mean'
        'Block3SEM'
    } ...
);

writetable( ...
    summarySourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2B_PlottedMeansAndSEM.csv' ...
    ) ...
);

%% Format axes

ax = gca;

ax.YLim = [0.9 1.15];
ax.YLabel.String = 'A.U.';
ax.XLabel.String = 'time [s]';

ax.XTick = 0:20:size(dataBlock1, 2);
ax.XTickLabel = -2:2:10;

ax.FontWeight = 'bold';
ax.LineWidth = 1;

%% Plot odor interval

odorPatch = patch( ...
    [20 44 44 20], ...
    [ ...
        ax.YLim(1) ...
        ax.YLim(1) ...
        ax.YLim(2) ...
        ax.YLim(2) ...
    ], ...
    [0.2 0.2 0.2] ...
);

odorPatch.FaceAlpha = 0.2;
odorPatch.EdgeAlpha = 0;

odorText = text( ...
    21, ...
    ax.YLim(1) + ...
        (ax.YLim(2) - ax.YLim(1)) * 0.06, ...
    'Odor' ...
);

odorText.Color = [0.2 0.2 0.2];

%% Legend and title

legend( ...
    [sd1.mainLine sd2.mainLine], ...
    {'Bl. 1', 'Bl. 3'}, ...
    'Location', ...
    'best' ...
);

title({ ...
    'lid data (pooled)', ...
    'Bl1 vs. Bl3' ...
});

%% Document source script

docDataSrc( ...
    fig, ...
    outputDir, ...
    scriptFile, ...
    true ...
);

%% Save figure

outputBaseName = ...
    'Figure_2B_Lid_Block3_vs_Block1';

pdfFile = fullfile( ...
    outputDir, ...
    [outputBaseName '.pdf'] ...
);

exportgraphics( ...
    fig, ...
    pdfFile, ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'none' ...
);

fprintf('\nFigure 2B outputs saved to:\n%s\n', outputDir);
fprintf('Figure file:\n%s\n', pdfFile);