% panel_C.m
% Jonathan Reinwald
%
% Reproduces Figure 2C:
% Intrasession eyelid responses across conditioning blocks 1-3.
%
% This script:
%   1. Loads processed eyelid data
%   2. Extracts the conditioning/reappraisal sessions
%   3. Plots the smoothed session time course
%   4. Plots animal-level mean responses for blocks 1-3
%   5. Exports the plotted source data
%
% Statistical testing is performed separately in:
% figures/main/Figure_2/panel_C_statistics.R
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_2/
% │   ├── panel_C.m
% │   └── panel_C_statistics.R
% ├── data/processed/eyelid/reappraisal/
% │   └── pupil_summary_all.mat
% ├── src/matlab/
% └── results/main/Figure_2/

clear;
close all;
clc;

%% Locate repository root automatically

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of panel_C.m. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% Script location:
% repository/figures/main/Figure_2/panel_C.m
%
% Move upwards:
% Figure_2 -> main -> figures -> repository
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Define repository directories

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputFile = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'eyelid', ...
    'reappraisal', ...
    'pupil_summary_all.mat' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_2' ...
);

%% Add MATLAB helper functions

if ~isfolder(srcDir)
    error([ ...
        'MATLAB source-code directory not found:\n%s\n\n' ...
        'Expected repository location:\n' ...
        'src/matlab/' ...
    ], srcDir);
end

addpath(genpath(srcDir));

%% Check required helper functions

requiredFunctions = {
    'shadedErrorBar'
    'SEM_calc'
    'notBoxPlot_modified_pupilANDlid'
    'docDataSrc'
};

functionPaths = cellfun( ...
    @which, ...
    requiredFunctions, ...
    'UniformOutput', ...
    false ...
);

missingFunctions = requiredFunctions( ...
    cellfun(@isempty, functionPaths) ...
);

if ~isempty(missingFunctions)
    error([ ...
        'The following required MATLAB functions were not found:\n\n%s\n\n' ...
        'Place these functions, and any functions they call, somewhere ' ...
        'inside src/matlab/ or one of its subfolders.' ...
    ], strjoin(missingFunctions, newline));
end

%% Check and load input data

if ~isfile(inputFile)
    error([ ...
        'Required input file not found:\n%s\n\n' ...
        'Expected repository location:\n' ...
        'data/processed/eyelid/reappraisal/pupil_summary_all.mat' ...
    ], inputFile);
end

loadedData = load(inputFile);

if ~isfield(loadedData, 'summary_all')
    error([ ...
        'The input MAT file does not contain the expected variable ' ...
        '"summary_all":\n%s' ...
    ], inputFile);
end

summary_all_rp = loadedData.summary_all;

if isempty(summary_all_rp)
    error('The variable "summary_all" is empty.');
end

%% Create output directory

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Select conditioning sessions

% Original summary_all ordering:
% 1 = conditioning/reappraisal
% 2 = 1 hour post
% 3 = 24 hours post
%
% Therefore, every third entry beginning with 1 is a conditioning session.
reappraisal_all = summary_all_rp(1:3:end);

if isempty(reappraisal_all)
    error('No conditioning/reappraisal sessions were found.');
end

%% Analysis and plotting settings

% Trial ranges included in the intrasession comparison
blockTrials = {
    11:40
    41:80
    81:120
};

numberOfBlocks = numel(blockTrials);

% Number of time samples per trial in LidDiameterMatrix
samplesPerTrial = 119;

% Original smoothing window: three trials
smoothingKernel = samplesPerTrial * 3;

% Original color used for the reappraisal session
sessionColor = [0 0.5 0.5];

%% Validate input structure

requiredFields = {
    'LidDiameterMatrix'
};

for animalIndex = 1:numel(reappraisal_all)

    for fieldIndex = 1:numel(requiredFields)

        fieldName = requiredFields{fieldIndex};

        if ~isfield(reappraisal_all(animalIndex), fieldName)
            error( ...
                'Animal/session %d is missing field "%s".', ...
                animalIndex, ...
                fieldName ...
            );
        end
    end
end

%% Construct continuous session data

numberOfAnimals = numel(reappraisal_all);

dataLong = [];

for animalIndex = 1:numberOfAnimals

    % Preserve the original conversion:
    % transpose the trial-by-time matrix and concatenate trials
    transposedData = ...
        reappraisal_all(animalIndex).LidDiameterMatrix';

    animalSessionData = transposedData(:)';

    if animalIndex == 1

        numberOfTimePoints = numel(animalSessionData);

        dataLong = nan( ...
            numberOfAnimals, ...
            numberOfTimePoints ...
        );

    elseif numel(animalSessionData) ~= numberOfTimePoints

        error([ ...
            'Animal/session %d has %d time points, whereas the first ' ...
            'animal/session has %d.' ...
        ], ...
            animalIndex, ...
            numel(animalSessionData), ...
            numberOfTimePoints ...
        );
    end

    dataLong(animalIndex, :) = animalSessionData;
end

%% Calculate animal-level block means

blockMeans = nan( ...
    numberOfAnimals, ...
    numberOfBlocks ...
);

for blockIndex = 1:numberOfBlocks

    currentTrials = blockTrials{blockIndex};

    startIndex = ...
        (currentTrials(1) - 1) * samplesPerTrial + 1;

    endIndex = ...
        currentTrials(end) * samplesPerTrial;

    if endIndex > size(dataLong, 2)
        error([ ...
            'The data contain only %d time points, but block %d ' ...
            'requires time point %d.' ...
        ], ...
            size(dataLong, 2), ...
            blockIndex, ...
            endIndex ...
        );
    end

    blockMeans(:, blockIndex) = mean( ...
        dataLong(:, startIndex:endIndex), ...
        2, ...
        'omitnan' ...
    );
end

%% Calculate plotted time-course values

sessionMean = mean( ...
    dataLong, ...
    1, ...
    'omitnan' ...
);

sessionSEM = SEM_calc(dataLong);

% Moving-average smoothing matching the original 357-sample window
smoothedSessionMean = movmean( ...
    sessionMean, ...
    smoothingKernel, ...
    'omitnan' ...
);

smoothedSessionSEM = movmean( ...
    sessionSEM, ...
    smoothingKernel, ...
    'omitnan' ...
);

xValues = 1:size(dataLong, 2);

%% Define common y-axis limits

yCenter = mean( ...
    dataLong(:), ...
    'omitnan' ...
);

timePointSD = std( ...
    dataLong, ...
    0, ...
    1, ...
    'omitnan' ...
);

ySpread = mean( ...
    timePointSD, ...
    'omitnan' ...
);

yLimits = [
    yCenter - 3 * ySpread
    yCenter + 3 * ySpread
];

if ~all(isfinite(yLimits)) || yLimits(1) == yLimits(2)
    yLimits = [
        min(dataLong(:), [], 'omitnan')
        max(dataLong(:), [], 'omitnan')
    ];
end

%% Create figure

fig = figure( ...
    'Name', ...
    'Figure 2C: Intrasession eyelid responses' ...
);

fig.Position = [100 100 900 400];

plotLayout = tiledlayout( ...
    fig, ...
    1, ...
    2, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact' ...
);

%% Left panel: continuous session time course

nexttile(plotLayout, 1);

sessionPlot = shadedErrorBar( ...
    xValues, ...
    smoothedSessionMean, ...
    smoothedSessionSEM ...
);

sessionPlot.mainLine.Color = sessionColor;
sessionPlot.mainLine.LineWidth = 1.5;

sessionPlot.patch.FaceColor = sessionColor;
sessionPlot.patch.FaceAlpha = 0.25;
sessionPlot.patch.EdgeColor = 'none';

sessionPlot.edge(1).Color = 'none';
sessionPlot.edge(2).Color = 'none';

hold on;

axTimeCourse = gca;

axTimeCourse.YLim = yLimits;
axTimeCourse.YLabel.String = 'A.U.';
axTimeCourse.XLabel.String = 'time [min]';
axTimeCourse.FontWeight = 'bold';
axTimeCourse.LineWidth = 1;

% Original timing convention:
% 1,200 samples correspond to two minutes
samplesPerTwoMinutes = 1200;

axTimeCourse.XTick = ...
    0:samplesPerTwoMinutes:size(dataLong, 2);

axTimeCourse.XTickLabel = ...
    0:2:(2 * floor(size(dataLong, 2) / samplesPerTwoMinutes));

%% Mark the puff block

puffBlockTrials = blockTrials{2};

puffBlockStart = ...
    (puffBlockTrials(1) - 1) * samplesPerTrial + 1;

puffBlockEnd = ...
    puffBlockTrials(end) * samplesPerTrial;

puffPatch = patch( ...
    [ ...
        puffBlockStart ...
        puffBlockEnd ...
        puffBlockEnd ...
        puffBlockStart ...
    ], ...
    [ ...
        yLimits(1) ...
        yLimits(1) ...
        yLimits(2) ...
        yLimits(2) ...
    ], ...
    [0.2 0.2 0.2] ...
);

puffPatch.FaceAlpha = 0.2;
puffPatch.EdgeAlpha = 0;

puffText = text( ...
    puffBlockStart + 100, ...
    yLimits(1) + 0.1 * diff(yLimits), ...
    'Puff-Block' ...
);

puffText.Color = [0.2 0.2 0.2];

%% Mark the habituation period

habituationEnd = 10 * samplesPerTrial;

habituationPatch = patch( ...
    [ ...
        1 ...
        habituationEnd ...
        habituationEnd ...
        1 ...
    ], ...
    [ ...
        yLimits(1) ...
        yLimits(1) ...
        yLimits(2) ...
        yLimits(2) ...
    ], ...
    [131/244 208/244 1] ...
);

habituationPatch.FaceAlpha = 0.2;
habituationPatch.EdgeAlpha = 0;

habituationText = text( ...
    100, ...
    yLimits(1) + 0.1 * diff(yLimits), ...
    'Habituation' ...
);

habituationText.Color = [131/244 208/244 1];

legend( ...
    sessionPlot.mainLine, ...
    {'Conditioning'}, ...
    'Location', ...
    'best' ...
);

title( ...
    sprintf( ...
        'Lid data smoothed (%d-sample window)', ...
        smoothingKernel ...
    ) ...
);

%% Right panel: animal-level block means

nexttile(plotLayout, 2);

blockPlot = ...
    notBoxPlot_modified_pupilANDlid(blockMeans);

for blockIndex = 1:numberOfBlocks

    blockPlot(blockIndex).sdPtch.EdgeColor = 'none';
    blockPlot(blockIndex).semPtch.EdgeColor = 'none';

    blockPlot(blockIndex).sdPtch.FaceColor = sessionColor;
    blockPlot(blockIndex).semPtch.FaceColor = sessionColor;

    blockPlot(blockIndex).sdPtch.FaceAlpha = 0.1;
    blockPlot(blockIndex).semPtch.FaceAlpha = 0.3;

    blockPlot(blockIndex).mu.Color = sessionColor;

    blockPlot(blockIndex).data.MarkerFaceColor = sessionColor;
    blockPlot(blockIndex).data.MarkerEdgeColor = 'none';
end

axBlockMeans = gca;

axBlockMeans.YLim = yLimits;
axBlockMeans.XTick = 1:numberOfBlocks;
axBlockMeans.XTickLabel = {'Block 1', 'Block 2', 'Block 3'};

axBlockMeans.YLabel.String = {
    'A.U.'
    'mean per block'
};

axBlockMeans.XLabel.String = 'block';
axBlockMeans.FontWeight = 'bold';
axBlockMeans.LineWidth = 1;

title('Mean eyelid response');

%% Save continuous-session source data

animalVariableNames = arrayfun( ...
    @(animalIndex) sprintf('Animal_%d', animalIndex), ...
    1:numberOfAnimals, ...
    'UniformOutput', ...
    false ...
);

sessionSourceData = array2table( ...
    dataLong', ...
    'VariableNames', ...
    animalVariableNames ...
);

sessionSourceData = addvars( ...
    sessionSourceData, ...
    (1:size(dataLong, 2))', ...
    'Before', ...
    1, ...
    'NewVariableNames', ...
    'TimeIndex' ...
);

writetable( ...
    sessionSourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2C_ContinuousSession.csv' ...
    ) ...
);

%% Save plotted mean and SEM

plottedSummary = table( ...
    xValues(:), ...
    sessionMean(:), ...
    sessionSEM(:), ...
    smoothedSessionMean(:), ...
    smoothedSessionSEM(:), ...
    'VariableNames', {
        'TimeIndex'
        'Mean'
        'SEM'
        'SmoothedMean'
        'SmoothedSEM'
    } ...
);

writetable( ...
    plottedSummary, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2C_PlottedMeanAndSEM.csv' ...
    ) ...
);

%% Save animal-level block means

blockSourceData = array2table( ...
    blockMeans, ...
    'VariableNames', {
        'Block1'
        'Block2'
        'Block3'
    } ...
);

blockSourceData = addvars( ...
    blockSourceData, ...
    (1:numberOfAnimals)', ...
    'Before', ...
    1, ...
    'NewVariableNames', ...
    'AnimalID' ...
);

writetable( ...
    blockSourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure2C_BlockMeans.csv' ...
    ) ...
);

%% Document source script

docDataSrc( ...
    fig, ...
    outputDir, ...
    scriptFile, ...
    true ...
);

%% Save figure

outputFile = fullfile( ...
    outputDir, ...
    'Figure_2C_Intrasession_Eyelid_Response.pdf' ...
);

exportgraphics( ...
    fig, ...
    outputFile, ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'none' ...
);

fprintf('\nFigure 2C outputs saved to:\n%s\n', outputDir);
fprintf('Figure file:\n%s\n', outputFile);