% panel_E.m
% Jonathan Reinwald
%
% Reproduces Figure 2E:
% High-resolution trial-by-time BOLD heat maps for trials 11–40.
%
% The script processes:
%   1. mask_activation_v22_T001
%   2. mask_deactivation_v22_T001
%
% Required input in each ROI folder:
%   tc_matrsess_all_BINS6_TRsbefore2.mat
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_2/panel_E.m
% ├── data/processed/fMRI/Figure_2E/
% │   ├── mask_activation_v22_T001/
% │   │   └── tc_matrsess_all_BINS6_TRsbefore2.mat
% │   └── mask_deactivation_v22_T001/
% │       └── tc_matrsess_all_BINS6_TRsbefore2.mat
% ├── src/matlab/
% └── results/main/Figure_2/Figure_2E/

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of panel_E.m. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% panel_E.m is located at:
% repository/figures/main/Figure_2/panel_E.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Define repository paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

baseInputDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_2E' ...
);

baseOutputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_2', ...
    'Figure_2E' ...
);

%% Define ROI folders

roiNames = {
    'mask_activation_v22_T001'
    'mask_deactivation_v22_T001'
};

%% Analysis settings

% Trials shown in Figure 2E after trial reordering
selectedTrials = 11:40;

% Original three-trial smoothing
smoothingWindow = 3;

% Original color limits
colorLimits = [-1, 1];

%% Add repository MATLAB functions

if isfolder(srcDir)
    addpath(genpath(srcDir));
else
    warning( ...
        'Repository MATLAB source folder was not found:\n%s', ...
        srcDir ...
    );
end

% docDataSrc is optional here
useDocDataSrc = ~isempty(which('docDataSrc'));

%% Create output directory

if ~isfolder(baseOutputDir)
    mkdir(baseOutputDir);
end

%% Process both ROI folders

for roiIndex = 1:numel(roiNames)

    roiName = roiNames{roiIndex};

    fprintf('\nProcessing ROI: %s\n', roiName);

    %% Define ROI-specific paths

    inputDir = fullfile( ...
        baseInputDir, ...
        roiName ...
    );

    outputDir = fullfile( ...
        baseOutputDir, ...
        roiName ...
    );

    tcFile = fullfile( ...
        inputDir, ...
        'tc_matrsess_all_BINS6_TRsbefore2.mat' ...
    );

    if ~isfile(tcFile)
        error( ...
            'Required input file not found:\n%s', ...
            tcFile ...
        );
    end

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end

    %% Load high-resolution BOLD data

    loadedData = load(tcFile);

    requiredVariables = {
        'tc_matrsess_all_highres_lin'
        'puff_matrsess_all'
        'tc_matrsess_info'
    };

    missingVariables = requiredVariables( ...
        ~isfield(loadedData, requiredVariables) ...
    );

    if ~isempty(missingVariables)
        error([ ...
            'The following variables are missing from:\n%s\n\n%s' ...
        ], ...
            tcFile, ...
            strjoin(missingVariables, newline) ...
        );
    end

    tcAllHighRes = ...
        loadedData.tc_matrsess_all_highres_lin;

    puffMatrix = ...
        loadedData.puff_matrsess_all;

    tcInfo = ...
        loadedData.tc_matrsess_info;

    %% Validate dimensions

    numberOfSubjects = size(tcAllHighRes, 1);
    numberOfOriginalTrials = size(tcAllHighRes, 2);

    if size(puffMatrix, 1) ~= numberOfSubjects
        error( ...
            'BOLD data and puff matrix have different subject counts.' ...
        );
    end

    if size(puffMatrix, 2) ~= numberOfOriginalTrials
        error( ...
            'BOLD data and puff matrix have different trial counts.' ...
        );
    end

    %% Reorder trials

    % Final trial sequence:
    %   1:40    initial no-puff trials
    %   41:68   puff trials
    %   69:120  remaining no-puff trials

    puffPositions = 41:68;
    noPuffPositions = [1:40, 69:120];

    numberOfSortedTrials = 120;
    numberOfTimeBins = size(tcAllHighRes, 3);

    tcSortedHighRes = nan( ...
        numberOfSubjects, ...
        numberOfSortedTrials, ...
        numberOfTimeBins ...
    );

    for subjectIndex = 1:numberOfSubjects

        puffMask = logical( ...
            puffMatrix(subjectIndex, :) ...
        );

        noPuffMask = ~puffMask;

        if sum(puffMask) ~= numel(puffPositions)
            error([ ...
                'Subject %d in ROI "%s" has %d puff trials; ' ...
                '%d were expected.' ...
            ], ...
                subjectIndex, ...
                roiName, ...
                sum(puffMask), ...
                numel(puffPositions) ...
            );
        end

        if sum(noPuffMask) ~= numel(noPuffPositions)
            error([ ...
                'Subject %d in ROI "%s" has %d non-puff trials; ' ...
                '%d were expected.' ...
            ], ...
                subjectIndex, ...
                roiName, ...
                sum(noPuffMask), ...
                numel(noPuffPositions) ...
            );
        end

        tcSortedHighRes( ...
            subjectIndex, ...
            puffPositions, ...
            : ...
        ) = tcAllHighRes( ...
            subjectIndex, ...
            puffMask, ...
            : ...
        );

        tcSortedHighRes( ...
            subjectIndex, ...
            noPuffPositions, ...
            : ...
        ) = tcAllHighRes( ...
            subjectIndex, ...
            noPuffMask, ...
            : ...
        );
    end

    %% Calculate median across subjects

    medianHighRes = squeeze( ...
        median( ...
            tcSortedHighRes, ...
            1, ...
            'omitnan' ...
        ) ...
    );

    %% Select trials 11–40

    selectedData = medianHighRes( ...
        selectedTrials, ...
        : ...
    );

    %% Smooth across neighboring trials

    plottedData = movmean( ...
        selectedData, ...
        smoothingWindow, ...
        1, ...
        'omitnan' ...
    );

    %% Create heat map

    fig = figure( ...
        'Name', ...
        ['Figure 2E: ' roiName], ...
        'Visible', ...
        'on', ...
        'Color', ...
        'white' ...
    );

    imagesc(plottedData);

    ax = gca;

    box(ax, 'off');

    ax.CLim = colorLimits;
    ax.TickLabelInterpreter = 'none';
    ax.FontWeight = 'bold';

    colormap(ax, jet(256));

    colorBar = colorbar;
    colorBar.Label.String = 'BOLD [A.U., z-scored]';

    %% Configure x-axis

    timeLabels = -2.4:1.2:8.4;

    if isfield(tcInfo, 'highres')
        resolution = tcInfo.highres;
    else
        resolution = size(plottedData, 2) / 10;
        warning( ...
            'tc_matrsess_info.highres was not found; using inferred resolution.' ...
        );
    end

    xTickPositions = ...
        (1:resolution:size(plottedData, 2)) - 0.5;

    if numel(xTickPositions) ~= numel(timeLabels)

        xTickPositions = linspace( ...
            0.5, ...
            size(plottedData, 2) - 0.5, ...
            numel(timeLabels) ...
        );
    end

    ax.XTick = xTickPositions;
    ax.XTickLabel = timeLabels;
    ax.XLabel.String = 'time [s]';

    xtickangle(ax, 30);

    %% Configure y-axis

    % Display original trial numbers rather than 1–30
    yTickTrials = [11, 20, 30, 40];

    ax.YTick = ...
        yTickTrials - selectedTrials(1) + 1;

    ax.YTickLabel = yTickTrials;
    ax.YLabel.String = 'trials';

    %% Add odor period

    hold on;

    currentResolution = ...
        size(plottedData, 2) / 10;

    currentOnsetFrame = ...
        2 * size(plottedData, 2) / 10 + 1 - 0.5;

    odorEnd = ...
        currentOnsetFrame + ...
        (2.4 * currentResolution) / 1.2;

    odorPatch = patch( ...
        [ ...
            currentOnsetFrame, ...
            odorEnd, ...
            odorEnd, ...
            currentOnsetFrame ...
        ], ...
        [ ...
            ax.YLim(1), ...
            ax.YLim(1), ...
            ax.YLim(2), ...
            ax.YLim(2) ...
        ], ...
        [0.2, 0.2, 0.2] ...
    );

    odorPatch.FaceAlpha = 0.2;
    odorPatch.EdgeColor = 'none';

    odorText = text( ...
        currentOnsetFrame * 1.05, ...
        ax.YLim(1) + 0.15 * diff(ax.YLim), ...
        'Odor' ...
    );

    odorText.Color = [0.2, 0.2, 0.2];
    odorText.FontWeight = 'bold';

    %% Add title

    title( ...
        strrep(roiName, '_', '\_'), ...
        'Interpreter', ...
        'tex' ...
    );

    %% Save plotted source data

    timeBinNames = arrayfun( ...
        @(index) sprintf('TimeBin_%03d', index), ...
        1:size(plottedData, 2), ...
        'UniformOutput', ...
        false ...
    );

    sourceData = array2table( ...
        plottedData, ...
        'VariableNames', ...
        timeBinNames ...
    );

    sourceData = addvars( ...
        sourceData, ...
        selectedTrials', ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        'Trial' ...
    );

    sourceDataFile = fullfile( ...
        outputDir, ...
        'SourceData_Figure2E_HighResolution_Trials11to40.csv' ...
    );

    writetable( ...
        sourceData, ...
        sourceDataFile ...
    );

    %% Save analysis metadata

    metadata = table( ...
        string(roiName), ...
        numberOfSubjects, ...
        selectedTrials(1), ...
        selectedTrials(end), ...
        smoothingWindow, ...
        colorLimits(1), ...
        colorLimits(2), ...
        'VariableNames', {
            'ROI'
            'NumberOfSubjects'
            'FirstTrial'
            'LastTrial'
            'TrialSmoothingWindow'
            'ColorLimitMinimum'
            'ColorLimitMaximum'
        } ...
    );

    writetable( ...
        metadata, ...
        fullfile( ...
            outputDir, ...
            'AnalysisMetadata_Figure2E.csv' ...
        ) ...
    );

    %% Document source script

    if useDocDataSrc
        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );
    end

    %% Export figure

    outputFile = fullfile( ...
        outputDir, ...
        ['Figure_2E_' roiName ...
         '_HighResolution_Trials11to40.pdf'] ...
    );

    exportgraphics( ...
        fig, ...
        outputFile, ...
        'ContentType', ...
        'vector', ...
        'BackgroundColor', ...
        'white' ...
    );

    fprintf('Saved figure:\n%s\n', outputFile);
    fprintf('Saved source data:\n%s\n', sourceDataFile);
end

fprintf('\nFigure 2E processing completed.\n');
fprintf('Outputs saved under:\n%s\n', baseOutputDir);