function filePath = find_unique_subject_file(rootDir, subjectID, pattern)
% FIND_UNIQUE_SUBJECT_FILE Find one subject-specific file recursively.

if ~isfolder(rootDir)
    error('Search root not found:\n%s', rootDir);
end

files = dir(fullfile(rootDir, '**', pattern));
files = files(~[files.isdir]);

if isempty(files)
    error('No files matching "%s" below:\n%s', pattern, rootDir);
end

fullPaths = arrayfun( ...
    @(x) fullfile(x.folder, x.name), ...
    files, ...
    'UniformOutput', ...
    false ...
);

isSubject = contains( ...
    string(fullPaths), ...
    string(subjectID), ...
    'IgnoreCase', ...
    true ...
);

fullPaths = fullPaths(isSubject);

if numel(fullPaths) ~= 1
    error( ...
        'Expected one "%s" file for %s; found %d.', ...
        pattern, ...
        subjectID, ...
        numel(fullPaths) ...
    );
end

filePath = fullPaths{1};

end
