% panel_A_control.m
% Jonathan Reinwald
%
% Repository-adapted BASCO correlation-matrix analysis.
%
% Cohort: Control cohort
%
% For TPnoPuff (proximal CR), this script generates:
%   1. Mean connectivity matrix for PRE trials 11-40
%   2. Mean connectivity matrix for TEST trials 81-120
%   3. Paired TEST > PRE T-statistic matrix with FDR marking
%   4. FDR-thresholded schemaball for the TEST > PRE comparison
%
% Mean PRE/TEST matrices:
%   colormap = jet
%   color limits = [-1 1]
%
% TEST > PRE comparison:
%   paired edge-wise test using lei_pairedtt
%   FDR threshold = 0.05
%   custom magenta-blue colormap
%   color limits = [-5 5]

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error(['MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.']);
end

scriptDir = fileparts(scriptFile);
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile(repoRoot,'src','matlab');

inputDir = fullfile( ...
    repoRoot,'data','processed','fMRI','Figure_3','control' ...
);

outputDir = fullfile( ...
    repoRoot,'results','main','Figure_3','Figure_3A','control' ...
);

colormapFile = fullfile( ...
    srcDir,'helpers','colormaps','myColormap_magentablue.mat' ...
);

%% Analysis settings

cohortName = 'Control cohort';
cormatSuffix = 'v6';

analysisTypes = {
    'TPnoPuff'
};

preRangeLabel = '11to40';
testRangeLabel = '81to120';

fdrThreshold = 0.05;
meanColorLimits = [-1,1];
comparisonColorLimits = [-5,5];

% Original anatomical ROI ordering
sorting = [ ...
    4:8,42:43,24:27,1:3,28,12:16,19,18,17,20,21,9:11, ...
    32:33,29:31,34:35,38:41,45:52,22:23,36,37,44 ...
];

%% Add repository MATLAB helpers

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s',srcDir);
end

addpath(genpath(srcDir));

requiredFunctions = {'lei_pairedtt','schemaball'};

functionPaths = cellfun(@which,requiredFunctions,'UniformOutput',false);
missingFunctions = requiredFunctions(cellfun(@isempty,functionPaths));

if ~isempty(missingFunctions)
    error(['Required MATLAB functions not found:\n%s\n\n' ...
        'Place them under src/matlab/ or a subfolder.'], ...
        strjoin(missingFunctions,newline));
end

%% Check folders and custom colormap

if ~isfolder(inputDir)
    error('Input directory not found:\n%s',inputDir);
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

if ~isfile(colormapFile)
    error(['Custom colormap not found:\n%s\n\n' ...
        'Expected: src/matlab/colormaps/myColormap_magentablue.mat'], ...
        colormapFile);
end

colormapData = load(colormapFile);

if ~isfield(colormapData,'myColormap')
    error('The colormap file does not contain variable "myColormap":\n%s', ...
        colormapFile);
end

myColormap = colormapData.myColormap;

%% Load ROI names

roiDataFiles = dir(fullfile(inputDir,'roidata*.mat'));

if isempty(roiDataFiles)
    error('No roidata*.mat file was found in:\n%s',inputDir);
end

[~,roiOrder] = sort({roiDataFiles.name});
roiDataFiles = roiDataFiles(roiOrder);

if numel(roiDataFiles) > 1
    warning('Multiple roidata files found. Using:\n%s',roiDataFiles(1).name);
end

roiDataFile = fullfile(roiDataFiles(1).folder,roiDataFiles(1).name);
roiData = load(roiDataFile);

if ~isfield(roiData,'subj') || ...
        ~isfield(roiData.subj(1),'roi') || ...
        ~isfield(roiData.subj(1).roi,'name')
    error('Could not read ROI names from variable subj in:\n%s',roiDataFile);
end

roiNamesUnsorted = {roiData.subj(1).roi.name};

if max(sorting) > numel(roiNamesUnsorted)
    error(['The sorting vector requires at least %d ROIs, but only %d ' ...
        'were found.'],max(sorting),numel(roiNamesUnsorted));
end

roiNames = roiNamesUnsorted(sorting);
numberOfROIs = numel(roiNames);

%% Process analysis

for analysisIndex = 1:numel(analysisTypes)

    analysisName = analysisTypes{analysisIndex};

    fprintf('\n============================================\n');
    fprintf('%s: %s\n',cohortName,analysisName);
    fprintf('============================================\n');

    %% Define PRE and TEST files

    preFileName = sprintf( ...
        'cormat_%s_%s%s.mat', ...
        cormatSuffix,analysisName,preRangeLabel ...
    );

    testFileName = sprintf( ...
        'cormat_%s_%s%s.mat', ...
        cormatSuffix,analysisName,testRangeLabel ...
    );

    preFile = fullfile(inputDir,preFileName);
    testFile = fullfile(inputDir,testFileName);

    if ~isfile(preFile)
        error('PRE cormat file not found:\n%s',preFile);
    end

    if ~isfile(testFile)
        error('TEST cormat file not found:\n%s',testFile);
    end

    %% Load cormats

    preLoaded = load(preFile);
    testLoaded = load(testFile);

    if ~isfield(preLoaded,'cormat')
        error('Variable "cormat" is missing from:\n%s',preFile);
    end

    if ~isfield(testLoaded,'cormat')
        error('Variable "cormat" is missing from:\n%s',testFile);
    end

    cormatPre = preLoaded.cormat;
    cormatTest = testLoaded.cormat;

    if ~iscell(cormatPre) || ~iscell(cormatTest)
        error('Both cormat variables must be cell arrays.');
    end

    if numel(cormatPre) ~= numel(cormatTest)
        error(['%s PRE and TEST contain different subject counts: ' ...
            '%d versus %d.'], ...
            analysisName,numel(cormatPre),numel(cormatTest));
    end

    numberOfSubjects = numel(cormatPre);

    if numberOfSubjects == 0
        error('%s cormat arrays are empty.',analysisName);
    end

    %% Validate and reorder ROIs

    for subjectIndex = 1:numberOfSubjects

        preMatrix = cormatPre{subjectIndex};
        testMatrix = cormatTest{subjectIndex};

        if ~ismatrix(preMatrix) || size(preMatrix,1) ~= size(preMatrix,2)
            error('PRE matrix for subject %d is not square.',subjectIndex);
        end

        if ~ismatrix(testMatrix) || size(testMatrix,1) ~= size(testMatrix,2)
            error('TEST matrix for subject %d is not square.',subjectIndex);
        end

        if size(preMatrix,1) < max(sorting) || ...
                size(testMatrix,1) < max(sorting)
            error(['Subject %d contains fewer ROIs than required by ' ...
                'the sorting vector.'],subjectIndex);
        end

        cormatPre{subjectIndex} = preMatrix(sorting,sorting);
        cormatTest{subjectIndex} = testMatrix(sorting,sorting);
    end

    %% Mean PRE and TEST connectivity matrices

    pre3D = cat(3,cormatPre{:});
    test3D = cat(3,cormatTest{:});

    meanPre = mean(pre3D,3,'omitnan');
    meanTest = mean(test3D,3,'omitnan');

    %% Plot PRE mean matrix

    preTitle = sprintf( ...
        '%s: %s PRE (trials 11-40)', ...
        cohortName,analysisName ...
    );

    figPre = plotMeanMatrix( ...
        meanPre,roiNames,meanColorLimits,preTitle ...
    );

    exportgraphics( ...
        figPre, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_PRE_11to40.pdf',analysisName)), ...
        'ContentType','vector','BackgroundColor','white' ...
    );

    exportgraphics( ...
        figPre, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_PRE_11to40.png',analysisName)), ...
        'Resolution',300,'BackgroundColor','white' ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,sprintf( ...
            'SourceData_Figure3_control_%s_PRE_11to40.csv', ...
            analysisName)), ...
        meanPre,roiNames ...
    );

    %% Plot TEST mean matrix

    testTitle = sprintf( ...
        '%s: %s TEST (trials 81-120)', ...
        cohortName,analysisName ...
    );

    figTest = plotMeanMatrix( ...
        meanTest,roiNames,meanColorLimits,testTitle ...
    );

    exportgraphics( ...
        figTest, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_81to120.pdf',analysisName)), ...
        'ContentType','vector','BackgroundColor','white' ...
    );

    exportgraphics( ...
        figTest, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_81to120.png',analysisName)), ...
        'Resolution',300,'BackgroundColor','white' ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,sprintf( ...
            'SourceData_Figure3_control_%s_TEST_81to120.csv', ...
            analysisName)), ...
        meanTest,roiNames ...
    );

    %% Paired TEST > PRE edge-wise comparison

    [T,p,p2,fdrMatrix,meanValue,standardDeviation] = ...
        lei_pairedtt(cormatTest,cormatPre,fdrThreshold);

    if ~isequal(size(T),[numberOfROIs,numberOfROIs])
        error('lei_pairedtt returned a T matrix of unexpected size.');
    end

    displayT = tril(T,-1);
    displayT(displayT == 0) = NaN;

    comparisonTitle = sprintf( ...
        '%s: %s TEST > PRE, paired', ...
        cohortName,analysisName ...
    );

    figComparison = figure( ...
        'Name',comparisonTitle, ...
        'Visible','on', ...
        'Color','white', ...
        'Position',[100,100,900,780] ...
    );

    imagesc(displayT,'AlphaData',~isnan(displayT));

    ax = gca;
    axis(ax,'image');
    box(ax,'off');

    ax.CLim = comparisonColorLimits;
    ax.TickLabelInterpreter = 'none';
    ax.XTick = 1:numberOfROIs;
    ax.XTickLabel = roiNames;
    ax.YTick = 1:numberOfROIs;
    ax.YTickLabel = roiNames;
    ax.FontSize = 5;

    colormap(ax,flipud(myColormap));
    xtickangle(ax,90);

    title(comparisonTitle,'Interpreter','none');
    colorbar;
    hold on;

    % Mark FDR-significant cells in the displayed lower triangle
    for rowIndex = 2:numberOfROIs
        for columnIndex = 1:(rowIndex - 1)

            if fdrMatrix(rowIndex,columnIndex)
                rectangle( ...
                    'Position',[columnIndex-0.5,rowIndex-0.5,1,1], ...
                    'EdgeColor',[0.3,0.3,0.3], ...
                    'LineWidth',1 ...
                );
            end
        end
    end

    exportgraphics( ...
        figComparison, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_vs_PRE_PairedTMatrix.pdf', ...
            analysisName)), ...
        'ContentType','vector','BackgroundColor','white' ...
    );

    exportgraphics( ...
        figComparison, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_vs_PRE_PairedTMatrix.png', ...
            analysisName)), ...
        'Resolution',300,'BackgroundColor','white' ...
    );

    %% FDR-thresholded schemaball

    symmetricFDR = logical(fdrMatrix | fdrMatrix');
    symmetricSignificantT = double(symmetricFDR) .* T;

    figSchemaball = figure( ...
        'Name',[comparisonTitle ' schemaball'], ...
        'Visible','on', ...
        'Color','white', ...
        'Position',[100,100,900,780] ...
    );

    schemaball( ...
        roiNames, ...
        symmetricSignificantT, ...
        10, ...
        comparisonColorLimits ...
    );

    title(comparisonTitle,'Interpreter','none');

    exportgraphics( ...
        figSchemaball, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_vs_PRE_Schemaball.pdf', ...
            analysisName)), ...
        'ContentType','vector','BackgroundColor','white' ...
    );

    exportgraphics( ...
        figSchemaball, ...
        fullfile(outputDir,sprintf( ...
            'Figure_3A_control_%s_TEST_vs_PRE_Schemaball.png', ...
            analysisName)), ...
        'Resolution',300,'BackgroundColor','white' ...
    );

    %% Save comparison statistics/source data

    filePrefix = sprintf( ...
        'Figure3_control_%s_TEST_vs_PRE', ...
        analysisName ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['SourceData_' filePrefix ...
        '_DisplayedTMatrix.csv']), ...
        displayT,roiNames ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['Statistics_' filePrefix '_T_full.csv']), ...
        T,roiNames ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['Statistics_' filePrefix '_P.csv']), ...
        p,roiNames ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['Statistics_' filePrefix '_P2.csv']), ...
        p2,roiNames ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['Statistics_' filePrefix '_FDR.csv']), ...
        double(fdrMatrix),roiNames ...
    );

    writeLabeledMatrix( ...
        fullfile(outputDir,['SourceData_' filePrefix ...
        '_FDRThresholdedT.csv']), ...
        symmetricSignificantT,roiNames ...
    );

    %% Save complete results and metadata

    save( ...
        fullfile(outputDir,['Statistics_' filePrefix ...
        '_CompleteResults.mat']), ...
        'T','p','p2','fdrMatrix','meanValue','standardDeviation', ...
        'displayT','symmetricSignificantT','meanPre','meanTest', ...
        'roiNames','sorting','preFileName','testFileName', ...
        'analysisName','cohortName','fdrThreshold','numberOfSubjects' ...
    );

    metadata = table( ...
        string(cohortName), ...
        string(analysisName), ...
        string(preFileName), ...
        string(testFileName), ...
        numberOfSubjects, ...
        numberOfROIs, ...
        fdrThreshold, ...
        'VariableNames',{ ...
            'Cohort', ...
            'Analysis', ...
            'PreFile', ...
            'TestFile', ...
            'NumberOfSubjects', ...
            'NumberOfROIs', ...
            'FDRThreshold' ...
        } ...
    );

    writetable( ...
        metadata, ...
        fullfile(outputDir,sprintf( ...
            'AnalysisMetadata_Figure3_control_%s.csv', ...
            analysisName)) ...
    );

    %% Optional source-script documentation

    if ~isempty(which('docDataSrc'))
        try
            docDataSrc(figComparison,outputDir,scriptFile,true);
        catch documentationError
            warning('docDataSrc failed: %s',documentationError.message);
        end
    end

    fprintf('Completed %s: PRE, TEST, and TEST > PRE.\n',analysisName);
end

fprintf('\nCompleted %s Figure 3 analysis.\n',cohortName);
fprintf('Outputs saved to:\n%s\n',outputDir);

%% Local functions

function figHandle = plotMeanMatrix( ...
    matrixData,roiNames,colorLimits,figureTitle ...
)
% Plot a full mean connectivity matrix using the original jet display.

    numberOfROIs = numel(roiNames);

    figHandle = figure( ...
        'Name',figureTitle, ...
        'Visible','on', ...
        'Color','white', ...
        'Position',[100,100,900,780] ...
    );

    imagesc(matrixData,'AlphaData',~isnan(matrixData));

    ax = gca;
    axis(ax,'image');
    box(ax,'off');

    ax.CLim = colorLimits;
    ax.TickLabelInterpreter = 'none';
    ax.XTick = 1:numberOfROIs;
    ax.XTickLabel = roiNames;
    ax.YTick = 1:numberOfROIs;
    ax.YTickLabel = roiNames;
    ax.FontSize = 5;

    colormap(ax,jet(256));
    xtickangle(ax,90);

    title(figureTitle,'Interpreter','none');
    colorbar;
end


function writeLabeledMatrix(filePath,matrixData,labels)
% Write a numeric matrix with matching row and column ROI labels.

    labels = labels(:);
    numberOfLabels = numel(labels);

    if ~isequal(size(matrixData),[numberOfLabels,numberOfLabels])
        error('Matrix dimensions do not match the number of ROI labels.');
    end

    outputCell = cell(numberOfLabels+1,numberOfLabels+1);

    outputCell(1,2:end) = labels';
    outputCell(2:end,1) = labels;
    outputCell(2:end,2:end) = num2cell(matrixData);

    writecell(outputCell,filePath);
end
