% panel_B_control_vs_conditioning.m
% Jonathan Reinwald
%
% Repository-adapted NBS analysis.
%
% Analysis: TPnoPuff
% Figure destination: Figure 3B
%
% This script:
%   1. Loads PRE (trials 11-40) and TEST (trials 81-120) cormats
%      for the control and conditioning cohorts.
%   2. Calculates within-animal TEST - PRE connectivity-change matrices.
%   3. Compares these change matrices between cohorts.
%   4. Runs the original NBS procedure.
%   5. Plots the edge-wise T-statistic matrix with NBS-significant
%      connections outlined.
%   6. Plots the NBS-thresholded schemaball.
%   7. Exports source data, design matrices, NBS input matrices and results.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/
% │   ├── main/Figure_3/panel_B_TPnoPuff_NBS_control_vs_conditioning.m
% │   └── supplement/Figure_S5/figure_S5_Odor_NBS_control_vs_conditioning.m
% │
% ├── data/processed/fMRI/Figure_3/
% │   ├── conditioning/
% │   │   ├── cormat_v11_TPnoPuff11to40.mat
% │   │   ├── cormat_v11_TPnoPuff81to120.mat
% │   │   └── roidata*.mat
% │   └── control/
% │       ├── cormat_v6_TPnoPuff11to40.mat
% │       ├── cormat_v6_TPnoPuff81to120.mat
% │       └── roidata*.mat
% │
% ├── src/matlab/
% │   ├── acl_NBS_intercept.m
% │   ├── lei_ttest2.m
% │   ├── schemaball.m
% │   ├── colormaps/myColormap_darkredgreen.mat
% │   └── NBS/input_files/
% │       ├── UI.mat
% │       ├── COG.txt
% │       └── nodeLabels.txt
% │
% └── results/main/Figure_3/Figure_3B/
%
% Original contrast structure retained:
%   [1 -1]  control > conditioning
%   [-1 1]  conditioning > control
%   [1 1]
%
% The plotted NBS mask preferentially uses CON_MAT2, as in the original
% script, corresponding to conditioning > control.

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% This script is expected to be three folders below repository root:
% repository/figures/.../<figure>/<script>.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputDirControl = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_3', ...
    'control' ...
);

inputDirConditioning = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_3', ...
    'conditioning' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_3', ...
    'Figure_3B' ...
);

nbsInputDir = fullfile( ...
    srcDir, ...
    'helpers', ...
    'NBS1.2', ...
    'input_files' ...
);

colormapFile = fullfile( ...
    srcDir, ...
    'helpers', ...
    'colormaps', ...
    'myColormap_darkredgreen.mat' ...
);

%% Analysis settings

analysisName = 'TPnoPuff';

controlSuffix = 'v6';
conditioningSuffix = 'v11';

preRange = '11to40';
testRange = '81to120';

inputType = {'Extent'};
thresholdProbability = 0.975;

fdrThreshold = 0.05;
tColorLimits = [-5, 5];

sorting = [ ...
    4:8, ...
    42:43, ...
    24:27, ...
    1:3, ...
    28, ...
    12:16, ...
    19, ...
    18, ...
    17, ...
    20, ...
    21, ...
    9:11, ...
    32:33, ...
    29:31, ...
    34:35, ...
    38:41, ...
    45:52, ...
    22:23, ...
    36, ...
    37, ...
    44 ...
];

%% Add repository MATLAB code

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

requiredFunctions = {
    'acl_NBS_intercept'
    'lei_ttest2'
    'schemaball'
};

functionPaths = cellfun( ...
    @which, ...
    requiredFunctions, ...
    'UniformOutput', ...
    false ...
);

missingFunctions = requiredFunctions(cellfun(@isempty, functionPaths));

if ~isempty(missingFunctions)
    error([ ...
        'Required MATLAB functions not found:\n%s\n\n' ...
        'Place them somewhere under src/matlab/.' ...
    ], strjoin(missingFunctions, newline));
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for tinv and finv.' ...
    ]);
end

%% Check directories and support files

if ~isfolder(inputDirControl)
    error('Control input directory not found:\n%s', inputDirControl);
end

if ~isfolder(inputDirConditioning)
    error( ...
        'Conditioning input directory not found:\n%s', ...
        inputDirConditioning ...
    );
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

uiTemplateFile = fullfile(nbsInputDir, 'UI.mat');
cogFile = fullfile(nbsInputDir, 'COG.txt');
% nodeLabelFile = fullfile(nbsInputDir, 'nodeLabels.txt');

requiredSupportFiles = {
    uiTemplateFile
    cogFile
    colormapFile
};

missingSupportFiles = requiredSupportFiles( ...
    ~cellfun(@isfile, requiredSupportFiles) ...
);

if ~isempty(missingSupportFiles)
    error([ ...
        'Required NBS/support files are missing:\n\n%s' ...
    ], strjoin(missingSupportFiles, newline));
end

%% Load custom colormap

colormapData = load(colormapFile);

if ~isfield(colormapData, 'myColormap')
    error( ...
        'Variable "myColormap" is missing from:\n%s', ...
        colormapFile ...
    );
end

myColormap = colormapData.myColormap;

%% Load ROI names

roiDataFiles = dir(fullfile(inputDirControl, 'roidata*.mat'));

if isempty(roiDataFiles)
    error('No roidata*.mat file found in:\n%s', inputDirControl);
end

[~, roiOrder] = sort({roiDataFiles.name});
roiDataFiles = roiDataFiles(roiOrder);

if numel(roiDataFiles) > 1
    warning( ...
        'Multiple roidata files found. Using:\n%s', ...
        roiDataFiles(1).name ...
    );
end

roiDataFile = fullfile( ...
    roiDataFiles(1).folder, ...
    roiDataFiles(1).name ...
);

roiData = load(roiDataFile);

if ~isfield(roiData, 'subj') || ...
        ~isfield(roiData.subj(1), 'roi') || ...
        ~isfield(roiData.subj(1).roi, 'name')
    error('Could not read ROI names from:\n%s', roiDataFile);
end

roiNamesUnsorted = {roiData.subj(1).roi.name};

if max(sorting) > numel(roiNamesUnsorted)
    error([ ...
        'Sorting vector requires at least %d ROIs, but only %d found.' ...
    ], ...
        max(sorting), ...
        numel(roiNamesUnsorted) ...
    );
end

roiNames = roiNamesUnsorted(sorting);
numberOfROIs = numel(roiNames);

%% Define cormat filenames

controlPreFileName = sprintf( ...
    'cormat_%s_%s%s.mat', ...
    controlSuffix, ...
    analysisName, ...
    preRange ...
);

controlTestFileName = sprintf( ...
    'cormat_%s_%s%s.mat', ...
    controlSuffix, ...
    analysisName, ...
    testRange ...
);

conditioningPreFileName = sprintf( ...
    'cormat_%s_%s%s.mat', ...
    conditioningSuffix, ...
    analysisName, ...
    preRange ...
);

conditioningTestFileName = sprintf( ...
    'cormat_%s_%s%s.mat', ...
    conditioningSuffix, ...
    analysisName, ...
    testRange ...
);

controlPreFile = fullfile( ...
    inputDirControl, ...
    controlPreFileName ...
);

controlTestFile = fullfile( ...
    inputDirControl, ...
    controlTestFileName ...
);

conditioningPreFile = fullfile( ...
    inputDirConditioning, ...
    conditioningPreFileName ...
);

conditioningTestFile = fullfile( ...
    inputDirConditioning, ...
    conditioningTestFileName ...
);

requiredCormatFiles = {
    controlPreFile
    controlTestFile
    conditioningPreFile
    conditioningTestFile
};

missingCormatFiles = requiredCormatFiles( ...
    ~cellfun(@isfile, requiredCormatFiles) ...
);

if ~isempty(missingCormatFiles)
    error([ ...
        'Required cormat files are missing:\n\n%s' ...
    ], strjoin(missingCormatFiles, newline));
end

%% Load cormats

controlPreData = load(controlPreFile);
controlTestData = load(controlTestFile);

conditioningPreData = load(conditioningPreFile);
conditioningTestData = load(conditioningTestFile);

loadedStructures = {
    controlPreData
    controlTestData
    conditioningPreData
    conditioningTestData
};

loadedNames = {
    controlPreFile
    controlTestFile
    conditioningPreFile
    conditioningTestFile
};

for fileIndex = 1:numel(loadedStructures)

    if ~isfield(loadedStructures{fileIndex}, 'cormat')
        error( ...
            'Variable "cormat" missing from:\n%s', ...
            loadedNames{fileIndex} ...
        );
    end
end

cormatPreControl = controlPreData.cormat;
cormatTestControl = controlTestData.cormat;

cormatPreConditioning = conditioningPreData.cormat;
cormatTestConditioning = conditioningTestData.cormat;

%% Validate subject counts

nControl = numel(cormatPreControl);
nConditioning = numel(cormatPreConditioning);

if nControl ~= numel(cormatTestControl)
    error('Control PRE and TEST subject counts differ.');
end

if nConditioning ~= numel(cormatTestConditioning)
    error('Conditioning PRE and TEST subject counts differ.');
end

if nControl == 0 || nConditioning == 0
    error('One or both cohorts contain no subjects.');
end

%% Calculate TEST - PRE change matrices

cormatDiffControl = cell(1, nControl);
cormatDiffConditioning = cell(1, nConditioning);

for subjectIndex = 1:nControl

    preMatrix = cormatPreControl{subjectIndex};
    testMatrix = cormatTestControl{subjectIndex};

    validateCormatMatrix( ...
        preMatrix, ...
        sorting, ...
        'control PRE', ...
        subjectIndex ...
    );

    validateCormatMatrix( ...
        testMatrix, ...
        sorting, ...
        'control TEST', ...
        subjectIndex ...
    );

    differenceMatrix = testMatrix - preMatrix;

    cormatDiffControl{subjectIndex} = ...
        differenceMatrix(sorting, sorting);
end

for subjectIndex = 1:nConditioning

    preMatrix = cormatPreConditioning{subjectIndex};
    testMatrix = cormatTestConditioning{subjectIndex};

    validateCormatMatrix( ...
        preMatrix, ...
        sorting, ...
        'conditioning PRE', ...
        subjectIndex ...
    );

    validateCormatMatrix( ...
        testMatrix, ...
        sorting, ...
        'conditioning TEST', ...
        subjectIndex ...
    );

    differenceMatrix = testMatrix - preMatrix;

    cormatDiffConditioning{subjectIndex} = ...
        differenceMatrix(sorting, sorting);
end

%% NBS input matrix

allDifferenceMatrices = [ ...
    cormatDiffControl, ...
    cormatDiffConditioning ...
];

Mat = cat(3, allDifferenceMatrices{:});

matFile = fullfile( ...
    outputDir, ...
    'Figure_3B_TPnoPuff_NBS_InputMatrices_TESTminusPRE.mat' ...
);

save(matFile, 'Mat');

%% GLM design matrix

GLM_design = [ ...
    ones(nControl, 1), zeros(nControl, 1); ...
    zeros(nConditioning, 1), ones(nConditioning, 1) ...
];

designFile = fullfile( ...
    outputDir, ...
    'Figure_3B_TPnoPuff_NBS_Design.txt' ...
);

writematrix( ...
    GLM_design, ...
    designFile, ...
    'Delimiter', ...
    'tab' ...
);

%% Primary NBS thresholds

degreesOfFreedom = ...
    size(GLM_design, 1) - size(GLM_design, 2);

thr_t = tinv( ...
    thresholdProbability, ...
    degreesOfFreedom ...
);

thr_F = finv( ...
    thresholdProbability, ...
    1, ...
    degreesOfFreedom ...
);

%% Edge-wise between-cohort statistics

% Original orientation:
% CONTROL versus CONDITIONING.
[ ...
    T, ...
    p, ...
    p2, ...
    fdrMatrix, ...
    meanValue, ...
    standardDeviation ...
] = lei_ttest2( ...
    cormatDiffControl, ...
    cormatDiffConditioning, ...
    fdrThreshold ...
);

%% Prepare NBS UI

uiData = load(uiTemplateFile);

if ~isfield(uiData, 'UI')
    error('UI.mat does not contain variable "UI".');
end

UI = uiData.UI;

UI.matrices.ui = matFile;
UI.design.ui = designFile;
UI.node_label.ui = '';
UI.exchange.ui = '';

% Retained from original workflow
COG = load(cogFile); %#ok<NASGU>

contrasts = {
    '[1 -1]'
    '[-1 1]'
    '[1 1]'
};

tstat = T;

resNBS = acl_NBS_intercept( ...
    UI, ...
    tstat, ...
    thr_t, ...
    thr_F, ...
    inputType, ...
    contrasts ...
);

%% Extract NBS component

[NBSmat, nbsContrastUsed] = extractNBSMatrix( ...
    resNBS, ...
    numberOfROIs ...
);

%% Plot T-statistic matrix

displayData = tril(T, -1);

figureTitle = sprintf( ...
    'Figure 3B: %s TEST-PRE, control vs conditioning', ...
    analysisName ...
);

figMatrix = figure( ...
    'Name', ...
    figureTitle, ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 900, 780] ...
);

imagesc( ...
    displayData, ...
    'AlphaData', ...
    ~isnan(displayData) ...
);

ax = gca;

axis(ax, 'image');
box(ax, 'off');

ax.CLim = tColorLimits;
ax.TickLabelInterpreter = 'none';
ax.XTick = 1:numberOfROIs;
ax.XTickLabel = roiNames;
ax.YTick = 1:numberOfROIs;
ax.YTickLabel = roiNames;
ax.FontSize = 6;

colormap(ax, myColormap);

xtickangle(ax, 90);

title( ...
    figureTitle, ...
    'Interpreter', ...
    'none' ...
);

colorbar;
hold on;

%% Mark NBS-significant edges

if any(NBSmat(:))

    for rowIndex = 2:numberOfROIs
        for columnIndex = 1:(rowIndex - 1)

            if NBSmat(rowIndex, columnIndex)

                rectangle( ...
                    'Position', ...
                    [ ...
                        columnIndex - 0.5, ...
                        rowIndex - 0.5, ...
                        1, ...
                        1 ...
                    ], ...
                    'EdgeColor', ...
                    [0.1, 0.1, 0.1], ...
                    'LineWidth', ...
                    1 ...
                );
            end
        end
    end
end

%% Export matrix plot

matrixPdf = fullfile( ...
    outputDir, ...
    'Figure_3B_TPnoPuff_NBS_Control_vs_Conditioning_TESTminusPRE.pdf' ...
);

matrixPng = fullfile( ...
    outputDir, ...
    'Figure_3B_TPnoPuff_NBS_Control_vs_Conditioning_TESTminusPRE.png' ...
);

exportgraphics( ...
    figMatrix, ...
    matrixPdf, ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    figMatrix, ...
    matrixPng, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

%% Save source/statistical matrices

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_SourceData_T_ControlMinusConditioning.csv' ...
    ), ...
    displayData, ...
    roiNames ...
);

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_SourceData_T_ConditioningMinusControl.csv' ...
    ), ...
    displayData .* -1, ...
    roiNames ...
);

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_Statistics_T_full.csv' ...
    ), ...
    T, ...
    roiNames ...
);

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_Statistics_P.csv' ...
    ), ...
    p, ...
    roiNames ...
);

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_Statistics_FDR.csv' ...
    ), ...
    double(fdrMatrix), ...
    roiNames ...
);

writeLabeledMatrix( ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_Statistics_NBSMask.csv' ...
    ), ...
    NBSmat, ...
    roiNames ...
);

%% Plot schemaball

if any(NBSmat(:))

    cmap = flipud(myColormap(100:end, :));

    Cdata = NBSmat .* T;

    finiteValues = Cdata(isfinite(Cdata));

    if isempty(finiteValues)

        RGB = ones(numberOfROIs, numberOfROIs, 3) .* 0.5;

    else

        cmin = min(finiteValues);
        cmax = max(finiteValues);
        numberOfColors = size(cmap, 1);

        if cmax == cmin

            index = ones(size(Cdata));

        else

            index = fix( ...
                (Cdata - cmin) ./ ...
                (cmax - cmin) .* ...
                (numberOfColors - 1) ...
            ) + 1;
        end

        index(~isfinite(index)) = 1;

        index = max( ...
            1, ...
            min(numberOfColors, index) ...
        );

        RGB = ind2rgb(index, cmap);
    end

    figSchemaball = figure( ...
        'Name', ...
        [figureTitle ' schemaball'], ...
        'Visible', ...
        'on', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 900, 780] ...
    );

    schemaball( ...
        roiNames, ...
        Cdata, ...
        10, ...
        tColorLimits, ...
        ones(numberOfROIs, 3) .* 0.5, ...
        RGB ...
        );

    title( ...
        sprintf( ...
            'Figure 3B: %s; %s', ...
            analysisName, ...
            nbsContrastUsed ...
        ), ...
        'Interpreter', ...
        'none' ...
    );

    schemaballPdf = fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_NBS_Schemaball.pdf' ...
    );

    schemaballPng = fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_NBS_Schemaball.png' ...
    );

    exportgraphics( ...
        figSchemaball, ...
        schemaballPdf, ...
        'ContentType', ...
        'vector', ...
        'BackgroundColor', ...
        'white' ...
    );

    exportgraphics( ...
        figSchemaball, ...
        schemaballPng, ...
        'Resolution', ...
        300, ...
        'BackgroundColor', ...
        'white' ...
    );

else

    warning( ...
        'No NBS component returned for %s. Schemaball skipped.', ...
        analysisName ...
    );
end

%% Save complete results

resultFile = fullfile( ...
    outputDir, ...
    'Figure_3B_TPnoPuff_CompleteNBSResults.mat' ...
);

save( ...
    resultFile, ...
    'resNBS', ...
    'NBSmat', ...
    'nbsContrastUsed', ...
    'T', ...
    'p', ...
    'p2', ...
    'fdrMatrix', ...
    'meanValue', ...
    'standardDeviation', ...
    'GLM_design', ...
    'thr_t', ...
    'thr_F', ...
    'thresholdProbability', ...
    'inputType', ...
    'contrasts', ...
    'cormatDiffControl', ...
    'cormatDiffConditioning', ...
    'roiNames', ...
    'sorting', ...
    'nControl', ...
    'nConditioning', ...
    'analysisName' ...
);

%% Save metadata

metadata = table( ...
    string('Figure 3B'), ...
    string(analysisName), ...
    nControl, ...
    nConditioning, ...
    thresholdProbability, ...
    thr_t, ...
    thr_F, ...
    string(nbsContrastUsed), ...
    string(controlPreFileName), ...
    string(controlTestFileName), ...
    string(conditioningPreFileName), ...
    string(conditioningTestFileName), ...
    'VariableNames', {
        'Figure'
        'Analysis'
        'N_Control'
        'N_Conditioning'
        'NBS_PrimaryProbability'
        'T_Threshold'
        'F_Threshold'
        'NBS_ContrastDisplayed'
        'Control_Pre_File'
        'Control_Test_File'
        'Conditioning_Pre_File'
        'Conditioning_Test_File'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'Figure_3B_TPnoPuff_AnalysisMetadata.csv' ...
    ) ...
);

%% Optional source-script documentation

if ~isempty(which('docDataSrc'))

    try
        docDataSrc( ...
            figMatrix, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );
    catch documentationError
        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

fprintf('\nCompleted Figure 3B NBS analysis.\n');
fprintf('Analysis: %s\n', analysisName);
fprintf('Control n = %d; conditioning n = %d\n', ...
    nControl, nConditioning);
fprintf('Outputs saved to:\n%s\n', outputDir);

%% Local functions

function validateCormatMatrix( ...
    matrixData, ...
    sorting, ...
    conditionLabel, ...
    subjectIndex ...
)

    if ~ismatrix(matrixData) || ...
            size(matrixData, 1) ~= size(matrixData, 2)
        error( ...
            '%s matrix for subject %d is not square.', ...
            conditionLabel, ...
            subjectIndex ...
        );
    end

    if size(matrixData, 1) < max(sorting)
        error([ ...
            '%s matrix for subject %d contains fewer ROIs than ' ...
            'required by the sorting vector.' ...
        ], ...
            conditionLabel, ...
            subjectIndex ...
        );
    end
end


function [NBSmat, contrastLabel] = extractNBSMatrix( ...
    resNBS, ...
    numberOfROIs ...
)

    NBSmat = zeros(numberOfROIs);
    contrastLabel = 'no significant NBS component';

    if isfield(resNBS, 'CON_MAT2') && ...
            ~isempty(resNBS.CON_MAT2) && ...
            ~isempty(resNBS.CON_MAT2{1, 1})

        component = full(resNBS.CON_MAT2{1, 1});

        NBSmat = double((component + component') ~= 0);

        contrastLabel = ...
            '[-1 1] conditioning > control';

        return;
    end

    if isfield(resNBS, 'CON_MAT1') && ...
            ~isempty(resNBS.CON_MAT1) && ...
            ~isempty(resNBS.CON_MAT1{1, 1})

        component = full(resNBS.CON_MAT1{1, 1});

        NBSmat = component + component';

        contrastLabel = ...
            '[1 -1] control > conditioning';
    end
end


function writeLabeledMatrix( ...
    filePath, ...
    matrixData, ...
    labels ...
)

    labels = labels(:);
    numberOfLabels = numel(labels);

    if ~isequal( ...
            size(matrixData), ...
            [numberOfLabels, numberOfLabels] ...
        )
        error( ...
            'Matrix dimensions do not match ROI labels.' ...
        );
    end

    outputCell = cell( ...
        numberOfLabels + 1, ...
        numberOfLabels + 1 ...
    );

    outputCell(1, 2:end) = labels';
    outputCell(2:end, 1) = labels;
    outputCell(2:end, 2:end) = num2cell(matrixData);

    writecell(outputCell, filePath);
end
