% panel_B_rank_vHC_BOLD.m
% Jonathan Reinwald
%
% Standalone repository script for Figure 6B.
%
% Figure 6B relates social rank to mean vHC BOLD values extracted from
% the rank-related vHC cluster used in Figure 6A.
%
% Fixed analysis settings from the original script:
%   - explanatory variable: Rank only
%   - beta selection: vHC
%   - threshold: T01
%   - preprocessing: no scrubbing
%   - PRE  = TPnoPuff trials 11-40
%   - TEST = TPnoPuff trials 81-120
%
% The script plots:
%   1. PRE vs TEST mean BOLD
%   2. Rank vs PRE and TEST mean BOLD
%   3. Rank vs TEST-PRE BOLD change
%
% Pearson and Spearman correlations are reported.
% PRE vs TEST is additionally assessed with a paired t-test and
% 10,000-permutation paired test.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_6/
% │   └── panel_B_rank_vHC_BOLD.m
% │
% ├── data/processed/NoSeMaze/
% │   ├── 01_General_Overview.xlsx
% │   ├── AnimalNumb_to_ID.mat
% │   └── tubetest/
% │       ├── NoSeMaze_1/
% │       │   ├── DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       │   └── DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       └── NoSeMaze_2/
% │           └── DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │
% ├── data/processed/fMRI/Figure_6/Figure_6B/
% │   └── mask_positiveCorrRank_T01.mat
% │
% ├── src/matlab/
% │   ├── notBoxPlot_modified.m
% │   ├── permutest.m
% │   ├── sigstar.m
% │   └── docDataSrc.m              (optional)
% │
% └── results/main/Figure_6/Figure_6B/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/main/Figure_6/panel_B_rank_vHC_BOLD.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

noSeMazeDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze' ...
);

noSeMaze1Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_1' ...
);

noSeMaze2Dir = fullfile( ...
    noSeMazeDir, ...
    'tubetest', ...
    'NoSeMaze_2' ...
);

inputDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_6', ...
    'Figure_6B' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_6', ...
    'Figure_6B' ...
);

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Add MATLAB helpers

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

requiredFunctions = {
    'notBoxPlot_modified'
    'permutest'
    'sigstar'
};

missingFunctions = requiredFunctions( ...
    cellfun(@(x) isempty(which(x)), requiredFunctions) ...
);

if ~isempty(missingFunctions)
    error([ ...
        'Required MATLAB helper functions not found:\n%s\n\n' ...
        'Place them somewhere under src/matlab/.' ...
    ], ...
        strjoin(missingFunctions, newline) ...
    );
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for corr, ttest and lsline.' ...
    ]);
end

%% Fixed analysis settings

numberOfPermutations = 10000;
randomSeed = 1234;

betaSelection = 'vHC';
thresholdSelection = 'T01';
scrubbedVersion = 'no_scrubbing';

preName = 'TPnoPuff11to40';
testName = 'TPnoPuff81to120';

%% Input files

generalOverviewFile = fullfile( ...
    noSeMazeDir, ...
    '01_General_Overview.xlsx' ...
);

animalMapFile = fullfile( ...
    noSeMazeDir, ...
    'AnimalNumb_to_ID.mat' ...
);

am1EarlyFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day3to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am1LateFile = fullfile( ...
    noSeMaze1Dir, ...
    'DS_info_AM1_day8to21_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

am2File = fullfile( ...
    noSeMaze2Dir, ...
    'DS_info_AM2_day1to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

betaFile = fullfile( ...
    inputDir, ...
    'mask_positiveCorrRank_T01.mat' ...
);

requiredFiles = {
    generalOverviewFile
    animalMapFile
    am1EarlyFile
    am1LateFile
    am2File
    betaFile
};

missingFiles = requiredFiles(~cellfun(@isfile, requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required input files are missing:\n\n%s', ...
        strjoin(missingFiles, newline) ...
    );
end

%% Load overview

T = readtable( ...
    generalOverviewFile, ...
    'Sheet', ...
    9, ...
    'ReadVariableNames', ...
    true, ...
    'VariableNamingRule', ...
    'modify' ...
);

%% Load and prepare hierarchy windows

tmp = load(am1EarlyFile, 'DS_info');
AM1_early = prepareHierarchy(tmp.DS_info);

tmp = load(am1LateFile, 'DS_info');
AM1_late = prepareHierarchy(tmp.DS_info);

tmp = load(am2File, 'DS_info');
AM2 = prepareHierarchy(tmp.DS_info);

%% Build Rank vector for all MRI animals

animalID = strings(0,1);
animalNumberOverview = [];
rankValue = [];

for rowIndex = 1:height(T)

    autoValue = T.Autonomouse(rowIndex);

    if ~ismember(autoValue, [1, 2])
        continue;
    end

    currentID = normalizeAnimalID(T.AnimalIDCombined(rowIndex));

    if autoValue == 1

        daysValue = normalizeText(T.DaysToConsider(rowIndex));

        if contains(daysValue, '16')
            hierarchy = AM1_early;

        elseif contains(daysValue, '21')
            hierarchy = AM1_late;

        else
            error( ...
                'Could not assign hierarchy window for AM1 animal %s.', ...
                currentID ...
            );
        end

    else
        hierarchy = AM2;
    end

    hierarchyIDs = upper(strtrim(string(hierarchy.ID(:))));
    hierarchyIndex = find(hierarchyIDs == currentID);

    if numel(hierarchyIndex) ~= 1
        error( ...
            'Animal ID %s could not be matched uniquely in hierarchy data.', ...
            currentID ...
        );
    end

    animalID(end+1,1) = currentID; %#ok<SAGROW>
    animalNumberOverview(end+1,1) = ...
        getNumericScalar(T.AnimalNumber(rowIndex)); %#ok<SAGROW>
    rankValue(end+1,1) = ...
        hierarchy.Rank(hierarchyIndex); %#ok<SAGROW>
end

%% Map IDs to MRI AnimalNumb and sort exactly as original analysis

mapLoaded = load(animalMapFile);

if ~isfield(mapLoaded, 'AnimalNumb_to_ID')
    error( ...
        'Variable "AnimalNumb_to_ID" missing from:\n%s', ...
        animalMapFile ...
    );
end

AnimalNumb_to_ID = mapLoaded.AnimalNumb_to_ID;

mapIDs = strings(numel(AnimalNumb_to_ID), 1);

for mapIndex = 1:numel(AnimalNumb_to_ID)
    mapIDs(mapIndex) = normalizeAnimalID( ...
        AnimalNumb_to_ID(mapIndex).ID ...
    );
end

animalNumberMapped = nan(numel(animalID), 1);

for animalIndex = 1:numel(animalID)

    matches = find(mapIDs == animalID(animalIndex));

    if isempty(matches)
        error( ...
            'Animal ID %s not found in AnimalNumb_to_ID.', ...
            animalID(animalIndex) ...
        );
    end

    mappedNumbers = nan(numel(matches),1);

    for matchIndex = 1:numel(matches)
        mappedNumbers(matchIndex) = getNumericScalar( ...
            AnimalNumb_to_ID(matches(matchIndex)).AnimalNumb ...
        );
    end

    mappedNumbers = unique(mappedNumbers);

    if numel(mappedNumbers) ~= 1
        error( ...
            'Animal ID %s maps to multiple AnimalNumb values.', ...
            animalID(animalIndex) ...
        );
    end

    animalNumberMapped(animalIndex) = mappedNumbers;
end

if ~isequal(animalNumberMapped, animalNumberOverview)
    warning([ ...
        'AnimalNumber from General Overview differs from AnimalNumb_to_ID ' ...
        'for at least one row. The MRI mapping is used for sorting, ' ...
        'matching the original analysis.' ...
    ]);
end

[animalNumberSorted, sortIndex] = sort( ...
    animalNumberMapped, ...
    'ascend' ...
);

animalIDSorted = animalID(sortIndex);
rankInput = rankValue(sortIndex);

%% Load vHC beta values

betaLoaded = load(betaFile);

if ~isfield(betaLoaded, 'res')
    error( ...
        'Variable "res" missing from beta file:\n%s', ...
        betaFile ...
    );
end

res = betaLoaded.res;

if ~isfield(res, 'mean_betaNeg') || ~isfield(res, 'mean_betaPos')
    error([ ...
        'Expected fields res.mean_betaNeg and res.mean_betaPos ' ...
        'are missing from:\n%s' ...
    ], ...
        betaFile ...
    );
end

% Original analysis:
%   PRE  = mean_betaNeg
%   TEST = mean_betaPos

betaPre = [res.mean_betaNeg]';
betaTest = [res.mean_betaPos]';
betaDiff = betaTest - betaPre;

%% Input checks

nAnimals = numel(rankInput);

if any([ ...
        numel(betaPre), ...
        numel(betaTest), ...
        numel(betaDiff) ...
    ] ~= nAnimals)

    error([ ...
        'Sample-size mismatch: Rank has n=%d, while beta vectors have ' ...
        'n=%d/%d/%d.' ...
    ], ...
        nAnimals, ...
        numel(betaPre), ...
        numel(betaTest), ...
        numel(betaDiff) ...
    );
end

fprintf('\nFigure 6B input check\n');
fprintf('Animals: %d\n', nAnimals);
fprintf('Behavior: Rank\n');
fprintf('ROI: %s\n', betaSelection);
fprintf('Threshold: %s\n', thresholdSelection);
fprintf('Version: %s\n\n', scrubbedVersion);

%% Correlations

[rPrePearson, pPrePearson] = corr( ...
    rankInput, ...
    betaPre, ...
    'Type', ...
    'Pearson', ...
    'Rows', ...
    'complete' ...
);

[rPreSpearman, pPreSpearman] = corr( ...
    rankInput, ...
    betaPre, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete' ...
);

[rTestPearson, pTestPearson] = corr( ...
    rankInput, ...
    betaTest, ...
    'Type', ...
    'Pearson', ...
    'Rows', ...
    'complete' ...
);

[rTestSpearman, pTestSpearman] = corr( ...
    rankInput, ...
    betaTest, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete' ...
);

[rDiffPearson, pDiffPearson] = corr( ...
    rankInput, ...
    betaDiff, ...
    'Type', ...
    'Pearson', ...
    'Rows', ...
    'complete' ...
);

[rDiffSpearman, pDiffSpearman] = corr( ...
    rankInput, ...
    betaDiff, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete' ...
);

%% PRE vs TEST statistics

[hPaired, pPaired, ~, pairedStats] = ttest( ...
    betaPre, ...
    betaTest ...
);

rng(randomSeed, 'twister');

[ ...
    clusters, ...
    permutationPValues, ...
    tSums, ...
    permutationDistribution ...
] = permutest( ...
    betaPre', ...
    betaTest', ...
    true, ...
    0.05, ...
    numberOfPermutations, ...
    true ...
);

permutationP = getScalarPermutationP(permutationPValues);

%% Figure

fig = figure( ...
    'Name', ...
    'Figure 6B: Rank vs vHC BOLD', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 80, 1050, 720] ...
);

%% 1. PRE vs TEST

subplot(2,3,1);

bb = notBoxPlot_modified([betaPre, betaTest]);

for index = 1:numel(bb)
    bb(index).data.MarkerSize = 6;
    bb(index).data.MarkerEdgeColor = 'none';
    bb(index).semPtch.EdgeColor = 'none';
    bb(index).sdPtch.EdgeColor = 'none';
end

% PRE
bb(1).data.MarkerFaceColor = [204/255, 51/255, 204/255];
bb(1).mu.Color = [204/255, 51/255, 204/255];
bb(1).semPtch.FaceColor = [255/255, 102/255, 204/255];
bb(1).sdPtch.FaceColor = [255/255, 204/255, 204/255];

% TEST
bb(2).data.MarkerFaceColor = [0, 160/255, 227/255];
bb(2).mu.Color = [0, 160/255, 227/255];
bb(2).semPtch.FaceColor = [75/255, 207/255, 227/255];
bb(2).sdPtch.FaceColor = [150/255, 255/255, 227/255];

ax1 = gca;
box(ax1, 'off');

ylabel(ax1, 'mean BOLD');
ax1.XTick = [1,2];
ax1.XTickLabel = {'Pre','Test'};
ax1.XLim = [0.5,2.5];
ax1.FontSize = 10;
ax1.FontWeight = 'bold';
ax1.LineWidth = 1.5;

if isfinite(permutationP) && permutationP < 0.05
    sigstar({[1,2]}, permutationP, 0, 10);
end

text( ...
    ax1, ...
    ax1.XLim(1) + 0.10*diff(ax1.XLim), ...
    ax1.YLim(1) + 0.20*diff(ax1.YLim), ...
    sprintf('p_{perm} = %.4g', permutationP), ...
    'Interpreter', ...
    'tex' ...
);

%% 2. Rank vs PRE and TEST

subplot(2,3,[2,3]);

scPre = scatter(rankInput, betaPre, 40, 'filled');
hold on;
scTest = scatter(rankInput, betaTest, 40, 'filled');

scPre.MarkerEdgeColor = 'none';
scTest.MarkerEdgeColor = 'none';

scPre.MarkerFaceColor = [204/255, 51/255, 204/255];
scTest.MarkerFaceColor = [0, 160/255, 227/255];

ax2 = gca;
box(ax2, 'off');
axis(ax2, 'square');

xlabel(ax2, 'Rank');
ylabel(ax2, 'mean BOLD');

ax2.XLim = [1,12];
ax2.XTick = 1:12;

ax2.FontSize = 10;
ax2.FontWeight = 'bold';
ax2.LineWidth = 1.5;

lineHandles = lsline;

if numel(lineHandles) >= 2
    lineHandles(1).Color = [0, 160/255, 227/255];
    lineHandles(1).LineWidth = 1.5;
    lineHandles(2).Color = [204/255, 51/255, 204/255];
    lineHandles(2).LineWidth = 1.5;
end

addPreTestCorrelationText( ...
    ax2, ...
    rPrePearson, ...
    pPrePearson, ...
    rPreSpearman, ...
    pPreSpearman, ...
    rTestPearson, ...
    pTestPearson, ...
    rTestSpearman, ...
    pTestSpearman ...
);

%% 3. Rank vs TEST-PRE change

subplot(2,3,[5,6]);

diffColor = ...
    ([204/255, 51/255, 204/255] + [0, 160/255, 227/255]) ./ 2;

scDiff = scatter(rankInput, betaDiff, 40, 'filled');
scDiff.MarkerEdgeColor = 'none';
scDiff.MarkerFaceColor = diffColor;

ax3 = gca;
box(ax3, 'off');
axis(ax3, 'square');

xlabel(ax3, 'Rank');
ylabel(ax3, {'mean BOLD','(Test - Pre)'});

ax3.XLim = [1,12];
ax3.XTick = 1:12;

ax3.FontSize = 10;
ax3.FontWeight = 'bold';
ax3.LineWidth = 1.5;

diffLine = lsline;
diffLine.Color = diffColor;
diffLine.LineWidth = 1.5;

addDifferenceCorrelationText( ...
    ax3, ...
    rDiffPearson, ...
    pDiffPearson, ...
    rDiffSpearman, ...
    pDiffSpearman, ...
    diffColor ...
);

sgtitle( ...
    sprintf( ...
        'Figure 6B | Rank | %s | %s', ...
        betaSelection, ...
        thresholdSelection ...
    ), ...
    'Interpreter', ...
    'none' ...
);

%% Source data

sourceData = table( ...
    animalIDSorted, ...
    animalNumberSorted, ...
    rankInput, ...
    betaPre, ...
    betaTest, ...
    betaDiff, ...
    'VariableNames', {
        'AnimalID'
        'AnimalNumber'
        'Rank'
        'BOLD_Pre'
        'BOLD_Test'
        'BOLD_TestMinusPre'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_6B_Rank_vHC_BOLD.csv' ...
    ) ...
);

%% Statistics

statisticsTable = table( ...
    [
        "Rank_vs_PRE_Pearson"
        "Rank_vs_PRE_Spearman"
        "Rank_vs_TEST_Pearson"
        "Rank_vs_TEST_Spearman"
        "Rank_vs_Delta_Pearson"
        "Rank_vs_Delta_Spearman"
        "PRE_vs_TEST_PairedTTest"
        "PRE_vs_TEST_Permutation"
    ], ...
    [
        rPrePearson
        rPreSpearman
        rTestPearson
        rTestSpearman
        rDiffPearson
        rDiffSpearman
        pairedStats.tstat
        NaN
    ], ...
    [
        pPrePearson
        pPreSpearman
        pTestPearson
        pTestSpearman
        pDiffPearson
        pDiffSpearman
        pPaired
        permutationP
    ], ...
    'VariableNames', {
        'Statistic'
        'Estimate'
        'P'
    } ...
);

writetable( ...
    statisticsTable, ...
    fullfile( ...
        outputDir, ...
        'Statistics_Figure_6B_Rank_vHC_BOLD.csv' ...
    ) ...
);

%% Save complete result

result = struct;

result.AnimalID = animalIDSorted;
result.AnimalNumber = animalNumberSorted;
result.Rank = rankInput;

result.betaPre = betaPre;
result.betaTest = betaTest;
result.betaDiff = betaDiff;

result.correlation.prePearson = [rPrePearson, pPrePearson];
result.correlation.preSpearman = [rPreSpearman, pPreSpearman];
result.correlation.testPearson = [rTestPearson, pTestPearson];
result.correlation.testSpearman = [rTestSpearman, pTestSpearman];
result.correlation.diffPearson = [rDiffPearson, pDiffPearson];
result.correlation.diffSpearman = [rDiffSpearman, pDiffSpearman];

result.pairedTTest.h = hPaired;
result.pairedTTest.p = pPaired;
result.pairedTTest.stats = pairedStats;

result.permutation.clusters = clusters;
result.permutation.pValues = permutationPValues;
result.permutation.p = permutationP;
result.permutation.tSums = tSums;
result.permutation.distribution = permutationDistribution;
result.permutation.numberOfPermutations = numberOfPermutations;
result.permutation.randomSeed = randomSeed;

result.betaSelection = betaSelection;
result.thresholdSelection = thresholdSelection;
result.scrubbedVersion = scrubbedVersion;

save( ...
    fullfile( ...
        outputDir, ...
        'Results_Figure_6B_Rank_vHC_BOLD.mat' ...
    ), ...
    'result' ...
);

%% Metadata

metadata = table( ...
    string(betaSelection), ...
    string(thresholdSelection), ...
    string(scrubbedVersion), ...
    nAnimals, ...
    numberOfPermutations, ...
    randomSeed, ...
    string(betaFile), ...
    string(generalOverviewFile), ...
    string(animalMapFile), ...
    'VariableNames', {
        'BetaSelection'
        'ThresholdSelection'
        'Preprocessing'
        'N'
        'NumberOfPermutations'
        'RandomSeed'
        'BetaFile'
        'GeneralOverviewFile'
        'AnimalMapFile'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'AnalysisMetadata_Figure_6B.csv' ...
    ) ...
);

%% Optional provenance

if ~isempty(which('docDataSrc'))
    try
        docDataSrc(fig, outputDir, scriptFile, true);
    catch documentationError
        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_6B_Rank_vHC_BOLD.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_6B_Rank_vHC_BOLD.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

fprintf('Figure 6B completed.\n');
fprintf('Results saved to:\n%s\n', outputDir);

%% ========================================================================
% Local functions
%% ========================================================================

function hierarchy = prepareHierarchy(DS_info)

    hierarchy = DS_info;

    [~, sortedIndex] = sort( ...
        [hierarchy.DS], ...
        'descend' ...
    );

    [~, rank] = sort(sortedIndex);

    hierarchy.Rank = rank;
end


function value = normalizeAnimalID(rawValue)

    while iscell(rawValue)
        if numel(rawValue) ~= 1
            error('Animal ID cell contains more than one element.');
        end
        rawValue = rawValue{1};
    end

    value = upper(strtrim(string(rawValue)));

    if numel(value) ~= 1 || ismissing(value) || strlength(value) == 0
        error('Could not convert an Animal ID to a valid string.');
    end
end


function value = normalizeText(rawValue)

    while iscell(rawValue)
        if numel(rawValue) ~= 1
            error('Text cell contains more than one element.');
        end
        rawValue = rawValue{1};
    end

    value = strtrim(string(rawValue));
end


function value = getNumericScalar(rawValue)

    while iscell(rawValue)
        if numel(rawValue) ~= 1
            error('Numeric cell contains more than one element.');
        end
        rawValue = rawValue{1};
    end

    if isnumeric(rawValue)
        value = double(rawValue);
    else
        value = str2double(string(rawValue));
    end

    if numel(value) ~= 1 || ~isfinite(value)
        error('Could not convert value to one finite numeric scalar.');
    end
end


function p = getScalarPermutationP(pValues)

    if isempty(pValues)
        p = NaN;
        return;
    end

    pValues = pValues(:);

    if numel(pValues) > 1
        warning([ ...
            'permutest returned %d p-values. ' ...
            'Using the smallest p-value for this scalar comparison.' ...
        ], numel(pValues));
    end

    p = min(pValues);
end


function addPreTestCorrelationText( ...
    ax, ...
    rPrePearson, ...
    pPrePearson, ...
    rPreSpearman, ...
    pPreSpearman, ...
    rTestPearson, ...
    pTestPearson, ...
    rTestSpearman, ...
    pTestSpearman ...
)

    preColor = [204/255, 51/255, 204/255];
    testColor = [0, 160/255, 227/255];

    xLeft = ax.XLim(1) + 0.10*diff(ax.XLim);
    xRight = ax.XLim(1) + 0.55*diff(ax.XLim);

    y1 = ax.YLim(1) + 0.10*diff(ax.YLim);
    y2 = ax.YLim(1) + 0.20*diff(ax.YLim);
    y3 = ax.YLim(1) + 0.90*diff(ax.YLim);
    y4 = ax.YLim(1) + 0.80*diff(ax.YLim);

    text(ax, xLeft, y1, sprintf('p = %.3g', pPrePearson), ...
        'Color', preColor, 'FontWeight', 'bold');
    text(ax, xRight, y1, sprintf('r = %.3f', rPrePearson), ...
        'Color', preColor, 'FontWeight', 'bold');

    text(ax, xLeft, y2, sprintf('p = %.3g', pTestPearson), ...
        'Color', testColor, 'FontWeight', 'bold');
    text(ax, xRight, y2, sprintf('r = %.3f', rTestPearson), ...
        'Color', testColor, 'FontWeight', 'bold');

    text(ax, xLeft, y3, sprintf('p_s = %.3g', pPreSpearman), ...
        'Color', preColor, 'FontWeight', 'bold', 'Interpreter', 'tex');
    text(ax, xRight, y3, sprintf('\rho_s = %.3f', rPreSpearman), ...
        'Color', preColor, 'FontWeight', 'bold', 'Interpreter', 'tex');

    text(ax, xLeft, y4, sprintf('p_s = %.3g', pTestSpearman), ...
        'Color', testColor, 'FontWeight', 'bold', 'Interpreter', 'tex');
    text(ax, xRight, y4, sprintf('\rho_s = %.3f', rTestSpearman), ...
        'Color', testColor, 'FontWeight', 'bold', 'Interpreter', 'tex');
end


function addDifferenceCorrelationText( ...
    ax, ...
    rPearson, ...
    pPearson, ...
    rSpearman, ...
    pSpearman, ...
    plotColor ...
)

    xLeft = ax.XLim(1) + 0.10*diff(ax.XLim);
    xRight = ax.XLim(1) + 0.55*diff(ax.XLim);

    y1 = ax.YLim(1) + 0.10*diff(ax.YLim);
    y2 = ax.YLim(1) + 0.20*diff(ax.YLim);

    text(ax, xLeft, y1, sprintf('p = %.3g', pPearson), ...
        'Color', plotColor, 'FontWeight', 'bold');

    text(ax, xRight, y1, sprintf('r = %.3f', rPearson), ...
        'Color', plotColor, 'FontWeight', 'bold');

    text(ax, xLeft, y2, sprintf('p_s = %.3g', pSpearman), ...
        'Color', plotColor, 'FontWeight', 'bold', 'Interpreter', 'tex');

    text(ax, xRight, y2, sprintf('\rho_s = %.3f', rSpearman), ...
        'Color', plotColor, 'FontWeight', 'bold', 'Interpreter', 'tex');
end
