function cfg = glm_reappraisal_config(repoRoot)
% GLM_REAPPRAISAL_CONFIG Primary reappraisal-cohort voxelwise GLM.
%
% Primary manuscript settings confirmed:
%   - regressor model: v22
%   - voxelwise smoothing branch: 0.6 mm (s6)
%   - nuisance model: v1 = 14 covariates
%
% The 0.4-mm (s4) branch was a robustness analysis and is NOT the primary
% configuration in this file.

arguments
    repoRoot (1,:) char
end

cfg = struct();

%% Subjects

cfg.subjectNumbers = 1:24;
cfg.subjectIDs = arrayfun( ...
    @(n) sprintf('ZI_M%02d', n), ...
    cfg.subjectNumbers, ...
    'UniformOutput', false ...
);

%% Large preprocessed fMRI input
%
% Preferred repository-local location:
%   data/processed/fMRI/preprocessing/reappraisal/
%
% Alternatively set:
%   NOSEMAZE_REAPPRAISAL_FMRI_PROCESSED_ROOT

repoFmriRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'preprocessing', ...
    'reappraisal' ...
);

externalFmriRoot = getenv('NOSEMAZE_REAPPRAISAL_FMRI_PROCESSED_ROOT');

if isfolder(repoFmriRoot)
    cfg.preprocessedFmriRoot = repoFmriRoot;
elseif ~isempty(externalFmriRoot) && isfolder(externalFmriRoot)
    cfg.preprocessedFmriRoot = externalFmriRoot;
else
    cfg.preprocessedFmriRoot = repoFmriRoot;
end

%% Processed task timing

cfg.protocolDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'RHD', ...
    'reappraisal', ...
    'processed_protocol_files' ...
);

%% Derived GLM inputs

cfg.glmDataRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'glm', ...
    'reappraisal' ...
);

cfg.regressorsDir = fullfile(cfg.glmDataRoot, 'regressors');
cfg.covariatesDir = fullfile(cfg.glmDataRoot, 'covariates');
cfg.groupCovariatesDir = fullfile(cfg.glmDataRoot, 'group_covariates');

%% Primary regressor model

cfg.regressorModel = 'v22';
cfg.regressorGenerationAvailable = true;
cfg.odorDelay = 0.7;  % seconds; historical mini-PID estimate

%% Nuisance model: 14 covariates

cfg.covariateModel = 'v1';
cfg.nuisanceRegressorFile = 'regressors_despiked_motcsf_der.txt';
cfg.scaleTranslationsBy10 = true;
cfg.includeFD = false;

%% Primary voxelwise EPI branch: 0.6-mm smoothing

cfg.smoothingFWHMmm = 0.6;

cfg.epiPrefix = ...
    'wave_10cons_med1000_msk_s6_wrst_a1_u_despiked_del5_';

cfg.epiSuffix = '_c1_c2t_wds';

%% GLM parameters

cfg.TR = 1.2;
cfg.nSlices = 22;
cfg.refSlice = 1;
cfg.fmri_t = 22;
cfg.fmri_t0 = 1;
cfg.maskThreshold = 0;
cfg.orth = 1;
cfg.DerDisp = [0 0];

%% Mouse HRF

cfg.hrfTCbased = 'longTC';
cfg.hrfEstimateLength = 'from2sHRF-GLM';
cfg.hrfOnset = 'withoutOnset';

cfg.hrfInfoPath = sprintf( ...
    '%s_%s', ...
    cfg.hrfOnset, ...
    cfg.hrfEstimateLength ...
);

cfg.hrfDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab', ...
    'preprocessing', ...
    'toolboxes', ...
    'spm12_animal', ...
    cfg.hrfTCbased, ...
    ['hrf_' cfg.hrfInfoPath] ...
);

%% Explicit mask

cfg.explicitMask = fullfile( ...
    repoRoot, ...
    'data', ...
    'reference', ...
    'atlases', ...
    'AllenBrain_2021_v2', ...
    'mask_noCB_noBS_polished.nii' ...
);

%% Results

cfg.analysisLabel = sprintf( ...
    'reappraisal_%s_cov%s_s6_primary', ...
    cfg.regressorModel, ...
    cfg.covariateModel ...
);

cfg.resultsDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'analysis', ...
    'fMRI', ...
    'glm', ...
    'reappraisal', ...
    cfg.analysisLabel ...
);

cfg.firstLevelDir = fullfile(cfg.resultsDir, 'firstlevel');
cfg.secondLevelDir = fullfile(cfg.resultsDir, 'secondlevel');
cfg.socialHierarchyDir = fullfile( ...
    cfg.resultsDir, ...
    'secondlevel_social_hierarchy' ...
);

cfg.graphCovariatesDir = fullfile( ...
    cfg.resultsDir, ...
    'secondlevel_graph_covariates' ...
);

canonicalGraphAucDir = fullfile( ...
    repoRoot, ...
    'data','processed','fMRI', ...
    'graph_analysis','reappraisal','v11', ...
    'max_connected','auc' ...
);

externalGraphAucDir = getenv('NOSEMAZE_REAPPRAISAL_GRAPH_AUC_ROOT');

if ~isempty(externalGraphAucDir) && isfolder(externalGraphAucDir)
    cfg.graphAucDir = externalGraphAucDir;
else
    cfg.graphAucDir = canonicalGraphAucDir;
end

%% NoSeMaze inputs for social-hierarchy second-level models

cfg.generalOverviewFile = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze', ...
    '01_General_Overview.xlsx' ...
);

cfg.noSeMaze1Dir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze', ...
    'tubetest', ...
    'NoSeMaze_1' ...
);

cfg.noSeMaze2Dir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'NoSeMaze', ...
    'tubetest', ...
    'NoSeMaze_2' ...
);

end
