% panel_B_OB_AON_timecourses_control.m
% Jonathan Reinwald
%
% BOLD time-course analysis for Supplementary Figure S2B.
%
% No-puff control cohort only.
%
% ROIs:
%   1. Olfactory bulb (OB)
%   2. Anterior olfactory nucleus (AON)
%
% Displayed blocks:
%   PRE  = trials 11-40
%   TEST = trials 81-120
%
% For each ROI, trials are averaged within mouse first. The figure then
% shows the group mean +/- SEM across mice.
%
% The high-resolution linearly interpolated time course is used directly:
%
%   tc_matrsess_all_highres_lin
%
% No pairing-trial reordering or puff mask is required because only PRE and
% TEST are displayed.
%
% Input:
%
% data/processed/fMRI/Figure_S2/Figure_S2B/control/
% ├── OB/
% │   └── tc_matrsess_all_BINS6_TRsbefore2.mat
% └── AON/
%     └── tc_matrsess_all_BINS6_TRsbefore2.mat
%
% Required variables:
%   tc_matrsess_all_highres_lin
%   tc_matrsess_info.highres
%
% Output:
%   results/supplement/Figure_S2/Figure_S2B/control/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the script location. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repo/figures/supplement/Figure_S2/panel_B_OB_AON_timecourses_control.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

inputBaseDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_S2', ...
    'Figure_S2B', ...
    'control' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'supplement', ...
    'Figure_S2', ...
    'Figure_S2B', ...
    'control' ...
);

if ~isfolder(inputBaseDir)
    error('Figure S2B input directory not found:\n%s', inputBaseDir);
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Analysis settings

roiInfo = struct([]);

roiInfo(1).name = 'OB';
roiInfo(1).displayName = 'Olfactory bulb (OB)';
roiInfo(1).yLimits = [-0.5, 1.0];

roiInfo(2).name = 'AON';
roiInfo(2).displayName = 'Anterior olfactory nucleus (AON)';
roiInfo(2).yLimits = [-0.4, 0.8];

tcFileName = 'tc_matrsess_all_BINS6_TRsbefore2.mat';

preTrials = 11:40;
testTrials = 81:120;

TRSeconds = 1.2;

% Historical labels for the 10-TR peri-stimulus window.
historicalTimeLabels = -2.4:1.2:8.4;

preColor = [204/255, 51/255, 204/255];
testColor = [0, 160/255, 227/255];

lineWidth = 2.5;
semAlpha = 0.20;

%% Load and process OB/AON

results = struct([]);

for roiIndex = 1:numel(roiInfo)

    roiName = roiInfo(roiIndex).name;

    roiDir = fullfile( ...
        inputBaseDir, ...
        roiName ...
    );

    if ~isfolder(roiDir)
        error('ROI input directory not found:\n%s', roiDir);
    end

    tcFile = fullfile( ...
        roiDir, ...
        tcFileName ...
    );

    if ~isfile(tcFile)
        error('Time-course MAT file not found:\n%s', tcFile);
    end

    loadedTC = load(tcFile);

    if ~isfield(loadedTC, 'tc_matrsess_all_highres_lin')
        error([ ...
            'Variable "tc_matrsess_all_highres_lin" missing from:\n%s' ...
        ], ...
            tcFile ...
        );
    end

    if ~isfield(loadedTC, 'tc_matrsess_info')
        error([ ...
            'Variable "tc_matrsess_info" missing from:\n%s' ...
        ], ...
            tcFile ...
        );
    end

    if ~isfield(loadedTC.tc_matrsess_info, 'highres')
        error([ ...
            'Field tc_matrsess_info.highres missing from:\n%s' ...
        ], ...
            tcFile ...
        );
    end

    tcAll = ...
        loadedTC.tc_matrsess_all_highres_lin;

    highresResolution = ...
        loadedTC.tc_matrsess_info.highres;

    %% Validate dimensions

    if ndims(tcAll) ~= 3
        error([ ...
            'tc_matrsess_all_highres_lin for %s must be ' ...
            'subject x trial x time.' ...
        ], ...
            roiName ...
        );
    end

    numberOfSubjects = size(tcAll, 1);
    numberOfTrials = size(tcAll, 2);
    numberOfTimePoints = size(tcAll, 3);

    if numberOfTrials < max(testTrials)
        error([ ...
            '%s contains only %d trials, but TEST requires trial %d.' ...
        ], ...
            roiName, ...
            numberOfTrials, ...
            max(testTrials) ...
        );
    end

    %% Mouse-level PRE and TEST time courses

    preSubjectTC = squeeze( ...
        mean( ...
            tcAll(:, preTrials, :), ...
            2, ...
            'omitnan' ...
        ) ...
    );

    testSubjectTC = squeeze( ...
        mean( ...
            tcAll(:, testTrials, :), ...
            2, ...
            'omitnan' ...
        ) ...
    );

    preSubjectTC = reshape( ...
        preSubjectTC, ...
        numberOfSubjects, ...
        numberOfTimePoints ...
    );

    testSubjectTC = reshape( ...
        testSubjectTC, ...
        numberOfSubjects, ...
        numberOfTimePoints ...
    );

    %% Group mean and SEM across mice

    preMean = mean( ...
        preSubjectTC, ...
        1, ...
        'omitnan' ...
    )';

    testMean = mean( ...
        testSubjectTC, ...
        1, ...
        'omitnan' ...
    )';

    preSEM = ...
        semAcrossSubjects(preSubjectTC)';

    testSEM = ...
        semAcrossSubjects(testSubjectTC)';

    %% Time axis

    sampleIndex = (1:numberOfTimePoints)';

    expectedNumberOfTimePoints = ...
        numel(historicalTimeLabels) * highresResolution;

    if numberOfTimePoints ~= expectedNumberOfTimePoints
        warning([ ...
            '%s contains %d high-resolution samples; based on ' ...
            'tc_matrsess_info.highres = %g, %d were expected.' ...
        ], ...
            roiName, ...
            numberOfTimePoints, ...
            highresResolution, ...
            expectedNumberOfTimePoints ...
        );
    end

    tickPositions = ...
        (1:highresResolution:numberOfTimePoints) - 0.5;

    numberOfTicks = min( ...
        numel(tickPositions), ...
        numel(historicalTimeLabels) ...
    );

    tickPositions = ...
        tickPositions(1:numberOfTicks);

    tickLabels = ...
        historicalTimeLabels(1:numberOfTicks);

    % Approximate time for each high-resolution sample.
    timeSeconds = ...
        -2.4 + ...
        (sampleIndex - 1) .* ...
        (TRSeconds / highresResolution);

    %% Store

    results(roiIndex).name = roiName;
    results(roiIndex).displayName = ...
        roiInfo(roiIndex).displayName;

    results(roiIndex).sampleIndex = sampleIndex;
    results(roiIndex).timeSeconds = timeSeconds;

    results(roiIndex).tickPositions = tickPositions;
    results(roiIndex).tickLabels = tickLabels;

    results(roiIndex).highresResolution = ...
        highresResolution;

    results(roiIndex).preSubjectTC = ...
        preSubjectTC;

    results(roiIndex).testSubjectTC = ...
        testSubjectTC;

    results(roiIndex).preMean = preMean;
    results(roiIndex).testMean = testMean;

    results(roiIndex).preSEM = preSEM;
    results(roiIndex).testSEM = testSEM;

    results(roiIndex).numberOfSubjects = ...
        numberOfSubjects;

    results(roiIndex).yLimits = ...
        roiInfo(roiIndex).yLimits;

    results(roiIndex).tcFile = tcFile;
end

%% Create Figure S2B

fig = figure( ...
    'Name', ...
    'Figure S2B: control OB and AON BOLD time courses', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 1050, 450] ...
);

for roiIndex = 1:numel(roiInfo)

    ax = subplot( ...
        1, ...
        numel(roiInfo), ...
        roiIndex ...
    );

    hold(ax, 'on');

    sampleIndex = ...
        results(roiIndex).sampleIndex;

    highresResolution = ...
        results(roiIndex).highresResolution;

    currentYLimits = ...
        results(roiIndex).yLimits;

    %% Odor period

    odorOnsetSample = ...
        2 * highresResolution + 0.5;

    odorOffsetSample = ...
        odorOnsetSample + ...
        (2.4 * highresResolution) / TRSeconds;

    odorPatch = patch( ...
        ax, ...
        [ ...
            odorOnsetSample, ...
            odorOffsetSample, ...
            odorOffsetSample, ...
            odorOnsetSample ...
        ], ...
        [ ...
            currentYLimits(1), ...
            currentYLimits(1), ...
            currentYLimits(2), ...
            currentYLimits(2) ...
        ], ...
        [0.2, 0.2, 0.2], ...
        'FaceAlpha', ...
        0.10, ...
        'EdgeColor', ...
        'none' ...
    );

    odorPatch.HandleVisibility = 'off';

    %% PRE and TEST

    preLine = plotMeanSem( ...
        ax, ...
        sampleIndex, ...
        results(roiIndex).preMean, ...
        results(roiIndex).preSEM, ...
        preColor, ...
        semAlpha, ...
        lineWidth ...
    );

    testLine = plotMeanSem( ...
        ax, ...
        sampleIndex, ...
        results(roiIndex).testMean, ...
        results(roiIndex).testSEM, ...
        testColor, ...
        semAlpha, ...
        lineWidth ...
    );

    %% Axes

    box(ax, 'off');

    ax.XLim = ...
        [0.5, numel(sampleIndex) + 0.5];

    ax.XTick = ...
        results(roiIndex).tickPositions;

    ax.XTickLabel = ...
        results(roiIndex).tickLabels;

    xlabel(ax, 'Time [s]');
    ylabel(ax, 'BOLD [A.U., z-scored]');

    ax.YLim = ...
        results(roiIndex).yLimits;

    ax.FontSize = 12;
    ax.LineWidth = 1.5;

    title( ...
        ax, ...
        results(roiIndex).displayName, ...
        'Interpreter', ...
        'none' ...
    );

    legend( ...
        ax, ...
        [preLine, testLine], ...
        {'PRE', 'TEST'}, ...
        'Location', ...
        'best', ...
        'Box', ...
        'off' ...
    );
end

sgtitle( ...
    'Figure S2B | no-puff control cohort', ...
    'Interpreter', ...
    'none' ...
);

%% Export source data

for roiIndex = 1:numel(roiInfo)

    roiName = ...
        results(roiIndex).name;

    groupSourceData = table( ...
        results(roiIndex).sampleIndex, ...
        results(roiIndex).timeSeconds, ...
        results(roiIndex).preMean, ...
        results(roiIndex).preSEM, ...
        results(roiIndex).testMean, ...
        results(roiIndex).testSEM, ...
        'VariableNames', {
            'HighResSampleIndex'
            'ApproxTime_s'
            'PRE_Mean'
            'PRE_SEM'
            'TEST_Mean'
            'TEST_SEM'
        } ...
    );

    writetable( ...
        groupSourceData, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_group_timecourse.csv', ...
                roiName ...
            ) ...
        ) ...
    );

    %% Subject-level time courses

    timeVariableNames = arrayfun( ...
        @(x) sprintf('sample_%d', x), ...
        1:size(results(roiIndex).preSubjectTC, 2), ...
        'UniformOutput', ...
        false ...
    );

    preTable = array2table( ...
        results(roiIndex).preSubjectTC, ...
        'VariableNames', ...
        timeVariableNames ...
    );

    preTable = addvars( ...
        preTable, ...
        (1:results(roiIndex).numberOfSubjects)', ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        'SubjectIndex' ...
    );

    testTable = array2table( ...
        results(roiIndex).testSubjectTC, ...
        'VariableNames', ...
        timeVariableNames ...
    );

    testTable = addvars( ...
        testTable, ...
        (1:results(roiIndex).numberOfSubjects)', ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        'SubjectIndex' ...
    );

    writetable( ...
        preTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_PRE_subjects.csv', ...
                roiName ...
            ) ...
        ) ...
    );

    writetable( ...
        testTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_TEST_subjects.csv', ...
                roiName ...
            ) ...
        ) ...
    );
end

%% Metadata

metadata = table( ...
    string('Figure S2B'), ...
    string('no-puff control'), ...
    string('OB; AON'), ...
    string('11-40'), ...
    string('81-120'), ...
    results(1).numberOfSubjects, ...
    results(2).numberOfSubjects, ...
    results(1).highresResolution, ...
    results(2).highresResolution, ...
    string(results(1).tcFile), ...
    string(results(2).tcFile), ...
    'VariableNames', {
        'Figure'
        'Cohort'
        'ROIs'
        'PRE_Trials'
        'TEST_Trials'
        'N_OB'
        'N_AON'
        'OB_HighresSamplesPerTR'
        'AON_HighresSamplesPerTR'
        'OB_TC_File'
        'AON_TC_File'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'AnalysisMetadata_Figure_S2B_control.csv' ...
    ) ...
);

%% Save complete results

save( ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_control_OB_AON_complete_results.mat' ...
    ), ...
    'results', ...
    'roiInfo', ...
    'preTrials', ...
    'testTrials', ...
    'preColor', ...
    'testColor', ...
    'TRSeconds', ...
    'historicalTimeLabels' ...
);

%% Optional provenance

if ~isempty(which('docDataSrc'))

    try
        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );

    catch documentationError

        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export figure

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_control_OB_AON_timecourses.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_control_OB_AON_timecourses.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

savefig( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_control_OB_AON_timecourses.fig' ...
    ) ...
);

fprintf('\nCompleted Supplementary Figure S2B.\n');
fprintf('Cohort: no-puff control\n');
fprintf('ROIs: OB, AON\n');
fprintf('PRE: trials 11-40\n');
fprintf('TEST: trials 81-120\n');
fprintf('Outputs saved to:\n%s\n', outputDir);

%% ========================================================================
% Local functions
%% ========================================================================

function semValues = semAcrossSubjects(subjectByTime)

    n = sum( ...
        isfinite(subjectByTime), ...
        1 ...
    );

    semValues = std( ...
        subjectByTime, ...
        0, ...
        1, ...
        'omitnan' ...
    ) ./ sqrt(n);

    semValues(n < 2) = NaN;
end


function lineHandle = plotMeanSem( ...
    ax, ...
    x, ...
    meanValues, ...
    semValues, ...
    lineColor, ...
    alphaValue, ...
    lineWidth ...
)

    x = x(:);
    meanValues = meanValues(:);
    semValues = semValues(:);

    lower = ...
        meanValues - semValues;

    upper = ...
        meanValues + semValues;

    patchHandle = fill( ...
        ax, ...
        [x; flipud(x)], ...
        [lower; flipud(upper)], ...
        lineColor, ...
        'FaceAlpha', ...
        alphaValue, ...
        'EdgeColor', ...
        'none' ...
    );

    patchHandle.HandleVisibility = 'off';

    lineHandle = plot( ...
        ax, ...
        x, ...
        meanValues, ...
        'Color', ...
        lineColor, ...
        'LineWidth', ...
        lineWidth ...
    );
end
