% panel_B_OB_AON_timecourses_conditioning.m
% Jonathan Reinwald
%
% Repository-adapted BOLD time-course analysis for Supplementary Figure S2B.
%
% Conditioning cohort only.
%
% Panels:
%   1. Olfactory bulb (OB)
%   2. Anterior olfactory nucleus (AON)
%
% For each ROI, the figure shows:
%   PRE  = trials 11-40
%   TEST = trials 81-120
%
% Each line represents the group mean across mice.
% Shaded areas show SEM across mice.
%
% The underlying tc_matrsess_all data are first reordered into the original
% canonical 120-trial sequence using puff_matrsess_all, reproducing the
% sorting logic of the historical script:
%
%   trials  1-40   = pre
%   trials 41-68   = pairing trials with puff
%   trials 69-80   = pairing trials without puff
%   trials 81-120  = test
%
% Figure S2B uses only PRE trials 11-40 and TEST trials 81-120.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/supplement/Figure_S2/
% │   └── panel_B_OB_AON_timecourses_conditioning.m
% │
% ├── data/processed/fMRI/Figure_S2/Figure_S2B/conditioning/
% │   ├── OB/
% │   │   ├── tc_matrsess_all_BINS6_TRsbefore2.mat
% │   │   └── FD_matrsess_all_BINS6_TRsbefore2.mat   (optional fallback)
% │   └── AON/
% │       ├── tc_matrsess_all_BINS6_TRsbefore2.mat
% │       └── FD_matrsess_all_BINS6_TRsbefore2.mat   (optional fallback)
% │
% └── results/supplement/Figure_S2/Figure_S2B/
%
% Required variables:
%   tc_matrsess_all_highres_lin
%   tc_matrsess_info
%   puff_matrsess_all
%
% The high-resolution linearly interpolated time course is the same
% signal used in subplot 1 ("high res.") of the historical analysis.
%
% puff_matrsess_all may be stored either in the tc_matrsess file or,
% as a fallback, in the corresponding FD_matrsess file.
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the script location. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repo/figures/supplement/Figure_S2/panel_B_OB_AON_timecourses_conditioning.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

inputBaseDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_S2', ...
    'Figure_S2B', ...
    'conditioning' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'supplement', ...
    'Figure_S2', ...
    'Figure_S2B', ...
    'conditioning' ...
);

%% Analysis settings

roiInfo = struct([]);

roiInfo(1).name = 'OB';
roiInfo(1).displayName = 'Olfactory bulb (OB)';
roiInfo(1).yLimits = [-0.5, 1.0];

roiInfo(2).name = 'AON';
roiInfo(2).displayName = 'Anterior olfactory nucleus (AON)';
roiInfo(2).yLimits = [-0.4, 0.8];

tcFileName = 'tc_matrsess_all_BINS6_TRsbefore2.mat';
fdFileName = 'FD_matrsess_all_BINS6_TRsbefore2.mat';

preTrials = 11:40;
testTrials = 81:120;

% Original TR and displayed time labels.
TRSeconds = 1.2;
historicalTimeLabels = -2.4:1.2:8.4;

% Historical color convention from the figure caption
preColor = [204/255, 51/255, 204/255];   % magenta
testColor = [0, 160/255, 227/255];       % blue

lineWidth = 2.5;
semAlpha = 0.20;

% Odor presentation
odorOnsetSeconds = 0;
odorOffsetSeconds = 2.4;

%% Check/create directories

if ~isfolder(inputBaseDir)
    error('Figure S2B input directory not found:\n%s', inputBaseDir);
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Load and process OB/AON

results = struct([]);

for roiIndex = 1:numel(roiInfo)

    roiName = roiInfo(roiIndex).name;
    roiDir = fullfile(inputBaseDir, roiName);

    if ~isfolder(roiDir)
        error('ROI input directory not found:\n%s', roiDir);
    end

    tcFile = fullfile(roiDir, tcFileName);
    fdFile = fullfile(roiDir, fdFileName);

    if ~isfile(tcFile)
        error('Time-course MAT file not found:\n%s', tcFile);
    end

    loadedTC = load(tcFile);

    if ~isfield(loadedTC, 'tc_matrsess_all_highres_lin')
        error([ ...
            'Variable "tc_matrsess_all_highres_lin" missing from:\n%s\n\n' ...
            'This is the high-resolution signal used in the original script.' ...
        ], tcFile);
    end

    if ~isfield(loadedTC, 'tc_matrsess_info')
        error('Variable "tc_matrsess_info" missing from:\n%s', tcFile);
    end

    if ~isfield(loadedTC.tc_matrsess_info, 'highres')
        error('Field tc_matrsess_info.highres missing from:\n%s', tcFile);
    end

    tcAll = loadedTC.tc_matrsess_all_highres_lin;
    highresResolution = loadedTC.tc_matrsess_info.highres;

    %% Obtain puff mask

    if isfield(loadedTC, 'puff_matrsess_all')

        puffMask = loadedTC.puff_matrsess_all;
        puffMaskSource = tcFile;

    elseif isfile(fdFile)

        loadedFD = load(fdFile);

        if ~isfield(loadedFD, 'puff_matrsess_all')
            error([ ...
                'Variable "puff_matrsess_all" is absent from both:\n%s\n%s' ...
            ], ...
                tcFile, ...
                fdFile ...
            );
        end

        puffMask = loadedFD.puff_matrsess_all;
        puffMaskSource = fdFile;

    else

        error([ ...
            'Variable "puff_matrsess_all" was not found in:\n%s\n\n' ...
            'and fallback FD file does not exist:\n%s' ...
        ], ...
            tcFile, ...
            fdFile ...
        );
    end

    %% Validate dimensions

    if ndims(tcAll) ~= 3
        error([ ...
            'tc_matrsess_all_highres_lin must be subject x trial x time, but %s ' ...
            'has %d dimensions.' ...
        ], ...
            roiName, ...
            ndims(tcAll) ...
        );
    end

    numberOfSubjects = size(tcAll, 1);
    numberOfOriginalTrials = size(tcAll, 2);
    numberOfTimePoints = size(tcAll, 3);

    if size(puffMask, 1) ~= numberOfSubjects || ...
            size(puffMask, 2) ~= numberOfOriginalTrials
        error([ ...
            '%s: puff_matrsess_all dimensions do not match ' ...
            'tc_matrsess_all_highres_lin.' ...
        ], roiName);
    end

    %% Reconstruct canonical 120-trial order

    tcSorted = nan( ...
        numberOfSubjects, ...
        120, ...
        numberOfTimePoints ...
    );

    for subjectIndex = 1:numberOfSubjects

        subjectPuffMask = logical( ...
            puffMask(subjectIndex, :) ...
        );

        numberOfPuffTrials = sum(subjectPuffMask);
        numberOfNoPuffTrials = sum(~subjectPuffMask);

        if numberOfPuffTrials ~= 28
            error([ ...
                '%s subject %d has %d puff trials; expected 28.' ...
            ], ...
                roiName, ...
                subjectIndex, ...
                numberOfPuffTrials ...
            );
        end

        if numberOfNoPuffTrials ~= 92
            error([ ...
                '%s subject %d has %d no-puff trials; expected 92.' ...
            ], ...
                roiName, ...
                subjectIndex, ...
                numberOfNoPuffTrials ...
            );
        end

        % Puff trials occupy positions 41-68.
        tcSorted(subjectIndex, 41:68, :) = ...
            tcAll(subjectIndex, subjectPuffMask, :);

        % No-puff trials occupy pre, pairing-no-puff, and test positions.
        tcSorted(subjectIndex, [1:40, 69:120], :) = ...
            tcAll(subjectIndex, ~subjectPuffMask, :);
    end

    %% Subject-level PRE and TEST time courses
    %
    % Average trials within each mouse first. Group mean/SEM are then
    % calculated across mice, matching the caption's "mean BOLD time
    % courses (+/- SEM)".

    preSubjectTC = squeeze( ...
        mean( ...
            tcSorted(:, preTrials, :), ...
            2, ...
            'omitnan' ...
        ) ...
    );

    testSubjectTC = squeeze( ...
        mean( ...
            tcSorted(:, testTrials, :), ...
            2, ...
            'omitnan' ...
        ) ...
    );

    % Ensure subject x time orientation even for singleton dimensions.
    preSubjectTC = reshape( ...
        preSubjectTC, ...
        numberOfSubjects, ...
        numberOfTimePoints ...
    );

    testSubjectTC = reshape( ...
        testSubjectTC, ...
        numberOfSubjects, ...
        numberOfTimePoints ...
    );

    %% Group mean and SEM

    preMean = mean(preSubjectTC, 1, 'omitnan')';
    testMean = mean(testSubjectTC, 1, 'omitnan')';

    preSEM = semAcrossSubjects(preSubjectTC)';
    testSEM = semAcrossSubjects(testSubjectTC)';

    %% High-resolution time axis
    %
    % The historical heatmap plotted the high-resolution samples on their
    % native sample axis and placed one tick every tc_matrsess_info.highres
    % samples, labeling these ticks -2.4:1.2:8.4 s.
    %
    % We preserve that convention exactly for the figure. In addition,
    % derive approximate sample-center times for the source-data export.

    sampleIndex = (1:numberOfTimePoints)';

    expectedNumberOfTimePoints = ...
        numel(historicalTimeLabels) * highresResolution;

    if numberOfTimePoints ~= expectedNumberOfTimePoints
        warning([ ...
            '%s contains %d high-resolution samples; based on ' ...
            'tc_matrsess_info.highres = %g and the historical 10-TR ' ...
            'window, %d were expected.' ...
        ], ...
            roiName, ...
            numberOfTimePoints, ...
            highresResolution, ...
            expectedNumberOfTimePoints ...
        );
    end

    tickPositions = ...
        (1:highresResolution:numberOfTimePoints) - 0.5;

    numberOfTicks = min( ...
        numel(tickPositions), ...
        numel(historicalTimeLabels) ...
    );

    tickPositions = tickPositions(1:numberOfTicks);
    tickLabels = historicalTimeLabels(1:numberOfTicks);

    % Interpolate sample-center times from the historical tick convention:
    % x = 0.5 corresponds to -2.4 s; one highresResolution step = 1.2 s.
    timeSeconds = ...
        -2.4 + ...
        ((sampleIndex - 0.5) - 0.5) .* ...
        (TRSeconds / highresResolution);

    %% Store

    results(roiIndex).name = roiName;
    results(roiIndex).displayName = roiInfo(roiIndex).displayName;

    results(roiIndex).sampleIndex = sampleIndex;
    results(roiIndex).timeSeconds = timeSeconds;
    results(roiIndex).tickPositions = tickPositions;
    results(roiIndex).tickLabels = tickLabels;
    results(roiIndex).highresResolution = highresResolution;

    results(roiIndex).preSubjectTC = preSubjectTC;
    results(roiIndex).testSubjectTC = testSubjectTC;

    results(roiIndex).preMean = preMean;
    results(roiIndex).testMean = testMean;

    results(roiIndex).preSEM = preSEM;
    results(roiIndex).testSEM = testSEM;

    results(roiIndex).numberOfSubjects = numberOfSubjects;
    results(roiIndex).yLimits = roiInfo(roiIndex).yLimits;
    results(roiIndex).tcFile = tcFile;
    results(roiIndex).puffMaskSource = puffMaskSource;
end

%% Create Figure S2B

fig = figure( ...
    'Name', ...
    'Figure S2B: conditioning OB and AON BOLD time courses', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 1050, 450] ...
);

axesHandles = gobjects(1, numel(roiInfo));

for roiIndex = 1:numel(roiInfo)

    ax = subplot(1, 2, roiIndex);
    axesHandles(roiIndex) = ax;

    hold(ax, 'on');

    sampleIndex = results(roiIndex).sampleIndex;
    highresResolution = results(roiIndex).highresResolution;

    %% Odor-period shading
    %
    % Reproduce the historical onset convention:
    % odor starts after two pre-stimulus TRs and lasts 2.4 s.

    currentYLimits = results(roiIndex).yLimits;

    odorOnsetSample = ...
        2 * highresResolution + 1 - 0.5;

    odorOffsetSample = ...
        odorOnsetSample + ...
        (2.4 * highresResolution) / TRSeconds;

    odorPatch = patch( ...
            ax, ...
            [ ...
                odorOnsetSample, ...
                odorOffsetSample, ...
                odorOffsetSample, ...
                odorOnsetSample ...
            ], ...
            [ ...
                currentYLimits(1), ...
                currentYLimits(1), ...
                currentYLimits(2), ...
                currentYLimits(2) ...
            ], ...
            [0.2, 0.2, 0.2], ...
            'FaceAlpha', ...
            0.10, ...
            'EdgeColor', ...
            'none' ...
        );

    odorPatch.HandleVisibility = 'off';

    %% PRE

    plotMeanSem( ...
        ax, ...
        sampleIndex, ...
        results(roiIndex).preMean, ...
        results(roiIndex).preSEM, ...
        preColor, ...
        semAlpha, ...
        lineWidth ...
    );

    %% TEST

    plotMeanSem( ...
        ax, ...
        sampleIndex, ...
        results(roiIndex).testMean, ...
        results(roiIndex).testSEM, ...
        testColor, ...
        semAlpha, ...
        lineWidth ...
    );

    %% Axes

    box(ax, 'off');

    ax.XLim = [0.5, numberOfTimePoints + 0.5];
    ax.XTick = results(roiIndex).tickPositions;
    ax.XTickLabel = results(roiIndex).tickLabels;
    xlabel(ax, 'Time [s]');

    ylabel(ax, 'BOLD [A.U., z-scored]');

    ax.YLim = results(roiIndex).yLimits;

    ax.FontSize = 12;
    ax.LineWidth = 1.5;

    title( ...
        ax, ...
        results(roiIndex).displayName, ...
        'Interpreter', ...
        'none' ...
    );

    legend( ...
        ax, ...
        {'PRE', 'TEST'}, ...
        'Location', ...
        'best', ...
        'Box', ...
        'off' ...
    );
end

sgtitle( ...
    'Figure S2B | conditioning cohort', ...
    'Interpreter', ...
    'none' ...
);

%% Save source data

for roiIndex = 1:numel(roiInfo)

    roiName = results(roiIndex).name;
    sampleIndex = results(roiIndex).sampleIndex;
    timeSeconds = results(roiIndex).timeSeconds;

    groupSourceData = table( ...
        sampleIndex, ...
        timeSeconds, ...
        results(roiIndex).preMean, ...
        results(roiIndex).preSEM, ...
        results(roiIndex).testMean, ...
        results(roiIndex).testSEM, ...
        'VariableNames', {
            'HighResSampleIndex'
            'ApproxTime_s'
            'PRE_Mean'
            'PRE_SEM'
            'TEST_Mean'
            'TEST_SEM'
        } ...
    );

    writetable( ...
        groupSourceData, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_group_timecourse.csv', ...
                roiName ...
            ) ...
        ) ...
    );

    %% Subject-level PRE/TEST values

    preTable = array2table( ...
        results(roiIndex).preSubjectTC ...
    );

    preTable = addvars( ...
        preTable, ...
        (1:results(roiIndex).numberOfSubjects)', ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        'SubjectIndex' ...
    );

    testTable = array2table( ...
        results(roiIndex).testSubjectTC ...
    );

    testTable = addvars( ...
        testTable, ...
        (1:results(roiIndex).numberOfSubjects)', ...
        'Before', ...
        1, ...
        'NewVariableNames', ...
        'SubjectIndex' ...
    );

    writetable( ...
        preTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_PRE_subjects.csv', ...
                roiName ...
            ) ...
        ) ...
    );

    writetable( ...
        testTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure_S2B_%s_TEST_subjects.csv', ...
                roiName ...
            ) ...
        ) ...
    );
end

%% Save metadata

metadata = table( ...
    string('Figure S2B'), ...
    string('conditioning'), ...
    string('OB; AON'), ...
    string('11:40'), ...
    string('81:120'), ...
    results(1).numberOfSubjects, ...
    results(2).numberOfSubjects, ...
    results(1).highresResolution, ...
    results(2).highresResolution, ...
    string(results(1).tcFile), ...
    string(results(2).tcFile), ...
    string(results(1).puffMaskSource), ...
    string(results(2).puffMaskSource), ...
    'VariableNames', {
        'Figure'
        'Cohort'
        'ROIs'
        'PRE_Trials'
        'TEST_Trials'
        'N_OB'
        'N_AON'
        'OB_HighresSamplesPerTR'
        'AON_HighresSamplesPerTR'
        'OB_TC_File'
        'AON_TC_File'
        'OB_PuffMaskSource'
        'AON_PuffMaskSource'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'AnalysisMetadata_Figure_S2B_conditioning.csv' ...
    ) ...
);

%% Save complete results

save( ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_conditioning_OB_AON_complete_results.mat' ...
    ), ...
    'results', ...
    'roiInfo', ...
    'preTrials', ...
    'testTrials', ...
    'preColor', ...
    'testColor', ...
    'TRSeconds', ...
    'historicalTimeLabels' ...
);

%% Optional source-script documentation

if ~isempty(which('docDataSrc'))

    try
        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );

    catch documentationError

        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export figure

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_conditioning_OB_AON_timecourses.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_conditioning_OB_AON_timecourses.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

savefig( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S2B_conditioning_OB_AON_timecourses.fig' ...
    ) ...
);

fprintf('\nCompleted Supplementary Figure S2B (conditioning cohort).\n');
fprintf('ROIs: OB, AON\n');
fprintf('Signal: tc_matrsess_all_highres_lin\n');
fprintf('Outputs saved to:\n%s\n', outputDir);


%% ========================================================================
% Local functions
%% ========================================================================

function semValues = semAcrossSubjects(subjectByTime)

    n = sum(isfinite(subjectByTime), 1);

    semValues = std( ...
        subjectByTime, ...
        0, ...
        1, ...
        'omitnan' ...
    ) ./ sqrt(n);

    semValues(n < 2) = NaN;
end


function plotMeanSem( ...
    ax, ...
    x, ...
    meanValues, ...
    semValues, ...
    lineColor, ...
    alphaValue, ...
    lineWidth ...
)

    x = x(:);
    meanValues = meanValues(:);
    semValues = semValues(:);

    lower = meanValues - semValues;
    upper = meanValues + semValues;

    patchHandle = fill( ...
        ax, ...
        [x; flipud(x)], ...
        [lower; flipud(upper)], ...
        lineColor, ...
        'FaceAlpha', ...
        alphaValue, ...
        'EdgeColor', ...
        'none' ...
    );

    patchHandle.HandleVisibility = 'off';

    plot( ...
        ax, ...
        x, ...
        meanValues, ...
        'Color', ...
        lineColor, ...
        'LineWidth', ...
        lineWidth ...
    );
end
