% figure_S19_threshold_matrix_comparison.m
% Jonathan Reinwald
%
% Supplementary Figure S19
%
% Threshold-dependent comparison of functional-connectivity matrices:
%   row 1: conditioning cohort, TEST vs PRE
%   row 2: control cohort, TEST vs PRE
%   row 3: conditioning change vs control change
%
% PRE  = TPnoPuff trials 11-40
% TEST = TPnoPuff trials 81-120
%
% The analysis reuses the gstruc files already used for Figure 4A.
% No raw cormat files are required.
%
% Expected repository inputs:
%
% data/processed/fMRI/Figure_4/
% ├── conditioning/
% │   ├── gstruc_TPnoPuff11to40_p.mat
% │   └── gstruc_TPnoPuff81to120_p.mat
% └── control/
%     ├── gstruc_TPnoPuff11to40_p.mat
%     └── gstruc_TPnoPuff81to120_p.mat
%
% ROI labels are reused from the Figure 3 conditioning data:
%
% data/processed/fMRI/Figure_3/conditioning/
% └── roidata*.mat
%
% Required MATLAB helpers/resources under src/matlab/:
%   lei_pairedtt.m
%   colormaps/myColormapICON.mat
%   colormaps/myColormap_graygreen.mat
%   docDataSrc.m                       (optional)
%
% Outputs:
% results/supplement/Figure_S19/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/supplement/Figure_S19/figure_S19_threshold_matrix_comparison.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile(repoRoot,'src','matlab');
addpath(genpath(srcDir));

conditioningDir = fullfile( ...
    repoRoot,'data','processed','fMRI', ...
    'Figure_4','conditioning' ...
);

controlDir = fullfile( ...
    repoRoot,'data','processed','fMRI', ...
    'Figure_4','control' ...
);

roiDir = fullfile( ...
    repoRoot,'data','processed','fMRI', ...
    'Figure_3','conditioning' ...
);

outputDir = fullfile( ...
    repoRoot,'results','supplement','Figure_S19' ...
);

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Analysis settings

blockPre  = 'TPnoPuff11to40';
blockTest = 'TPnoPuff81to120';

% Original displayed threshold indices:
% ix = 1, 11, 21, 31, 41 -> labels 10, 20, 30, 40, 50 %
thresholdIndices = 1:10:41;
thresholdLabels = thresholdIndices + 9;

% Original 52-region ordering
sorting = [ ...
    4:8,42:43,24:27,1:3,28,12:16,19,18,17,20,21, ...
    9:11,32:33,29:31,34:35,38:41,45:52,22:23,36,37,44 ...
];

%% Required files

conditioningPreFile = fullfile( ...
    conditioningDir, ...
    ['gstruc_' blockPre '_p.mat'] ...
);

conditioningTestFile = fullfile( ...
    conditioningDir, ...
    ['gstruc_' blockTest '_p.mat'] ...
);

controlPreFile = fullfile( ...
    controlDir, ...
    ['gstruc_' blockPre '_p.mat'] ...
);

controlTestFile = fullfile( ...
    controlDir, ...
    ['gstruc_' blockTest '_p.mat'] ...
);

iconColormapFile = fullfile( ...
    srcDir,'helpers','colormaps','myColormapICON.mat' ...
);

grayGreenColormapFile = fullfile( ...
    srcDir,'helpers','colormaps','myColormap_graygreen.mat' ...
);

requiredFiles = {
    conditioningPreFile
    conditioningTestFile
    controlPreFile
    controlTestFile
    iconColormapFile
    grayGreenColormapFile
};

missingFiles = requiredFiles(~cellfun(@isfile,requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required files are missing:\n\n%s', ...
        strjoin(missingFiles,newline) ...
    );
end

if isempty(which('lei_pairedtt'))
    error([ ...
        'lei_pairedtt.m was not found. ' ...
        'Place it somewhere under src/matlab/.' ...
    ]);
end

%% Find ROI-data file

roiFiles = dir(fullfile(roiDir,'roidata*.mat'));

if isempty(roiFiles)
    error( ...
        'No roidata*.mat file found in:\n%s', ...
        roiDir ...
    );
end

% Prefer the v11 Lavender file if present.
roiNames = string({roiFiles.name});
preferred = find( ...
    contains(lower(roiNames),'v11') & ...
    contains(lower(roiNames),'lavender'), ...
    1 ...
);

if isempty(preferred)
    if numel(roiFiles) > 1
        warning( ...
            ['Multiple roidata files found. Using the first one: %s'], ...
            roiFiles(1).name ...
        );
    end
    roiFile = fullfile(roiFiles(1).folder,roiFiles(1).name);
else
    roiFile = fullfile(roiFiles(preferred).folder,roiFiles(preferred).name);
end

fprintf('Using ROI-data file:\n%s\n\n',roiFile);

%% Load ROI names

roiLoaded = load(roiFile);

if ~isfield(roiLoaded,'subj')
    error('Variable "subj" missing from ROI-data file:\n%s',roiFile);
end

subj = roiLoaded.subj;

if numel(subj) < 1 || ~isfield(subj(1),'roi')
    error('Could not read ROI information from:\n%s',roiFile);
end

names = {subj(1).roi.name};

if numel(names) < max(sorting)
    error( ...
        'ROI-data file contains only %d ROI names; sorting requires %d.', ...
        numel(names), ...
        max(sorting) ...
    );
end

names = names(sorting);

%% Load colormaps

iconColormap = loadNumericColormap(iconColormapFile);
grayGreenColormap = loadNumericColormap(grayGreenColormapFile);

%% Load graph-structure data

conditioningPreLoaded  = load(conditioningPreFile,'gstruc');
conditioningTestLoaded = load(conditioningTestFile,'gstruc');
controlPreLoaded       = load(controlPreFile,'gstruc');
controlTestLoaded      = load(controlTestFile,'gstruc');

if ~isfield(conditioningPreLoaded,'gstruc') || ...
   ~isfield(conditioningTestLoaded,'gstruc') || ...
   ~isfield(controlPreLoaded,'gstruc') || ...
   ~isfield(controlTestLoaded,'gstruc')

    error('At least one input MAT does not contain variable "gstruc".');
end

gConditioningPre  = conditioningPreLoaded.gstruc;
gConditioningTest = conditioningTestLoaded.gstruc;
gControlPre       = controlPreLoaded.gstruc;
gControlTest      = controlTestLoaded.gstruc;

%% Validate threshold availability

nThreshConditioning = min( ...
    size(gConditioningPre,1), ...
    size(gConditioningTest,1) ...
);

nThreshControl = min( ...
    size(gControlPre,1), ...
    size(gControlTest,1) ...
);

if max(thresholdIndices) > nThreshConditioning
    error( ...
        'Conditioning gstruc has only %d thresholds; index %d is required.', ...
        nThreshConditioning, ...
        max(thresholdIndices) ...
    );
end

if max(thresholdIndices) > nThreshControl
    error( ...
        'Control gstruc has only %d thresholds; index %d is required.', ...
        nThreshControl, ...
        max(thresholdIndices) ...
    );
end

%% Extract thresholded connectivity matrices

conditioningPre = extractThresholdMatrices( ...
    gConditioningPre,sorting ...
);

conditioningTest = extractThresholdMatrices( ...
    gConditioningTest,sorting ...
);

controlPre = extractThresholdMatrices( ...
    gControlPre,sorting ...
);

controlTest = extractThresholdMatrices( ...
    gControlTest,sorting ...
);

nConditioning = size(gConditioningPre,2);
nControl = size(gControlPre,2);

fprintf('Supplementary Figure S19 input check\n');
fprintf('Conditioning animals: %d\n',nConditioning);
fprintf('Control animals:      %d\n',nControl);
fprintf('Displayed thresholds: %s %%\n\n', ...
    strjoin(string(thresholdLabels),', '));

%% Calculate subjectwise TEST-PRE matrices

conditioningDiff = cell( ...
    1, ...
    min(numel(conditioningPre),numel(conditioningTest)) ...
);

for thresholdIndex = 1:numel(conditioningDiff)

    nSubjects = min( ...
        numel(conditioningPre{thresholdIndex}), ...
        numel(conditioningTest{thresholdIndex}) ...
    );

    conditioningDiff{thresholdIndex} = cell(1,nSubjects);

    for subjectIndex = 1:nSubjects
        conditioningDiff{thresholdIndex}{subjectIndex} = ...
            conditioningTest{thresholdIndex}{subjectIndex} - ...
            conditioningPre{thresholdIndex}{subjectIndex};
    end
end

controlDiff = cell( ...
    1, ...
    min(numel(controlPre),numel(controlTest)) ...
);

for thresholdIndex = 1:numel(controlDiff)

    nSubjects = min( ...
        numel(controlPre{thresholdIndex}), ...
        numel(controlTest{thresholdIndex}) ...
    );

    controlDiff{thresholdIndex} = cell(1,nSubjects);

    for subjectIndex = 1:nSubjects
        controlDiff{thresholdIndex}{subjectIndex} = ...
            controlTest{thresholdIndex}{subjectIndex} - ...
            controlPre{thresholdIndex}{subjectIndex};
    end
end

%% Main matrix-comparison figure

fig = figure( ...
    'Name','Supplementary Figure S19', ...
    'Visible','on', ...
    'Color','white', ...
    'Units','Normalized', ...
    'OuterPosition',[0,0.04,0.8,0.8] ...
);

%% Row 1: conditioning TEST vs PRE

for displayIndex = 1:numel(thresholdIndices)

    ix = thresholdIndices(displayIndex);

    [T,~,p2] = lei_pairedtt( ...
        conditioningTest{ix}, ...
        conditioningPre{ix}, ...
        0.05 ...
    );

    significantT = T .* (p2 < 0.05);

    subplot(3,5,displayIndex);
    imagesc(significantT);

    ax = gca;
    ax.Colormap = [1 1 1; iconColormap];
    ax.CLim = [-5,5];

    axis square;
    colorbar;

    title(sprintf('Conditioning: %d%%',thresholdLabels(displayIndex)));

    saveMatrixSourceData( ...
        significantT, ...
        names, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_conditioning_thresh%d_%sVS%s.csv', ...
                thresholdLabels(displayIndex), ...
                blockPre, ...
                blockTest ...
            ) ...
        ) ...
    );
end

%% Row 2: control TEST vs PRE

for displayIndex = 1:numel(thresholdIndices)

    ix = thresholdIndices(displayIndex);

    [T,~,p2] = lei_pairedtt( ...
        controlTest{ix}, ...
        controlPre{ix}, ...
        0.05 ...
    );

    significantT = T .* (p2 < 0.05);

    subplot(3,5,5+displayIndex);
    imagesc(significantT);

    ax = gca;
    ax.Colormap = [1 1 1; iconColormap];
    ax.CLim = [-5,5];

    axis square;
    colorbar;

    title(sprintf('Control: %d%%',thresholdLabels(displayIndex)));

    saveMatrixSourceData( ...
        significantT, ...
        names, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_control_thresh%d_%sVS%s.csv', ...
                thresholdLabels(displayIndex), ...
                blockPre, ...
                blockTest ...
            ) ...
        ) ...
    );
end

%% Row 3: conditioning change vs control change

% NOTE:
% This intentionally preserves the statistical function used in the
% original analysis (lei_pairedtt) for the between-cohort change comparison.

for displayIndex = 1:numel(thresholdIndices)

    ix = thresholdIndices(displayIndex);

    [T,~,p2] = lei_pairedtt( ...
        conditioningDiff{ix}, ...
        controlDiff{ix}, ...
        0.05 ...
    );

    significantT = T .* (p2 < 0.05);

    subplot(3,5,10+displayIndex);
    imagesc(significantT);

    ax = gca;
    ax.Colormap = [1 1 1; grayGreenColormap];
    ax.CLim = [-5,5];

    axis square;
    colorbar;

    title(sprintf('Conditioning vs control: %d%%', ...
        thresholdLabels(displayIndex)));

    saveMatrixSourceData( ...
        significantT, ...
        names, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_conditioningVScontrol_thresh%d_%sVS%s.csv', ...
                thresholdLabels(displayIndex), ...
                blockPre, ...
                blockTest ...
            ) ...
        ) ...
    );
end

%% Optional provenance

if ~isempty(which('docDataSrc'))
    try
        docDataSrc(fig,outputDir,scriptFile,true);
    catch documentationError
        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export main figure

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        sprintf( ...
            'Figure_S19_matrixComparison_%sVS%s.pdf', ...
            blockPre, ...
            blockTest ...
        ) ...
    ), ...
    'ContentType','vector', ...
    'BackgroundColor','white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        sprintf( ...
            'Figure_S19_matrixComparison_%sVS%s.png', ...
            blockPre, ...
            blockTest ...
        ) ...
    ), ...
    'Resolution',300, ...
    'BackgroundColor','white' ...
);

fprintf('\nSupplementary Figure S19 completed.\n');
fprintf('Results saved to:\n%s\n',outputDir);


%% ========================================================================
% Local functions
%% ========================================================================

function matrices = extractThresholdMatrices(gstruc,sorting)

    nThresholds = size(gstruc,1);
    nSubjects = size(gstruc,2);

    matrices = cell(1,nThresholds);

    for thresholdIndex = 1:nThresholds

        matrices{thresholdIndex} = cell(1,nSubjects);

        for subjectIndex = 1:nSubjects

            if ~isfield(gstruc(thresholdIndex,subjectIndex),'o_CIJ_thresh')
                error( ...
                    ['Field o_CIJ_thresh missing at threshold %d, ' ...
                     'subject %d.'], ...
                    thresholdIndex, ...
                    subjectIndex ...
                );
            end

            currentMatrix = ...
                gstruc(thresholdIndex,subjectIndex).o_CIJ_thresh;

            matrices{thresholdIndex}{subjectIndex} = ...
                currentMatrix(sorting,sorting);
        end
    end
end


function cmap = loadNumericColormap(matFile)

    loaded = load(matFile);
    fields = fieldnames(loaded);

    cmap = [];

    for fieldIndex = 1:numel(fields)

        candidate = loaded.(fields{fieldIndex});

        if isnumeric(candidate) && ...
           ismatrix(candidate) && ...
           size(candidate,2) == 3

            cmap = candidate;
            break;
        end
    end

    if isempty(cmap)
        error( ...
            'No numeric N-by-3 colormap found in:\n%s', ...
            matFile ...
        );
    end
end


function saveMatrixSourceData(matrix,names,outputFile)

    toSave = matrix;
    toSave(isnan(toSave)) = 0;

    sourceData = array2table( ...
        toSave, ...
        'VariableNames',names, ...
        'RowNames',names ...
    );

    writetable( ...
        sourceData, ...
        outputFile, ...
        'WriteVariableNames',true, ...
        'WriteRowNames',true ...
    );
end
