% panel_B_localGA_task_vs_control.m
% Jonathan Reinwald
%
% Repository-adapted local graph-analysis comparison for Figure 4B.
%
% Analysis:
%   - TPnoPuff PRE  = trials 11-40
%   - TPnoPuff TEST = trials 81-120
%   - For each ROI and the two selected local graph metrics:
%
%       l_strength and l_cc only
%
%       Conditioning change = TEST - PRE
%       Control change      = TEST - PRE
%
%     followed by an unpaired t-test:
%
%       Conditioning change vs Control change
%
% Input files are the already-computed local AUC result structures
% (res_auc_struc_local.mat) from threshold range 45-50.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_4/
% │   └── panel_B_localGA_task_vs_control.m
% │
% ├── data/processed/fMRI/Figure_4/Figure_4B/
% │   ├── conditioning/
% │   │   └── res_auc_struc_local.mat
% │   └── control/
% │       └── res_auc_struc_local.mat
% │
% ├── src/matlab/
% │   ├── FDR.m
% │   ├── vals2colormap_jr.m
% │   └── docDataSrc.m              (optional)
% │
% └── results/main/Figure_4/Figure_4B/
%
% Notes:
% - The original analysis used threshold indices 36:41, corresponding
%   to the displayed threshold range 45-50.
% - The original plotting script displayed -t rather than t. This
%   convention is retained so that the adapted figure matches the
%   original visualization. Both raw t and plotted -t are exported.
% - The original script drew significance-reference lines using df=23.
%   Here, the actual ttest2 degrees of freedom are used instead.
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% Script:
% repository/figures/main/Figure_4/panel_B_localGA_task_vs_control.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_4', ...
    'Figure_4B' ...
);

taskFile = fullfile( ...
    inputDir, ...
    'conditioning', ...
    'res_auc_struc_local.mat' ...
);

controlFile = fullfile( ...
    inputDir, ...
    'control', ...
    'res_auc_struc_local.mat' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_4', ...
    'Figure_4B' ...
);

%% Add repository MATLAB helpers

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

requiredFunctions = {
    'FDR'
    'vals2colormap_jr'
};

functionPaths = cellfun( ...
    @which, ...
    requiredFunctions, ...
    'UniformOutput', ...
    false ...
);

missingFunctions = requiredFunctions(cellfun(@isempty, functionPaths));

if ~isempty(missingFunctions)
    error([ ...
        'Required MATLAB functions not found:\n%s\n\n' ...
        'Place them somewhere under src/matlab/.' ...
    ], strjoin(missingFunctions, newline));
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for ttest2 and tinv.' ...
    ]);
end

%% Analysis settings

comparisonName = ...
    'TPnoPuff11to40VSTPnoPuff81to120';

preName = 'TPnoPuff11to40';
testName = 'TPnoPuff81to120';

fdrAlpha = 0.05;

% Original threshold selection:
minThresholdIndex = 36;
maxThresholdIndex = 41;

% Original display convention: index + 9
thresholdDisplayMin = minThresholdIndex + 9;
thresholdDisplayMax = maxThresholdIndex + 9;

% Original anatomical ROI ordering
sorting = [ ...
    4:8, ...
    42:43, ...
    24:27, ...
    1:3, ...
    28, ...
    12:16, ...
    19, ...
    18, ...
    17, ...
    20, ...
    21, ...
    9:11, ...
    32:33, ...
    29:31, ...
    34:35, ...
    38:41, ...
    45:52, ...
    22:23, ...
    36, ...
    37, ...
    44 ...
];

%% Check files/folders

if ~isfile(taskFile)
    error( ...
        'Conditioning AUC result file not found:\n%s', ...
        taskFile ...
    );
end

if ~isfile(controlFile)
    error( ...
        'Control AUC result file not found:\n%s', ...
        controlFile ...
    );
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Load AUC result structures

taskData = load(taskFile);
controlData = load(controlFile);

if ~isfield(taskData, 'res_auc_struc')
    error( ...
        'Variable "res_auc_struc" missing from:\n%s', ...
        taskFile ...
    );
end

if ~isfield(controlData, 'res_auc_struc')
    error( ...
        'Variable "res_auc_struc" missing from:\n%s', ...
        controlFile ...
    );
end

lTask = taskData.res_auc_struc;
lControl = controlData.res_auc_struc;

%% Select local metrics

% Only the two metrics required for Figure 4B
localMetrics = {
    'l_strength'
    'l_cc'
};

for metricCheckIndex = 1:numel(localMetrics)

    metricNameCheck = localMetrics{metricCheckIndex};

    if ~isfield(lTask, metricNameCheck)
        error( ...
            'Required metric "%s" is missing from the conditioning file.', ...
            metricNameCheck ...
        );
    end

    if ~isfield(lControl, metricNameCheck)
        error( ...
            'Required metric "%s" is missing from the control file.', ...
            metricNameCheck ...
        );
    end
end

%% Determine and sort ROI names

firstMetric = localMetrics{1};

if ~isfield(lTask.(firstMetric), testName)
    error([ ...
        'Expected TEST field "%s" missing under metric "%s".' ...
    ], ...
        testName, ...
        firstMetric ...
    );
end

regionNamesUnsorted = fieldnames( ...
    lTask.(firstMetric).(testName) ...
);

if max(sorting) > numel(regionNamesUnsorted)
    error([ ...
        'The sorting vector requires at least %d regions, ' ...
        'but only %d were found.' ...
    ], ...
        max(sorting), ...
        numel(regionNamesUnsorted) ...
    );
end

regionNames = regionNamesUnsorted(sorting);
numberOfRegions = numel(regionNames);

%% Colormap from original script

colorMap = [ ...
    [ ...
        linspace(0, 1, 128)'; ...
        linspace(255/255, 122/255, 128)' ...
    ], ...
    [ ...
        linspace(42/128, 1, 128)'; ...
        linspace(255/255, 46/255, 128)' ...
    ], ...
    [ ...
        linspace(42/128, 1, 128)'; ...
        linspace(255/255, 84/255, 128)' ...
    ] ...
];

%% Process each local metric

allSummaryTables = cell(numel(localMetrics), 1);

for metricIndex = 1:numel(localMetrics)

    metricName = localMetrics{metricIndex};

    fprintf('\n============================================\n');
    fprintf('Figure 4B metric: %s\n', metricName);
    fprintf('============================================\n');

    %% Check PRE/TEST fields in both cohorts

    requiredFieldSetsExist = ...
        isfield(lTask.(metricName), preName) && ...
        isfield(lTask.(metricName), testName) && ...
        isfield(lControl.(metricName), preName) && ...
        isfield(lControl.(metricName), testName);

    if ~requiredFieldSetsExist
        warning([ ...
            'Metric %s does not contain all required PRE/TEST fields ' ...
            'in both cohorts. Skipping.' ...
        ], metricName);

        continue;
    end

    %% Preallocate regional statistics

    tValue = nan(numberOfRegions, 1);
    plottedT = nan(numberOfRegions, 1);

    pValue = nan(numberOfRegions, 1);
    hValue = false(numberOfRegions, 1);
    dfValue = nan(numberOfRegions, 1);

    nTask = nan(numberOfRegions, 1);
    nControl = nan(numberOfRegions, 1);

    meanDeltaTask = nan(numberOfRegions, 1);
    meanDeltaControl = nan(numberOfRegions, 1);

    %% Loop over regions

    for regionIndex = 1:numberOfRegions

        regionName = regionNames{regionIndex};

        % TEST - PRE change in conditioning cohort
        taskTest = ...
            lTask.(metricName).(testName).(regionName);

        taskPre = ...
            lTask.(metricName).(preName).(regionName);

        taskDiff = taskTest - taskPre;

        % TEST - PRE change in control cohort
        controlTest = ...
            lControl.(metricName).(testName).(regionName);

        controlPre = ...
            lControl.(metricName).(preName).(regionName);

        controlDiff = controlTest - controlPre;

        taskDiff = taskDiff(:);
        controlDiff = controlDiff(:);

        % Remove NaNs for robust sample-size reporting and ttest2
        taskDiff = taskDiff(isfinite(taskDiff));
        controlDiff = controlDiff(isfinite(controlDiff));

        nTask(regionIndex) = numel(taskDiff);
        nControl(regionIndex) = numel(controlDiff);

        meanDeltaTask(regionIndex) = mean( ...
            taskDiff, ...
            'omitnan' ...
        );

        meanDeltaControl(regionIndex) = mean( ...
            controlDiff, ...
            'omitnan' ...
        );

        if numel(taskDiff) < 2 || numel(controlDiff) < 2
            warning([ ...
                'Insufficient observations for metric %s, ROI %s. ' ...
                'Skipping t-test.' ...
            ], ...
                metricName, ...
                regionName ...
            );

            continue;
        end

        [ ...
            hValue(regionIndex), ...
            pValue(regionIndex), ...
            ~, ...
            tStats ...
        ] = ttest2( ...
            taskDiff, ...
            controlDiff ...
        );

        tValue(regionIndex) = tStats.tstat;
        dfValue(regionIndex) = tStats.df;
    end

    % Original figure displayed the negative of the raw t-statistic
    plottedT = -tValue;

    %% FDR threshold across regions

    finiteP = pValue(isfinite(pValue));

    if isempty(finiteP)

        fdrThreshold = [];

    else

        fdrThreshold = FDR( ...
            finiteP', ...
            fdrAlpha ...
        );
    end

    fdrSignificant = false(numberOfRegions, 1);

    if ~isempty(fdrThreshold)

        fdrSignificant = ...
            isfinite(pValue) & ...
            pValue <= fdrThreshold;
    end

    %% Create figure

    figureTitle = sprintf( ...
        'Figure 4B: %s, TPnoPuff TEST-PRE conditioning vs control', ...
        metricName ...
    );

    fig = figure( ...
        'Name', ...
        figureTitle, ...
        'Visible', ...
        'on', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 80, 760, 1050] ...
    );

    yPositions = 1:numberOfRegions;

    barHandle = barh( ...
        yPositions, ...
        flip(plottedT), ...
        'FaceColor', ...
        'flat', ...
        'EdgeColor', ...
        'none' ...
    );

    barHandle.CData = vals2colormap_jr( ...
        flip(plottedT), ...
        colorMap, ...
        [-5, 5] ...
    );

    ax = gca;

    box(ax, 'off');

    ax.YTick = yPositions;
    ax.YTickLabel = flip(regionNames);
    ax.TickLabelInterpreter = 'none';

    ax.FontSize = 10;
    ax.LineWidth = 1.5;

    xlabel( ...
        ax, ...
        't statistic (original plotting orientation)', ...
        'Interpreter', ...
        'none' ...
    );

    title( ...
        ax, ...
        metricName, ...
        'Interpreter', ...
        'none', ...
        'FontSize', ...
        14 ...
    );

    %% Symmetric x limits

    finitePlottedT = plottedT(isfinite(plottedT));

    if isempty(finitePlottedT)

        maxAbsoluteT = 1;

    else

        maxAbsoluteT = ceil(max(abs(finitePlottedT)));

        if maxAbsoluteT < 1
            maxAbsoluteT = 1;
        end
    end

    ax.XLim = [-maxAbsoluteT, maxAbsoluteT];

    %% Add p=.05 and FDR reference lines
    %
    % Use actual degrees of freedom from ttest2 rather than the
    % hard-coded df=23 of the legacy plotting script.
    %
    % If df varies across ROIs, use the smallest finite df as a
    % conservative common display threshold.

    finiteDf = dfValue(isfinite(dfValue));

    if ~isempty(finiteDf)

        displayDf = min(finiteDf);

        uncorrectedTCritical = tinv( ...
            1 - 0.05/2, ...
            displayDf ...
        );

        xline( ...
            ax, ...
            uncorrectedTCritical, ...
            '--', ...
            'LineWidth', ...
            1 ...
        );

        xline( ...
            ax, ...
            -uncorrectedTCritical, ...
            '--', ...
            'LineWidth', ...
            1 ...
        );

        if ~isempty(fdrThreshold) && fdrThreshold > 0

            fdrTCritical = tinv( ...
                1 - fdrThreshold/2, ...
                displayDf ...
            );

            xline( ...
                ax, ...
                fdrTCritical, ...
                '-', ...
                'LineWidth', ...
                1.5 ...
            );

            xline( ...
                ax, ...
                -fdrTCritical, ...
                '-', ...
                'LineWidth', ...
                1.5 ...
            );

        else

            fdrTCritical = NaN;
        end

    else

        displayDf = NaN;
        uncorrectedTCritical = NaN;
        fdrTCritical = NaN;
    end

    %% Save source/statistical data

    resultTable = table( ...
        string(regionNames), ...
        tValue, ...
        plottedT, ...
        pValue, ...
        hValue, ...
        fdrSignificant, ...
        dfValue, ...
        nTask, ...
        nControl, ...
        meanDeltaTask, ...
        meanDeltaControl, ...
        'VariableNames', {
            'Region'
            'T_Raw_ConditioningVsControl'
            'T_Plotted_Negated'
            'P'
            'P_LessThan_0_05'
            'FDR_Significant'
            'DegreesOfFreedom'
            'N_Conditioning'
            'N_Control'
            'MeanDelta_Conditioning'
            'MeanDelta_Control'
        } ...
    );

    resultFile = fullfile( ...
        outputDir, ...
        sprintf( ...
            'SourceData_Figure4B_%s.csv', ...
            metricName ...
        ) ...
    );

    writetable( ...
        resultTable, ...
        resultFile ...
    );

    %% Save metadata

    fdrThresholdForTable = NaN;

    if ~isempty(fdrThreshold)
        fdrThresholdForTable = fdrThreshold;
    end

    metadata = table( ...
        string('Figure 4B'), ...
        string(metricName), ...
        string(comparisonName), ...
        minThresholdIndex, ...
        maxThresholdIndex, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax, ...
        fdrAlpha, ...
        fdrThresholdForTable, ...
        displayDf, ...
        uncorrectedTCritical, ...
        fdrTCritical, ...
        string(taskFile), ...
        string(controlFile), ...
        'VariableNames', {
            'Figure'
            'Metric'
            'Comparison'
            'MinThresholdIndex'
            'MaxThresholdIndex'
            'MinThresholdDisplay'
            'MaxThresholdDisplay'
            'FDR_Alpha'
            'FDR_P_Threshold'
            'DisplayDegreesOfFreedom'
            'Uncorrected_T_Critical'
            'FDR_T_Critical'
            'Conditioning_Input_File'
            'Control_Input_File'
        } ...
    );

    writetable( ...
        metadata, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'AnalysisMetadata_Figure4B_%s.csv', ...
                metricName ...
            ) ...
        ) ...
    );

    %% Save MATLAB results

    save( ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Statistics_Figure4B_%s.mat', ...
                metricName ...
            ) ...
        ), ...
        'tValue', ...
        'plottedT', ...
        'pValue', ...
        'hValue', ...
        'fdrSignificant', ...
        'fdrThreshold', ...
        'dfValue', ...
        'nTask', ...
        'nControl', ...
        'meanDeltaTask', ...
        'meanDeltaControl', ...
        'regionNames', ...
        'metricName', ...
        'comparisonName', ...
        'sorting' ...
    );

    %% Optional source-script documentation

    if ~isempty(which('docDataSrc'))

        try
            docDataSrc( ...
                fig, ...
                outputDir, ...
                scriptFile, ...
                true ...
            );
        catch documentationError
            warning( ...
                'docDataSrc failed: %s', ...
                documentationError.message ...
            );
        end
    end

    %% Export figure

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Figure_4B_%s_TaskVsControl.pdf', ...
                metricName ...
            ) ...
        ), ...
        'ContentType', ...
        'vector', ...
        'BackgroundColor', ...
        'white' ...
    );

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Figure_4B_%s_TaskVsControl.png', ...
                metricName ...
            ) ...
        ), ...
        'Resolution', ...
        300, ...
        'BackgroundColor', ...
        'white' ...
    );

    allSummaryTables{metricIndex} = resultTable;

    fprintf( ...
        'Completed %s.\n', ...
        metricName ...
    );
end

%% Save list of processed metrics

processedMetric = string(localMetrics);

metricList = table( ...
    processedMetric, ...
    'VariableNames', ...
    {'Metric'} ...
);

writetable( ...
    metricList, ...
    fullfile( ...
        outputDir, ...
        'Figure4B_ProcessedMetrics.csv' ...
    ) ...
);

fprintf('\nCompleted Figure 4B analysis.\n');
fprintf('Outputs saved to:\n%s\n', outputDir);
