% panel_C_E_global_graph_metrics.m
% Jonathan Reinwald
%
% Repository-adapted analysis for Figure 4C-E.
%
% Figure 4C: Delta C (fractional deviation of clustering coefficient
%             from the lattice reference)
% Figure 4D: Delta L (fractional deviation of average shortest path
%             length from the random reference)
% Figure 4E: Small-world propensity (SWP)
%
% For each metric:
%   1. Conditioning cohort: PRE vs TEST
%   2. TEST-PRE change: conditioning vs control
%
% PRE  = TPnoPuff trials 11-40
% TEST = TPnoPuff trials 81-120
%
% Statistics:
%   - paired t-test + permutation_test_paired for conditioning PRE vs TEST
%   - unpaired t-test + permutation_test_unpaired for TEST-PRE change
%   - Benjamini-Hochberg FDR correction across Delta C, Delta L and SWP
%     separately for these two comparison families
%
% Raw permutation p-values are displayed in the figures. A dagger (†)
% is added when the corresponding permutation p-value survives FDR
% correction across Delta C, Delta L and SWP.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_4/
% │   └── panel_C_E_global_graph_metrics.m
% │
% ├── data/processed/fMRI/Figure_4/Figure_4C_E/
% │   ├── conditioning/
% │   │   ├── auc_struc_TPnoPuff11to40_45to50_p.mat
% │   │   └── auc_struc_TPnoPuff81to120_45to50_p.mat
% │   └── control/
% │       ├── auc_struc_TPnoPuff11to40_45to50_p.mat
% │       └── auc_struc_TPnoPuff81to120_45to50_p.mat
% │
% ├── src/matlab/
% │   ├── notBoxPlot_modified.m
% │   ├── permutation_test_paired.m
% │   ├── permutation_test_unpaired.m
% │   ├── sigstar.m
% │   └── docDataSrc.m              (optional)
% │
% └── results/main/Figure_4/
%     ├── Figure_4C/
%     ├── Figure_4D/
%     └── Figure_4E/
%
% Metric field names:
% Only the following three global metrics are analyzed:
%
%   Delta C : g_delta_C
%   Delta L : g_delta_L
%   SWP     : g_swp
%
% The script stops with an explicit error if any of these fields is
% missing from one of the four AUC input structures.
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% Script location:
% repository/figures/main/Figure_4/panel_C_E_global_graph_metrics.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative directories

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputBaseDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_4', ...
    'Figure_4C_E' ...
);

inputDirTask = fullfile( ...
    inputBaseDir, ...
    'conditioning' ...
);

inputDirControl = fullfile( ...
    inputBaseDir, ...
    'control' ...
);

%% Add MATLAB helper functions

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

requiredFunctions = {
    'notBoxPlot_modified'
    'permutation_test_paired'
    'permutation_test_unpaired'
    'sigstar'
};

missingFunctions = requiredFunctions( ...
    cellfun( ...
        @(x) isempty(which(x)), ...
        requiredFunctions ...
    ) ...
);

if ~isempty(missingFunctions)
    error([ ...
        'Required MATLAB helper functions not found:\n%s\n\n' ...
        'Place them somewhere under src/matlab/.' ...
    ], ...
        strjoin(missingFunctions, newline) ...
    );
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'because this script uses ttest and ttest2.' ...
    ]);
end

%% Analysis settings

preName = 'TPnoPuff11to40';
testName = 'TPnoPuff81to120';

thresholdDisplayMin = 45;
thresholdDisplayMax = 50;

numberOfPermutations = 10000;
randomSeed = 1234;
fdrAlpha = 0.05;

%% Input files

taskPreFile = fullfile( ...
    inputDirTask, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        preName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

taskTestFile = fullfile( ...
    inputDirTask, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        testName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

controlPreFile = fullfile( ...
    inputDirControl, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        preName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

controlTestFile = fullfile( ...
    inputDirControl, ...
    sprintf( ...
        'auc_struc_%s_%dto%d_p.mat', ...
        testName, ...
        thresholdDisplayMin, ...
        thresholdDisplayMax ...
    ) ...
);

requiredFiles = {
    taskPreFile
    taskTestFile
    controlPreFile
    controlTestFile
};

missingFiles = requiredFiles(~cellfun(@isfile, requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required AUC files are missing:\n\n%s', ...
        strjoin(missingFiles, newline) ...
    );
end

%% Load AUC structures

taskPreLoaded = load(taskPreFile);
taskTestLoaded = load(taskTestFile);

controlPreLoaded = load(controlPreFile);
controlTestLoaded = load(controlTestFile);

loadedData = {
    taskPreLoaded
    taskTestLoaded
    controlPreLoaded
    controlTestLoaded
};

loadedNames = {
    taskPreFile
    taskTestFile
    controlPreFile
    controlTestFile
};

for fileIndex = 1:numel(loadedData)

    if ~isfield(loadedData{fileIndex}, 'auc_struc')
        error( ...
            'Variable "auc_struc" is missing from:\n%s', ...
            loadedNames{fileIndex} ...
        );
    end
end

aucTaskPre = taskPreLoaded.auc_struc;
aucTaskTest = taskTestLoaded.auc_struc;

aucControlPre = controlPreLoaded.auc_struc;
aucControlTest = controlTestLoaded.auc_struc;

%% Define the three predefined global metrics
%
% Only these three metrics are analyzed:
%   Figure 4C: g_delta_C
%   Figure 4D: g_delta_L
%   Figure 4E: g_swp

metricInfo = struct([]);

metricInfo(1).panel = 'Figure_4C';
metricInfo(1).shortName = 'deltaC';
metricInfo(1).displayName = '\DeltaC';
metricInfo(1).fieldName = 'g_delta_C';

metricInfo(2).panel = 'Figure_4D';
metricInfo(2).shortName = 'deltaL';
metricInfo(2).displayName = '\DeltaL';
metricInfo(2).fieldName = 'g_delta_L';

metricInfo(3).panel = 'Figure_4E';
metricInfo(3).shortName = 'SWP';
metricInfo(3).displayName = 'SWP';
metricInfo(3).fieldName = 'g_swp';

% Verify that all three fields exist in all four AUC structures
for metricIndex = 1:numel(metricInfo)

    fieldName = metricInfo(metricIndex).fieldName;

    fieldExistsEverywhere = ...
        isfield(aucTaskPre, fieldName) && ...
        isfield(aucTaskTest, fieldName) && ...
        isfield(aucControlPre, fieldName) && ...
        isfield(aucControlTest, fieldName);

    if ~fieldExistsEverywhere
        error([ ...
            'Required global metric field "%s" is not present in all ' ...
            'four AUC input structures.' ...
        ], fieldName);
    end

    fprintf( ...
        '%s uses field: %s\n', ...
        metricInfo(metricIndex).shortName, ...
        fieldName ...
    );
end

%% Prepare all data and statistics before plotting
%
% FDR correction is performed after raw permutation p-values have been
% obtained for all three predefined metrics.

numberOfMetrics = numel(metricInfo);

results = struct([]);

permutationPTask = nan(numberOfMetrics, 1);
permutationPDiff = nan(numberOfMetrics, 1);

rng(randomSeed, 'twister');

for metricIndex = 1:numberOfMetrics

    fieldName = metricInfo(metricIndex).fieldName;

    %% Extract subject-level AUC values

    preTask = getMetricVector(aucTaskPre, fieldName);
    testTask = getMetricVector(aucTaskTest, fieldName);

    preControl = getMetricVector(aucControlPre, fieldName);
    testControl = getMetricVector(aucControlTest, fieldName);

    fprintf( ...
        '%s: n conditioning = %d, n control = %d\n', ...
        fieldName, ...
        numel(preTask), ...
        numel(preControl) ...
    );

    if numel(preTask) ~= numel(testTask)
        error( ...
            '%s: conditioning PRE and TEST sample sizes differ.', ...
            fieldName ...
        );
    end

    if numel(preControl) ~= numel(testControl)
        error( ...
            '%s: control PRE and TEST sample sizes differ.', ...
            fieldName ...
        );
    end

    diffTask = testTask - preTask;
    diffControl = testControl - preControl;

    %% Parametric tests retained from the original analysis

    [hTask, pTask, ~, statsTask] = ttest( ...
        preTask, ...
        testTask ...
    );

    [hDiff, pDiff, ~, statsDiff] = ttest2( ...
        diffTask, ...
        diffControl ...
    );

    %% Permutation tests retained as primary figure inference
    %
    % Conditioning PRE vs TEST: paired permutation test.
    % TEST-PRE conditioning vs control: unpaired permutation test.

    rng(randomSeed, 'twister');

    [~, ~, pValuesTask] = permutation_test_paired( ...
        preTask, ...
        testTask, ...
        numberOfPermutations, ...
        'mean' ...
    );

    rng(randomSeed, 'twister');

    [~, ~, pValuesDiff] = permutation_test_unpaired( ...
        diffTask, ...
        diffControl, ...
        numberOfPermutations, ...
        'mean' ...
    );

    permutationPTask(metricIndex) = ...
        getScalarPermutationP(pValuesTask);

    permutationPDiff(metricIndex) = ...
        getScalarPermutationP(pValuesDiff);

    %% Store complete results

    results(metricIndex).panel = metricInfo(metricIndex).panel;
    results(metricIndex).shortName = metricInfo(metricIndex).shortName;
    results(metricIndex).displayName = metricInfo(metricIndex).displayName;
    results(metricIndex).fieldName = fieldName;

    results(metricIndex).preTask = preTask;
    results(metricIndex).testTask = testTask;
    results(metricIndex).preControl = preControl;
    results(metricIndex).testControl = testControl;

    results(metricIndex).diffTask = diffTask;
    results(metricIndex).diffControl = diffControl;

    results(metricIndex).parametric.task.h = hTask;
    results(metricIndex).parametric.task.p = pTask;
    results(metricIndex).parametric.task.stats = statsTask;

    results(metricIndex).parametric.diff.h = hDiff;
    results(metricIndex).parametric.diff.p = pDiff;
    results(metricIndex).parametric.diff.stats = statsDiff;

    results(metricIndex).permutation.task.pValues = pValuesTask;
    results(metricIndex).permutation.task.p = ...
        permutationPTask(metricIndex);

    results(metricIndex).permutation.diff.pValues = pValuesDiff;
    results(metricIndex).permutation.diff.p = ...
        permutationPDiff(metricIndex);

    results(metricIndex).permutation.methodPaired = ...
        'permutation_test_paired';
    results(metricIndex).permutation.methodUnpaired = ...
        'permutation_test_unpaired';
    results(metricIndex).permutation.statistic = 'mean';
    results(metricIndex).permutation.numberOfPermutations = ...
        numberOfPermutations;
    results(metricIndex).permutation.randomSeed = randomSeed;
end

%% FDR correction across Delta C, Delta L and SWP
%
% Each inferential family is corrected separately:
%   1. conditioning PRE vs TEST
%   2. conditioning vs control TEST-PRE change

[qTask, fdrSigTask] = bhFdrAdjustedP( ...
    permutationPTask, ...
    fdrAlpha ...
);

[qDiff, fdrSigDiff] = bhFdrAdjustedP( ...
    permutationPDiff, ...
    fdrAlpha ...
);

%% Generate panels C-E

for metricIndex = 1:numberOfMetrics

    panelName = metricInfo(metricIndex).panel;
    metricShortName = metricInfo(metricIndex).shortName;
    metricDisplayName = metricInfo(metricIndex).displayName;
    fieldName = metricInfo(metricIndex).fieldName;

    preTask = results(metricIndex).preTask;
    testTask = results(metricIndex).testTask;

    preControl = results(metricIndex).preControl;
    testControl = results(metricIndex).testControl;

    diffTask = results(metricIndex).diffTask;
    diffControl = results(metricIndex).diffControl;

    outputDir = fullfile( ...
        repoRoot, ...
        'results', ...
        'main', ...
        'Figure_4', ...
        panelName ...
    );

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end

    %% Figure

    fig = figure( ...
        'Name', ...
        sprintf('%s: %s', panelName, metricShortName), ...
        'Visible', ...
        'on', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 850, 450] ...
    );

    ax = gobjects(1, 2);

    %% Subplot 1: conditioning PRE vs TEST

    ax(1) = subplot(1, 2, 1);

    bb1 = notBoxPlot_modified( ...
        [preTask, testTask] ...
    );

    formatNotBoxPlotPair( ...
        bb1, ...
        'pretest' ...
    );

    formatAxis( ...
        ax(1), ...
        {'Pre', 'Test'}, ...
        'conditioning' ...
    );

    addPermutationAnnotation( ...
        ax(1), ...
        permutationPTask(metricIndex), ...
        fdrSigTask(metricIndex) ...
    );

    if permutationPTask(metricIndex) < 0.05
        sigstar({[1, 2]}, permutationPTask(metricIndex), 0, 30);
    end

    %% Subplot 2: TEST-PRE change, conditioning vs control

    ax(2) = subplot(1, 2, 2);

    bb3 = notBoxPlot_modified( ...
        [diffTask, diffControl] ...
    );

    formatNotBoxPlotPair( ...
        bb3, ...
        'cohortdiff' ...
    );

    formatAxis( ...
        ax(2), ...
        {'conditioning', 'control'}, ...
        'TEST - PRE' ...
    );

    addPermutationAnnotation( ...
        ax(2), ...
        permutationPDiff(metricIndex), ...
        fdrSigDiff(metricIndex) ...
    );

    if permutationPDiff(metricIndex) < 0.05
        sigstar({[1, 2]}, permutationPDiff(metricIndex), 0, 30);
    end

    %% Overall title

    sgtitle( ...
        sprintf( ...
            '%s | %s | %s', ...
            panelName, ...
            metricDisplayName, ...
            fieldName ...
        ), ...
        'Interpreter', ...
        'none' ...
    );

    %% Save source data

    maxN = max([ ...
        numel(preTask), ...
        numel(testTask), ...
        numel(preControl), ...
        numel(testControl), ...
        numel(diffTask), ...
        numel(diffControl) ...
    ]);

    sourceData = table( ...
        padVector(preTask, maxN), ...
        padVector(testTask, maxN), ...
        padVector(preControl, maxN), ...
        padVector(testControl, maxN), ...
        padVector(diffTask, maxN), ...
        padVector(diffControl, maxN), ...
        'VariableNames', {
            'Pre_Conditioning'
            'Test_Conditioning'
            'Pre_Control'
            'Test_Control'
            'Delta_Conditioning'
            'Delta_Control'
        } ...
    );

    writetable( ...
        sourceData, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_%s_%s.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Save statistics table

    comparison = {
        'Conditioning_PRE_vs_TEST'
        'Delta_Conditioning_vs_Control'
    };

    parametricP = [
        results(metricIndex).parametric.task.p
        results(metricIndex).parametric.diff.p
    ];

    permutationP = [
        permutationPTask(metricIndex)
        permutationPDiff(metricIndex)
    ];

    fdrQ = [
        qTask(metricIndex)
        qDiff(metricIndex)
    ];

    fdrSignificant = [
        fdrSigTask(metricIndex)
        fdrSigDiff(metricIndex)
    ];

    statisticsTable = table( ...
        comparison, ...
        parametricP, ...
        permutationP, ...
        fdrQ, ...
        fdrSignificant, ...
        repmat(numberOfPermutations, 2, 1), ...
        repmat(randomSeed, 2, 1), ...
        'VariableNames', {
            'Comparison'
            'Parametric_P'
            'Permutation_P_Raw'
            'Permutation_FDR_Q'
            'FDR_Significant'
            'NumberOfPermutations'
            'RandomSeed'
        } ...
    );

    writetable( ...
        statisticsTable, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Statistics_%s_%s.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Save metadata

    metadata = table( ...
        string(panelName), ...
        string(metricShortName), ...
        string(metricDisplayName), ...
        string(fieldName), ...
        thresholdDisplayMin, ...
        thresholdDisplayMax, ...
        numberOfPermutations, ...
        randomSeed, ...
        fdrAlpha, ...
        string(taskPreFile), ...
        string(taskTestFile), ...
        string(controlPreFile), ...
        string(controlTestFile), ...
        'VariableNames', {
            'Panel'
            'Metric'
            'DisplayName'
            'AUC_Structure_Field'
            'ThresholdPercentMin'
            'ThresholdPercentMax'
            'NumberOfPermutations'
            'RandomSeed'
            'FDR_Alpha'
            'Conditioning_Pre_File'
            'Conditioning_Test_File'
            'Control_Pre_File'
            'Control_Test_File'
        } ...
    );

    writetable( ...
        metadata, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'AnalysisMetadata_%s_%s.csv', ...
                panelName, ...
                metricShortName ...
            ) ...
        ) ...
    );

    %% Save complete MATLAB results

    currentResult = results(metricIndex);
    currentResult.fdr.task.q = qTask(metricIndex);
    currentResult.fdr.task.significant = fdrSigTask(metricIndex);

    currentResult.fdr.diff.q = qDiff(metricIndex);
    currentResult.fdr.diff.significant = fdrSigDiff(metricIndex);

    save( ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                'Results_%s_%s.mat', ...
                panelName, ...
                metricShortName ...
            ) ...
        ), ...
        'currentResult' ...
    );

    %% Optional source-code annotation

    if ~isempty(which('docDataSrc'))

        try
            docDataSrc( ...
                fig, ...
                outputDir, ...
                scriptFile, ...
                true ...
            );
        catch documentationError
            warning( ...
                'docDataSrc failed: %s', ...
                documentationError.message ...
            );
        end
    end

    %% Export figure

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                '%s_%s.pdf', ...
                panelName, ...
                metricShortName ...
            ) ...
        ), ...
        'ContentType', ...
        'vector', ...
        'BackgroundColor', ...
        'white' ...
    );

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            sprintf( ...
                '%s_%s.png', ...
                panelName, ...
                metricShortName ...
            ) ...
        ), ...
        'Resolution', ...
        300, ...
        'BackgroundColor', ...
        'white' ...
    );
end

%% Save combined FDR summary across all three global metrics

summaryMetric = string({metricInfo.shortName})';
summaryField = string({metricInfo.fieldName})';

fdrSummary = table( ...
    summaryMetric, ...
    summaryField, ...
    permutationPTask, ...
    qTask, ...
    fdrSigTask, ...
    permutationPDiff, ...
    qDiff, ...
    fdrSigDiff, ...
    'VariableNames', {
        'Metric'
        'AUC_Structure_Field'
        'Conditioning_P_Raw'
        'Conditioning_FDR_Q'
        'Conditioning_FDR_Significant'
        'DeltaBetweenCohorts_P_Raw'
        'DeltaBetweenCohorts_FDR_Q'
        'DeltaBetweenCohorts_FDR_Significant'
    } ...
);

summaryOutputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_4' ...
);

writetable( ...
    fdrSummary, ...
    fullfile( ...
        summaryOutputDir, ...
        'Figure_4C_E_GlobalMetrics_FDR_Summary.csv' ...
    ) ...
);

save( ...
    fullfile( ...
        summaryOutputDir, ...
        'Figure_4C_E_GlobalMetrics_complete_results.mat' ...
    ), ...
    'results', ...
    'metricInfo', ...
    'fdrSummary' ...
);

fprintf('\nCompleted Figure 4C-E analysis.\n');
fprintf('Outputs saved under:\n%s\n', summaryOutputDir);

%% ========================================================================
% Local functions
%% ========================================================================

function values = getMetricVector(aucStructure, fieldName)
% Extract one subject-level global AUC metric as a column vector.
%
% auc_struc is a struct array with one element per animal. Therefore,
% aucStructure.(fieldName) produces a comma-separated list. Concatenating
% with square brackets reproduces the logic of the original script:
%
%     [auc_struc.(fieldName)]
%
% and returns one value per animal.

    if ~isfield(aucStructure, fieldName)
        error( ...
            'Metric field "%s" does not exist in auc_struc.', ...
            fieldName ...
        );
    end

    values = [aucStructure.(fieldName)];
    values = values(:);

    if ~isnumeric(values)
        error( ...
            'Metric field "%s" is not numeric.', ...
            fieldName ...
        );
    end

    if any(~isfinite(values))
        warning( ...
            'Metric field "%s" contains NaN/Inf values.', ...
            fieldName ...
        );
    end
end


function p = getScalarPermutationP(pValues)
% The analysis expects one scalar permutation p-value per comparison.
% If a permutation helper unexpectedly returns more than one p-value,
% use the smallest and issue a warning.

    if isempty(pValues)
        p = NaN;
        return;
    end

    pValues = pValues(:);

    if numel(pValues) > 1
        warning([ ...
            'Permutation test returned %d p-values for a scalar graph metric. ' ...
            'Using the smallest p-value.' ...
        ], numel(pValues));
    end

    p = min(pValues);
end


function [qValues, significant] = bhFdrAdjustedP(pValues, alpha)
% Benjamini-Hochberg FDR-adjusted p-values (q-values).

    pValues = pValues(:);

    qValues = nan(size(pValues));
    significant = false(size(pValues));

    finiteMask = isfinite(pValues);

    if ~any(finiteMask)
        return;
    end

    pFinite = pValues(finiteMask);

    [sortedP, sortIndex] = sort(pFinite);
    m = numel(sortedP);

    adjustedSorted = sortedP .* m ./ (1:m)';

    % Enforce monotonicity from largest to smallest rank
    for index = m-1:-1:1
        adjustedSorted(index) = min( ...
            adjustedSorted(index), ...
            adjustedSorted(index + 1) ...
        );
    end

    adjustedSorted = min(adjustedSorted, 1);

    adjustedFinite = nan(m, 1);
    adjustedFinite(sortIndex) = adjustedSorted;

    qValues(finiteMask) = adjustedFinite;
    significant(finiteMask) = adjustedFinite <= alpha;
end


function formatNotBoxPlotPair(bb, plotType)
% Apply the original color scheme.

    for index = 1:numel(bb)

        bb(index).data.MarkerSize = 8;
        bb(index).data.MarkerEdgeColor = 'none';

        bb(index).semPtch.EdgeColor = 'none';
        bb(index).sdPtch.EdgeColor = 'none';
    end

    if strcmp(plotType, 'pretest')

        % PRE
        bb(1).data.MarkerFaceColor = [204/255 51/255 204/255];
        bb(1).mu.Color = [204/255 51/255 204/255];
        bb(1).semPtch.FaceColor = [221/255 118/255 221/255];
        bb(1).sdPtch.FaceColor = [247/255 221/255 247/255];

        % TEST
        bb(2).data.MarkerFaceColor = [0 160/255 227/255];
        bb(2).mu.Color = [0 160/255 227/255];
        bb(2).semPtch.FaceColor = [90/255 194/255 237/255];
        bb(2).sdPtch.FaceColor = [211/255 239/255 250/255];

    elseif strcmp(plotType, 'cohortdiff')

        % Conditioning delta
        bb(1).data.MarkerFaceColor = [0/255 83/255 83/255];
        bb(1).mu.Color = [0/255 83/255 83/255];
        bb(1).semPtch.FaceColor = [104/255 154/255 154/255];
        bb(1).sdPtch.FaceColor = [209/255 224/255 224/255];

        % Control delta
        bb(2).data.MarkerFaceColor = [122/255 46/255 84/255];
        bb(2).mu.Color = [122/255 46/255 84/255];
        bb(2).semPtch.FaceColor = [182/255 140/255 161/255];
        bb(2).sdPtch.FaceColor = [222/255 202/255 213/255];

    else
        error('Unknown plot type: %s', plotType);
    end
end


function formatAxis(ax, xLabels, titleText)

    box(ax, 'off');

    ax.XLim = [0.5 2.5];
    ax.XTick = [1 2];
    ax.XTickLabel = xLabels;

    ax.FontSize = 16;
    ax.FontWeight = 'bold';
    ax.LineWidth = 2.5;

    ylabel(ax, 'A.U.');

    title( ...
        ax, ...
        titleText, ...
        'Interpreter', ...
        'none' ...
    );
end


function addPermutationAnnotation(ax, pValue, fdrSignificant)

    if fdrSignificant
        label = sprintf('p_{perm} = %.5g  \\dagger', pValue);
    else
        label = sprintf('p_{perm} = %.5g', pValue);
    end

    xPosition = ax.XLim(1) + 0.08 * diff(ax.XLim);
    yPosition = ax.YLim(1) + 0.18 * diff(ax.YLim);

    text( ...
        ax, ...
        xPosition, ...
        yPosition, ...
        label, ...
        'Interpreter', ...
        'tex', ...
        'FontSize', ...
        10 ...
    );
end


function padded = padVector(values, targetLength)

    values = values(:);

    padded = nan(targetLength, 1);
    padded(1:numel(values)) = values;
end
