% panel_A_localGA_histograms.m
% Jonathan Reinwald
%
% Repository-adapted local graph-analysis histogram script for Figure 4A.
%
% Metrics retained from the original script:
%   - strength
%   - cc
%
% For each metric and threshold range, the script plots:
%   1. Conditioning cohort: PRE vs TEST
%   2. Control cohort:      PRE vs TEST
%   3. TEST-PRE change:     conditioning vs control
%
% PRE  = TPnoPuff trials 11-40
% TEST = TPnoPuff trials 81-120
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/main/Figure_4/
% │   └── panel_A_localGA_histograms.m
% │
% ├── data/processed/fMRI/Figure_4/
% │   ├── conditioning/
% │   │   ├── gstruc_TPnoPuff11to40_p.mat
% │   │   └── gstruc_TPnoPuff81to120_p.mat
% │   │
% │   └── control/
% │       ├── gstruc_TPnoPuff11to40_p.mat
% │       └── gstruc_TPnoPuff81to120_p.mat
% │
% ├── src/matlab/
% │   ├── permutationTest.m
% │   └── docDataSrc.m              (optional)
% │
% └── results/main/Figure_4/Figure_4A/
%     ├── thresholds_45to50/
%     ├── thresholds_10to50/
%     └── thresholds_40to50/
%
% Notes:
% - Threshold indices are preserved from the original script.
% - The displayed threshold labels follow the original index + 9 convention.
% - The original histogram colors and bin widths are retained.
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% Script location:
% repository/figures/main/Figure_4/panel_A_localGA_histograms.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

inputDirTask = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_4', ...
    'conditioning' ...
);

inputDirControl = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'Figure_4', ...
    'control' ...
);

baseOutputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'main', ...
    'Figure_4', ...
    'Figure_4A' ...
);

%% Add repository MATLAB helpers

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

addpath(genpath(srcDir));

if isempty(which('permutationTest'))
    error([ ...
        'Required function permutationTest.m was not found. ' ...
        'Place it somewhere under src/matlab/.' ...
    ]);
end

%% Analysis settings

preBlock = 'TPnoPuff11to40';
testBlock = 'TPnoPuff81to120';

% Only the two requested metrics
selectedMetrics = {
    'strength'
    'cc'
    };

% Histogram bin widths from the original script
binWidth.strength = 1;
binWidth.cc = 0.05;

% Original threshold-index ranges
thresholdRanges = [
    36, 41
];

% Original display label = threshold index + 9
thresholdDisplayOffset = 9;

numberOfPermutations = 10000;
randomSeed = 1234;

%% Original colors

colorPre = [ ...
    204/255, ...
    51/255, ...
    204/255 ...
];

colorTest = [ ...
    0, ...
    160/255, ...
    227/255 ...
];

colorTaskDiff = [ ...
    0/255, ...
    83/255, ...
    83/255 ...
];

colorControlDiff = [ ...
    122/255, ...
    46/255, ...
    84/255 ...
];

%% Input files

taskPreFile = fullfile( ...
    inputDirTask, ...
    ['gstruc_' preBlock '_p.mat'] ...
);

taskTestFile = fullfile( ...
    inputDirTask, ...
    ['gstruc_' testBlock '_p.mat'] ...
);

controlPreFile = fullfile( ...
    inputDirControl, ...
    ['gstruc_' preBlock '_p.mat'] ...
);

controlTestFile = fullfile( ...
    inputDirControl, ...
    ['gstruc_' testBlock '_p.mat'] ...
);

requiredFiles = {
    taskPreFile
    taskTestFile
    controlPreFile
    controlTestFile
};

missingFiles = requiredFiles(~cellfun(@isfile, requiredFiles));

if ~isempty(missingFiles)
    error([ ...
        'Required gstruc files are missing:\n\n%s' ...
    ], strjoin(missingFiles, newline));
end

%% Load gstruc files once

taskPreData = load(taskPreFile);
taskTestData = load(taskTestFile);

controlPreData = load(controlPreFile);
controlTestData = load(controlTestFile);

loadedStructures = {
    taskPreData
    taskTestData
    controlPreData
    controlTestData
};

loadedNames = {
    taskPreFile
    taskTestFile
    controlPreFile
    controlTestFile
};

for fileIndex = 1:numel(loadedStructures)

    if ~isfield(loadedStructures{fileIndex}, 'gstruc')
        error( ...
            'Variable "gstruc" missing from:\n%s', ...
            loadedNames{fileIndex} ...
        );
    end
end

gTaskPre = taskPreData.gstruc;
gTaskTest = taskTestData.gstruc;

gControlPre = controlPreData.gstruc;
gControlTest = controlTestData.gstruc;

%% Basic threshold-range validation

numberOfThresholds = min([
    size(gTaskPre, 1)
    size(gTaskTest, 1)
    size(gControlPre, 1)
    size(gControlTest, 1)
]);

if max(thresholdRanges(:)) > numberOfThresholds
    error([ ...
        'At least one requested threshold index exceeds the available ' ...
        'gstruc range. Maximum requested index = %d; available = %d.' ...
    ], ...
        max(thresholdRanges(:)), ...
        numberOfThresholds ...
    );
end

if ~isfolder(baseOutputDir)
    mkdir(baseOutputDir);
end

%% Reproducible randomization

rng(randomSeed, 'twister');

%% Loop over threshold ranges

for rangeIndex = 1:size(thresholdRanges, 1)

    minThresholdIndex = thresholdRanges(rangeIndex, 1);
    maxThresholdIndex = thresholdRanges(rangeIndex, 2);

    thresholdLabelMin = ...
        minThresholdIndex + thresholdDisplayOffset;

    thresholdLabelMax = ...
        maxThresholdIndex + thresholdDisplayOffset;

    thresholdLabel = sprintf( ...
        '%dto%d', ...
        thresholdLabelMin, ...
        thresholdLabelMax ...
    );

    outputDir = fullfile( ...
        baseOutputDir, ...
        ['thresholds_' thresholdLabel] ...
    );

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end

    fprintf('\n============================================\n');
    fprintf('Figure 4A: thresholds %s\n', thresholdLabel);
    fprintf('============================================\n');

    %% Loop over requested metrics

    for metricIndex = 1:numel(selectedMetrics)

        metricName = selectedMetrics{metricIndex};
        fieldName = ['l_' metricName];

        fprintf('Metric: %s\n', metricName);

        %% Verify metric exists in all four files

        metricExists = ...
            isfield(gTaskPre, fieldName) && ...
            isfield(gTaskTest, fieldName) && ...
            isfield(gControlPre, fieldName) && ...
            isfield(gControlTest, fieldName);

        if ~metricExists

            warning([ ...
                'Metric %s is not available in all four gstruc files. ' ...
                'Skipping this metric for threshold range %s.' ...
            ], ...
                metricName, ...
                thresholdLabel ...
            );

            continue;
        end

        %% Extract values across selected thresholds

        taskPreValues = extractMetricValues( ...
            gTaskPre, ...
            fieldName, ...
            minThresholdIndex, ...
            maxThresholdIndex ...
        );

        taskTestValues = extractMetricValues( ...
            gTaskTest, ...
            fieldName, ...
            minThresholdIndex, ...
            maxThresholdIndex ...
        );

        controlPreValues = extractMetricValues( ...
            gControlPre, ...
            fieldName, ...
            minThresholdIndex, ...
            maxThresholdIndex ...
        );

        controlTestValues = extractMetricValues( ...
            gControlTest, ...
            fieldName, ...
            minThresholdIndex, ...
            maxThresholdIndex ...
        );

        %% Validate corresponding PRE/TEST matrix sizes

        if ~isequal(size(taskPreValues), size(taskTestValues))
            error([ ...
                'Conditioning PRE and TEST values have different sizes ' ...
                'for metric %s.' ...
            ], metricName);
        end

        if ~isequal(size(controlPreValues), size(controlTestValues))
            error([ ...
                'Control PRE and TEST values have different sizes ' ...
                'for metric %s.' ...
            ], metricName);
        end

        %% TEST - PRE differences

        taskDiffValues = ...
            taskTestValues - taskPreValues;

        controlDiffValues = ...
            controlTestValues - controlPreValues;

        %% Flatten for histograms/statistics

        taskPreVector = taskPreValues(:);
        taskTestVector = taskTestValues(:);

        controlPreVector = controlPreValues(:);
        controlTestVector = controlTestValues(:);

        taskDiffVector = taskDiffValues(:);
        controlDiffVector = controlDiffValues(:);

        %% Create figure

        figureTitle = sprintf( ...
            'Figure 4A: %s, thresholds %s', ...
            metricName, ...
            thresholdLabel ...
        );

        fig = figure( ...
            'Name', ...
            figureTitle, ...
            'Visible', ...
            'on', ...
            'Color', ...
            'white', ...
            'Position', ...
            [100, 100, 1500, 520] ...
        );

        tiledlayout( ...
            1, ...
            3, ...
            'TileSpacing', ...
            'compact', ...
            'Padding', ...
            'compact' ...
        );

        %% Panel 1: conditioning PRE vs TEST

        ax1 = nexttile;

        plotHistogramPair( ...
            ax1, ...
            taskPreVector, ...
            taskTestVector, ...
            binWidth.(metricName), ...
            colorPre, ...
            colorTest, ...
            preBlock, ...
            testBlock, ...
            metricName ...
        );

        title( ...
            ax1, ...
            'conditioning', ...
            'Interpreter', ...
            'none' ...
        );

        %% Panel 2: control PRE vs TEST

        ax2 = nexttile;

        plotHistogramPair( ...
            ax2, ...
            controlPreVector, ...
            controlTestVector, ...
            binWidth.(metricName), ...
            colorPre, ...
            colorTest, ...
            preBlock, ...
            testBlock, ...
            metricName ...
        );

        title( ...
            ax2, ...
            'control', ...
            'Interpreter', ...
            'none' ...
        );

        %% Panel 3: TEST-PRE change, conditioning vs control

        ax3 = nexttile;

        plotHistogramPair( ...
            ax3, ...
            taskDiffVector, ...
            controlDiffVector, ...
            binWidth.(metricName), ...
            colorTaskDiff, ...
            colorControlDiff, ...
            'conditioning', ...
            'control', ...
            ['Delta ' metricName] ...
        );

        title( ...
            ax3, ...
            'TEST - PRE', ...
            'Interpreter', ...
            'none' ...
        );

        %% Match y-axis limits

        allYMax = max([
            ax1.YLim(2)
            ax2.YLim(2)
            ax3.YLim(2)
        ]);

        ax1.YLim = [0, allYMax];
        ax2.YLim = [0, allYMax];
        ax3.YLim = [0, allYMax];

        sgtitle( ...
            figureTitle, ...
            'Interpreter', ...
            'none' ...
        );

        %% Permutation tests
        %
        % This preserves the original use of permutationTest on the
        % flattened metric values.

        rng(randomSeed, 'twister');

        [ ...
            pTask, ...
            observedDifferenceTask, ...
            effectSizeTask ...
        ] = permutationTest( ...
            taskPreVector, ...
            taskTestVector, ...
            numberOfPermutations ...
        );

        rng(randomSeed, 'twister');

        [ ...
            pControl, ...
            observedDifferenceControl, ...
            effectSizeControl ...
        ] = permutationTest( ...
            controlPreVector, ...
            controlTestVector, ...
            numberOfPermutations ...
        );

        rng(randomSeed, 'twister');

        [ ...
            pDiff, ...
            observedDifferenceDiff, ...
            effectSizeDiff ...
        ] = permutationTest( ...
            taskDiffVector, ...
            controlDiffVector, ...
            numberOfPermutations ...
        );

        %% Annotate p-values

        addPValueText(ax1, pTask);
        addPValueText(ax2, pControl);
        addPValueText(ax3, pDiff);

        %% Save source data
        %
        % Each distribution is stored in its own column. NaN padding is
        % used if the conditioning and control vectors differ in length.

        maxLength = max([
            numel(taskPreVector)
            numel(taskTestVector)
            numel(controlPreVector)
            numel(controlTestVector)
            numel(taskDiffVector)
            numel(controlDiffVector)
        ]);

        sourceData = table( ...
            padVector(taskPreVector, maxLength), ...
            padVector(taskTestVector, maxLength), ...
            padVector(controlPreVector, maxLength), ...
            padVector(controlTestVector, maxLength), ...
            padVector(taskDiffVector, maxLength), ...
            padVector(controlDiffVector, maxLength), ...
            'VariableNames', {
                'Pre_Conditioning'
                'Test_Conditioning'
                'Pre_Control'
                'Test_Control'
                'Delta_Conditioning'
                'Delta_Control'
            } ...
        );

        sourceDataFile = fullfile( ...
            outputDir, ...
            sprintf( ...
                'SourceData_Figure4A_%s_thresholds_%s.csv', ...
                metricName, ...
                thresholdLabel ...
            ) ...
        );

        writetable( ...
            sourceData, ...
            sourceDataFile ...
        );

        %% Save permutation statistics

        comparison = {
            'Conditioning_PRE_vs_TEST'
            'Control_PRE_vs_TEST'
            'Delta_Conditioning_vs_Control'
        };

        pValue = [
            pTask
            pControl
            pDiff
        ];

        observedDifference = [
            observedDifferenceTask
            observedDifferenceControl
            observedDifferenceDiff
        ];

        effectSize = [
            effectSizeTask
            effectSizeControl
            effectSizeDiff
        ];

        statisticsTable = table( ...
            comparison, ...
            pValue, ...
            observedDifference, ...
            effectSize, ...
            repmat(numberOfPermutations, 3, 1), ...
            repmat(randomSeed, 3, 1), ...
            'VariableNames', {
                'Comparison'
                'Permutation_P'
                'ObservedDifference'
                'EffectSize'
                'NumberOfPermutations'
                'RandomSeed'
            } ...
        );

        statisticsFile = fullfile( ...
            outputDir, ...
            sprintf( ...
                'Statistics_Figure4A_%s_thresholds_%s.csv', ...
                metricName, ...
                thresholdLabel ...
            ) ...
        );

        writetable( ...
            statisticsTable, ...
            statisticsFile ...
        );

        %% Save complete MATLAB results

        metricResults = struct;

        metricResults.metric = metricName;
        metricResults.thresholdIndexRange = [ ...
            minThresholdIndex, ...
            maxThresholdIndex ...
        ];

        metricResults.thresholdDisplayRange = [ ...
            thresholdLabelMin, ...
            thresholdLabelMax ...
        ];

        metricResults.taskPre = taskPreValues;
        metricResults.taskTest = taskTestValues;
        metricResults.controlPre = controlPreValues;
        metricResults.controlTest = controlTestValues;

        metricResults.taskDiff = taskDiffValues;
        metricResults.controlDiff = controlDiffValues;

        metricResults.pTask = pTask;
        metricResults.pControl = pControl;
        metricResults.pDiff = pDiff;

        metricResults.observedDifferenceTask = ...
            observedDifferenceTask;

        metricResults.observedDifferenceControl = ...
            observedDifferenceControl;

        metricResults.observedDifferenceDiff = ...
            observedDifferenceDiff;

        metricResults.effectSizeTask = effectSizeTask;
        metricResults.effectSizeControl = effectSizeControl;
        metricResults.effectSizeDiff = effectSizeDiff;

        save( ...
            fullfile( ...
                outputDir, ...
                sprintf( ...
                    'Figure4A_%s_thresholds_%s_results.mat', ...
                    metricName, ...
                    thresholdLabel ...
                ) ...
            ), ...
            'metricResults' ...
        );

        %% Save metadata

        metadata = table( ...
            string('Figure 4A'), ...
            string(metricName), ...
            minThresholdIndex, ...
            maxThresholdIndex, ...
            thresholdLabelMin, ...
            thresholdLabelMax, ...
            numberOfPermutations, ...
            randomSeed, ...
            string(taskPreFile), ...
            string(taskTestFile), ...
            string(controlPreFile), ...
            string(controlTestFile), ...
            'VariableNames', {
                'Figure'
                'Metric'
                'MinThresholdIndex'
                'MaxThresholdIndex'
                'MinThresholdDisplay'
                'MaxThresholdDisplay'
                'NumberOfPermutations'
                'RandomSeed'
                'Conditioning_Pre_File'
                'Conditioning_Test_File'
                'Control_Pre_File'
                'Control_Test_File'
            } ...
        );

        writetable( ...
            metadata, ...
            fullfile( ...
                outputDir, ...
                sprintf( ...
                    'AnalysisMetadata_Figure4A_%s_thresholds_%s.csv', ...
                    metricName, ...
                    thresholdLabel ...
                ) ...
            ) ...
        );

        %% Optional source-script documentation

        if ~isempty(which('docDataSrc'))

            try
                docDataSrc( ...
                    fig, ...
                    outputDir, ...
                    scriptFile, ...
                    true ...
                );
            catch documentationError
                warning( ...
                    'docDataSrc failed: %s', ...
                    documentationError.message ...
                );
            end
        end

        %% Export figure

        figurePdf = fullfile( ...
            outputDir, ...
            sprintf( ...
                'Figure_4A_%s_thresholds_%s.pdf', ...
                metricName, ...
                thresholdLabel ...
            ) ...
        );

        figurePng = fullfile( ...
            outputDir, ...
            sprintf( ...
                'Figure_4A_%s_thresholds_%s.png', ...
                metricName, ...
                thresholdLabel ...
            ) ...
        );

        exportgraphics( ...
            fig, ...
            figurePdf, ...
            'ContentType', ...
            'vector', ...
            'BackgroundColor', ...
            'white' ...
        );

        exportgraphics( ...
            fig, ...
            figurePng, ...
            'Resolution', ...
            300, ...
            'BackgroundColor', ...
            'white' ...
        );

        fprintf( ...
            'Completed %s for thresholds %s.\n', ...
            metricName, ...
            thresholdLabel ...
        );
    end
end

fprintf('\nCompleted Figure 4A analysis.\n');
fprintf('Outputs saved to:\n%s\n', baseOutputDir);

%% Local functions

function values = extractMetricValues( ...
    gstruc, ...
    fieldName, ...
    minThresholdIndex, ...
    maxThresholdIndex ...
)
% Extract the selected local graph metric across the requested
% threshold-index range using the same concatenation logic as the
% original script.

    values = [ ...
        gstruc( ...
            minThresholdIndex:maxThresholdIndex, ...
            : ...
        ).(fieldName) ...
    ];
end


function plotHistogramPair( ...
    ax, ...
    values1, ...
    values2, ...
    binWidth, ...
    color1, ...
    color2, ...
    label1, ...
    label2, ...
    xLabelText ...
)
% Plot two overlaid filled/stair histograms and mean lines.

    axes(ax);
    hold(ax, 'on');

    h1 = histogram( ...
        ax, ...
        values1, ...
        'BinWidth', ...
        binWidth, ...
        'EdgeColor', ...
        'none', ...
        'FaceColor', ...
        color1, ...
        'FaceAlpha', ...
        0.10 ...
    );

    histogram( ...
        ax, ...
        values1, ...
        'BinWidth', ...
        binWidth, ...
        'DisplayStyle', ...
        'stairs', ...
        'EdgeColor', ...
        color1, ...
        'LineWidth', ...
        2.5 ...
    );

    h2 = histogram( ...
        ax, ...
        values2, ...
        'BinWidth', ...
        binWidth, ...
        'EdgeColor', ...
        'none', ...
        'FaceColor', ...
        color2, ...
        'FaceAlpha', ...
        0.10 ...
    );

    histogram( ...
        ax, ...
        values2, ...
        'BinWidth', ...
        binWidth, ...
        'DisplayStyle', ...
        'stairs', ...
        'EdgeColor', ...
        color2, ...
        'LineWidth', ...
        2.5 ...
    );

    maxCount = max([ ...
        h1.BinCounts, ...
        h2.BinCounts, ...
        1 ...
    ]);

    mean1 = mean(values1, 'omitnan');
    mean2 = mean(values2, 'omitnan');

    line( ...
        ax, ...
        [mean1, mean1], ...
        [0, maxCount], ...
        'Color', ...
        color1, ...
        'LineWidth', ...
        1.5 ...
    );

    line( ...
        ax, ...
        [mean2, mean2], ...
        [0, maxCount], ...
        'Color', ...
        color2, ...
        'LineWidth', ...
        1.5, ...
        'LineStyle', ...
        '--' ...
    );

    legend( ...
        ax, ...
        [h1, h2], ...
        {label1, label2}, ...
        'Interpreter', ...
        'none', ...
        'Location', ...
        'best' ...
    );

    box(ax, 'off');

    ax.LineWidth = 2.5;
    ax.FontWeight = 'bold';
    ax.FontSize = 14;

    ylabel(ax, 'rate');
    xlabel(ax, xLabelText, 'Interpreter', 'none');
end


function addPValueText(ax, pValue)
% Add permutation p-value to the upper-right area of an axis.

    xPosition = ...
        ax.XLim(1) + 0.62 * diff(ax.XLim);

    yPosition = ...
        ax.YLim(1) + 0.86 * diff(ax.YLim);

    text( ...
        ax, ...
        xPosition, ...
        yPosition, ...
        sprintf('p = %.5g', pValue), ...
        'FontSize', ...
        10 ...
    );
end


function padded = padVector(values, targetLength)
% Pad a numeric vector with NaNs to a common output length.

    values = values(:);

    padded = nan(targetLength, 1);

    padded(1:numel(values)) = values;
end
