% panel_B_week1_week2_rank_DS.m
% Jonathan Reinwald
%
% Supplementary Figure S8B-C
%
% Week-to-week stability of social hierarchy measures across NoSeMaze 1
% and NoSeMaze 2.
%
% Revised panel mapping:
%   Figure S8B: David's score, Week 1 vs Week 2, z-scored within cohort/week
%   Figure S8C: NoSeMaze rank, Week 1 vs Week 2
%
% Correlations retained from the original analysis:
%   - Rank: Spearman
%   - David's score: Pearson on cohort-wise z-scored values
%
% All animals are shown with identical markers; no point labels or cohort colors.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/supplement/Figure_S8/
% │   └── panel_B_week1_week2_rank_DS.m
% │
% ├── data/processed/NoSeMaze/tubetest/
% │   ├── NoSeMaze_1/
% │   │   ├── DS_info_AM1_day3to9_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │   │   └── DS_info_AM1_day10to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │   └── NoSeMaze_2/
% │       ├── DS_info_AM2_day1to7_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │       └── DS_info_AM2_day8to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat
% │
% └── results/supplement/Figure_S8/Figure_S8B_C/
%
% Optional helper:
%   src/matlab/.../docDataSrc.m
%
% -------------------------------------------------------------------------

clear;
clc;
close all;

%% Settings

rankCorrType = 'Spearman';
DSCorrType   = 'Pearson';

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repo/figures/supplement/Figure_S8/panel_B_week1_week2_rank_DS.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile(repoRoot,'src','matlab');

if isfolder(srcDir)
    addpath(genpath(srcDir));
end

noSeMazeDir = fullfile( ...
    repoRoot, ...
    'data','processed','NoSeMaze','tubetest' ...
);

nm1Dir = fullfile(noSeMazeDir,'NoSeMaze_1');
nm2Dir = fullfile(noSeMazeDir,'NoSeMaze_2');

outputDir = fullfile( ...
    repoRoot, ...
    'results','supplement', ...
    'Figure_S8','Figure_S8B_C' ...
);

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Input files

NM1_week1_file = fullfile( ...
    nm1Dir, ...
    'DS_info_AM1_day3to9_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

NM1_week2_file = fullfile( ...
    nm1Dir, ...
    'DS_info_AM1_day10to16_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

NM2_week1_file = fullfile( ...
    nm2Dir, ...
    'DS_info_AM2_day1to7_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

NM2_week2_file = fullfile( ...
    nm2Dir, ...
    'DS_info_AM2_day8to14_12mice_withChasingAndDoubleChasing_thresh10_td15tt2s.mat' ...
);

requiredFiles = {
    NM1_week1_file
    NM1_week2_file
    NM2_week1_file
    NM2_week2_file
};

missingFiles = requiredFiles(~cellfun(@isfile,requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required Figure S8B-C input files are missing:\n\n%s', ...
        strjoin(missingFiles,newline) ...
    );
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for corr and zscore.' ...
    ]);
end

%% Load hierarchy data

NM1_W1 = loadDSInfo(NM1_week1_file);
NM1_W2 = loadDSInfo(NM1_week2_file);

NM2_W1 = loadDSInfo(NM2_week1_file);
NM2_W2 = loadDSInfo(NM2_week2_file);

%% Assemble paired data

NM1_rank_w1 = NM1_W1.rank(:);
NM1_rank_w2 = NM1_W2.rank(:);

NM2_rank_w1 = NM2_W1.rank(:);
NM2_rank_w2 = NM2_W2.rank(:);

NM1_DS_w1 = NM1_W1.DS(:);
NM1_DS_w2 = NM1_W2.DS(:);

NM2_DS_w1 = NM2_W1.DS(:);
NM2_DS_w2 = NM2_W2.DS(:);

%% Basic checks

assert( ...
    numel(NM1_rank_w1) == numel(NM1_rank_w2), ...
    'NM1 rank vectors have different lengths.' ...
);

assert( ...
    numel(NM2_rank_w1) == numel(NM2_rank_w2), ...
    'NM2 rank vectors have different lengths.' ...
);

assert( ...
    numel(NM1_DS_w1) == numel(NM1_DS_w2), ...
    'NM1 David''s score vectors have different lengths.' ...
);

assert( ...
    numel(NM2_DS_w1) == numel(NM2_DS_w2), ...
    'NM2 David''s score vectors have different lengths.' ...
);

%% Combine cohorts

rank_w1 = [
    NM1_rank_w1
    NM2_rank_w1
];

rank_w2 = [
    NM1_rank_w2
    NM2_rank_w2
];

DS_w1_raw = [
    NM1_DS_w1
    NM2_DS_w1
];

DS_w2_raw = [
    NM1_DS_w2
    NM2_DS_w2
];

%% Z-score David's score within each NoSeMaze cohort and week

NM1_DS_w1_z = zscore(NM1_DS_w1);
NM1_DS_w2_z = zscore(NM1_DS_w2);

NM2_DS_w1_z = zscore(NM2_DS_w1);
NM2_DS_w2_z = zscore(NM2_DS_w2);

DS_w1_z = [
    NM1_DS_w1_z
    NM2_DS_w1_z
];

DS_w2_z = [
    NM1_DS_w2_z
    NM2_DS_w2_z
];

%% Group labels

group = [
    repmat("AM1",numel(NM1_rank_w1),1)
    repmat("AM2",numel(NM2_rank_w1),1)
];

mouseID = [
    compose("AM1-%02d",(1:numel(NM1_rank_w1))')
    compose("AM2-%02d",(1:numel(NM2_rank_w1))')
];

%% Statistics

validRank = isfinite(rank_w1) & isfinite(rank_w2);

[rRank,pRank] = corr( ...
    rank_w1(validRank), ...
    rank_w2(validRank), ...
    'Rows','complete', ...
    'Type',rankCorrType ...
);

validDS = isfinite(DS_w1_z) & isfinite(DS_w2_z);

[rDS,pDS] = corr( ...
    DS_w1_z(validDS), ...
    DS_w2_z(validDS), ...
    'Rows','complete', ...
    'Type',DSCorrType ...
);

fprintf('\nSupplementary Figure S8B-C\n');
fprintf('----------------------------------------\n');

fprintf( ...
    'NoSeMaze rank: %s r = %.3f, p = %.4g, n = %d\n', ...
    rankCorrType,rRank,pRank,sum(validRank) ...
);

fprintf( ...
    'David''s score: %s r = %.3f, p = %.4g, n = %d\n\n', ...
    DSCorrType,rDS,pDS,sum(validDS) ...
);

%% Figure S8B

fig = figure( ...
    'Name','Supplementary Figure S8B-C', ...
    'Color','white', ...
    'Visible','on', ...
    'Position',[200,200,1150,500] ...
);

tl = tiledlayout( ...
    fig, ...
    1,2, ...
    'Padding','compact', ...
    'TileSpacing','compact' ...
);

%% Figure S8B: David's score stability

ax1 = nexttile(tl);

plotCorrelationPanel( ...
    ax1, ...
    DS_w1_z, ...
    DS_w2_z, ...
    DSCorrType, ...
    'S8B | David''s score', ...
    'Week 1 David''s score, z-scored', ...
    'Week 2 David''s score, z-scored' ...
);

%% Figure S8C: rank stability

ax2 = nexttile(tl);

plotCorrelationPanel( ...
    ax2, ...
    rank_w1, ...
    rank_w2, ...
    rankCorrType, ...
    'S8C | NoSeMaze rank', ...
    'Week 1 rank', ...
    'Week 2 rank' ...
);

title( ...
    tl, ...
    'Figure S8B-C | Week 1 vs Week 2 hierarchy stability', ...
    'FontSize',14, ...
    'FontWeight','bold' ...
);

%% Source data

sourceData = table( ...
    group, ...
    mouseID, ...
    rank_w1, ...
    rank_w2, ...
    DS_w1_raw, ...
    DS_w2_raw, ...
    DS_w1_z, ...
    DS_w2_z, ...
    'VariableNames', {
        'NoSeMaze'
        'MouseID'
        'Rank_Week1'
        'Rank_Week2'
        'DavidsScore_Week1_Raw'
        'DavidsScore_Week2_Raw'
        'DavidsScore_Week1_Z'
        'DavidsScore_Week2_Z'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_S8B_C_Week1_Week2_Hierarchy.csv' ...
    ) ...
);

%% Statistics table

statisticsTable = table( ...
    [
        "Figure_S8B_DavidsScoreZ_Week1_vs_Week2"
        "Figure_S8C_Rank_Week1_vs_Week2"
    ], ...
    [
        string(DSCorrType)
        string(rankCorrType)
    ], ...
    [
        rDS
        rRank
    ], ...
    [
        pDS
        pRank
    ], ...
    [
        sum(validDS)
        sum(validRank)
    ], ...
    'VariableNames', {
        'Analysis'
        'CorrelationType'
        'Correlation'
        'P'
        'N'
    } ...
);

writetable( ...
    statisticsTable, ...
    fullfile( ...
        outputDir, ...
        'Statistics_Figure_S8B_C_Week1_Week2_Hierarchy.csv' ...
    ) ...
);

%% Save complete result

result = struct;

result.group = group;
result.mouseID = mouseID;

result.rank.week1 = rank_w1;
result.rank.week2 = rank_w2;
result.rank.correlationType = rankCorrType;
result.rank.r = rRank;
result.rank.p = pRank;

result.DS.raw.week1 = DS_w1_raw;
result.DS.raw.week2 = DS_w2_raw;
result.DS.z.week1 = DS_w1_z;
result.DS.z.week2 = DS_w2_z;
result.DS.correlationType = DSCorrType;
result.DS.r = rDS;
result.DS.p = pDS;

result.sourceData = sourceData;
result.statisticsTable = statisticsTable;

result.files.NM1_week1 = ...
    makeRepoRelative(NM1_week1_file,repoRoot);

result.files.NM1_week2 = ...
    makeRepoRelative(NM1_week2_file,repoRoot);

result.files.NM2_week1 = ...
    makeRepoRelative(NM2_week1_file,repoRoot);

result.files.NM2_week2 = ...
    makeRepoRelative(NM2_week2_file,repoRoot);

save( ...
    fullfile( ...
        outputDir, ...
        'Results_Figure_S8B_C_Week1_Week2_Hierarchy.mat' ...
    ), ...
    'result' ...
);

%% Optional provenance

if ~isempty(which('docDataSrc'))

    try

        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );

    catch documentationError

        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S8B_C_Week1_Week2_Hierarchy.pdf' ...
    ), ...
    'ContentType','vector', ...
    'BackgroundColor','white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S8B_C_Week1_Week2_Hierarchy.png' ...
    ), ...
    'Resolution',300, ...
    'BackgroundColor','white' ...
);

savefig( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S8B_C_Week1_Week2_Hierarchy.fig' ...
    ) ...
);

fprintf('Figure S8B-C completed.\n');
fprintf('Results saved to:\n%s\n',outputDir);


%% ========================================================================
% Local functions
%% ========================================================================

function S = loadDSInfo(fileName)

    tmp = load(fileName,'DS_info');

    if ~isfield(tmp,'DS_info')
        error( ...
            'File %s does not contain variable DS_info.', ...
            fileName ...
        );
    end

    DS_info = tmp.DS_info;

    if ~isfield(DS_info,'DS')
        error( ...
            'DS_info in %s does not contain field DS.', ...
            fileName ...
        );
    end

    % Historical files may contain an explicit rank field. If not,
    % reconstruct the same ordinal rank from David's score:
    % rank 1 = highest David's score.
    if isfield(DS_info,'rank')

        rank = [DS_info.rank]';

    elseif isfield(DS_info,'Rank')

        rank = [DS_info.Rank]';

    else

        DS = [DS_info.DS]';

        [~,sortedIndex] = sort( ...
            DS, ...
            'descend' ...
        );

        [~,rank] = sort(sortedIndex);
        rank = rank(:);
    end

    S.rank = rank(:);
    S.DS = [DS_info.DS]';
end


function plotCorrelationPanel( ...
    ax, ...
    x, ...
    y, ...
    corrType, ...
    plotTitle, ...
    xLabel, ...
    yLabel ...
)

    hold(ax,'on');

    markerSize = 70;
    markerColor = [0.35,0.35,0.35];

    scatter( ...
        ax, ...
        x, ...
        y, ...
        markerSize, ...
        'filled', ...
        'MarkerFaceColor',markerColor, ...
        'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha',0.85 ...
    );

    valid = isfinite(x) & isfinite(y);

    xv = x(valid);
    yv = y(valid);

    [r,p] = corr( ...
        xv, ...
        yv, ...
        'Rows','complete', ...
        'Type',corrType ...
    );

    allVals = [xv;yv];

    minVal = min(allVals);
    maxVal = max(allVals);

    pad = 0.08*range(allVals);

    if pad == 0 || isnan(pad)
        pad = 1;
    end

    lims = [
        minVal - pad
        maxVal + pad
    ];

    xlim(ax,lims);
    ylim(ax,lims);

    % Identity line
    plot( ...
        ax, ...
        lims, ...
        lims, ...
        'k:', ...
        'LineWidth',1.25, ...
        'HandleVisibility','off' ...
    );

    % Linear fit retained from original plot
    if numel(xv) > 1

        coeff = polyfit(xv,yv,1);

        xx = linspace(lims(1),lims(2),100);
        yy = polyval(coeff,xx);

        plot( ...
            ax, ...
            xx, ...
            yy, ...
            'k-', ...
            'LineWidth',1.75, ...
            'HandleVisibility','off' ...
        );
    end

    % Stats annotation
    statsText = sprintf( ...
        '%s r = %.2f\np = %s\nn = %d', ...
        corrType, ...
        r, ...
        formatPValue(p), ...
        numel(xv) ...
    );

    text( ...
        ax, ...
        0.05, ...
        0.95, ...
        statsText, ...
        'Units','normalized', ...
        'VerticalAlignment','top', ...
        'HorizontalAlignment','left', ...
        'FontSize',11, ...
        'FontWeight','bold', ...
        'BackgroundColor','white', ...
        'EdgeColor',[0.75,0.75,0.75], ...
        'Margin',6 ...
    );

    title( ...
        ax, ...
        plotTitle, ...
        'FontSize',13, ...
        'FontWeight','bold' ...
    );

    xlabel(ax,xLabel,'FontSize',11);
    ylabel(ax,yLabel,'FontSize',11);

    axis(ax,'square');
    grid(ax,'on');
    box(ax,'off');

    ax.FontSize = 10;
    ax.LineWidth = 1;
    ax.TickDir = 'out';

    hold(ax,'off');
end


function pText = formatPValue(p)

    if p < 0.001
        pText = '< 0.001';
    else
        pText = sprintf('%.3f',p);
    end
end


function rel = makeRepoRelative(pathString,repoRoot)

    p = strrep(char(pathString),'\','/');
    r = strrep(char(repoRoot),'\','/');

    if startsWith(lower(p),lower(r))

        rel = extractAfter( ...
            string(p), ...
            strlength(r) ...
        );

        rel = regexprep(rel,'^[\\/]+','');

    else

        rel = string(p);
    end
end
