% panel_E_F.m
% Jonathan Reinwald
%
% Reproduces Figure 1, panels E and F.
%
% Inputs:
%   data/processed/NoSeMaze/tubetest/NoSeMaze_1/
%   data/processed/NoSeMaze/tubetest/NoSeMaze_2/
%
% Outputs:
%   results/main/Figure_1/

clearvars;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of panel_E_F.m. ' ...
        'Run the complete script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% figures/main/Figure_1 -> repository root
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository directories

srcDir = fullfile(repoRoot, 'src', 'matlab');

dataDir = fullfile( ...
    repoRoot, ...
    'data', 'processed', 'NoSeMaze', 'tubetest' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', 'main', 'Figure_1' ...
);

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s', srcDir);
end

% Temporary broad source path; this can be narrowed once src/ is finalized.
addpath(genpath(srcDir));

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Required functions

requiredFunctions = {
    'plot_hierarchy_scores_in_cohort'
    'plot_hierarchy_graph_in_cohort'
    'docDataSrc'
};

missingFunctions = requiredFunctions( ...
    ~cellfun(@(x) exist(x, 'file') == 2, requiredFunctions) ...
);

if ~isempty(missingFunctions)
    error( ...
        'Missing required MATLAB function(s):\n%s', ...
        strjoin(missingFunctions, newline) ...
    );
end

%% Input files

inputFiles = struct();

inputFiles.NoSeMaze_1 = fullfile( ...
    dataDir, ...
    'NoSeMaze_1', ...
    ['DS_info_AM1_day3to16_12mice_' ...
     'withChasingAndDoubleChasing_thresh10_td15tt2s.mat'] ...
);

inputFiles.NoSeMaze_2 = fullfile( ...
    dataDir, ...
    'NoSeMaze_2', ...
    ['DS_info_AM2_day1to14_12mice_' ...
     'withChasingAndDoubleChasing_thresh10_td15tt2s.mat'] ...
);

cohortNames = fieldnames(inputFiles);

for i = 1:numel(cohortNames)
    cohort = cohortNames{i};

    if ~isfile(inputFiles.(cohort))
        error( ...
            'Required input file not found:\n%s', ...
            inputFiles.(cohort) ...
        );
    end
end

%% Generate panels E and F

for i = 1:numel(cohortNames)

    cohort = cohortNames{i};
    blockData = load_hierarchy_block(inputFiles.(cohort));

    % ---------------------------------------------------------------------
    % Figure 1E: hierarchy scores
    % ---------------------------------------------------------------------

    [fig, sortedIDs, sortedData, sortedRanks] = ...
        plot_hierarchy_scores_in_cohort( ...
            blockData.DSzscored, ...
            blockData.ID, ...
            cohort, ...
            'DSzscored' ...
        );

    docDataSrc(fig, outputDir, scriptFile, true);

    exportgraphics( ...
        fig, ...
        fullfile(outputDir, ['Figure_1E_' cohort '.pdf']), ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'none' ...
    );

    sourceDataE = table( ...
        string(sortedIDs(:)), ...
        sortedData(:), ...
        sortedRanks(:), ...
        'VariableNames', {'ID', 'DSz', 'Rank'} ...
    );

    writetable( ...
        sourceDataE, ...
        fullfile(outputDir, ['SourceData_Figure_1E_' cohort '.csv']) ...
    );

    close(fig);

    % ---------------------------------------------------------------------
    % Figure 1F: hierarchy graph
    % ---------------------------------------------------------------------

    fig = plot_hierarchy_graph_in_cohort( ...
        blockData.match_matrix, ...
        blockData.DSzscored, ...
        blockData.ID, ...
        cohort, ...
        'DSzscored' ...
    );

    docDataSrc(fig, outputDir, scriptFile, true);

    exportgraphics( ...
        fig, ...
        fullfile(outputDir, ['Figure_1F_' cohort '.pdf']), ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'none' ...
    );

    ids = matlab.lang.makeValidName(string(blockData.ID(:)));

    sourceDataF = array2table( ...
        blockData.match_matrix, ...
        'VariableNames', cellstr(ids) ...
    );

    sourceDataF = addvars( ...
        sourceDataF, ...
        string(blockData.ID(:)), ...
        'Before', 1, ...
        'NewVariableNames', 'ID' ...
    );

    writetable( ...
        sourceDataF, ...
        fullfile(outputDir, ['SourceData_Figure_1F_' cohort '.csv']) ...
    );

    close(fig);
end

fprintf('\nFigure 1E-F outputs saved to:\n%s\n', outputDir);

%% Local functions

function S = load_hierarchy_block(matFile)

tmp = load(matFile, 'DS_info');

if ~isfield(tmp, 'DS_info')
    error('Variable DS_info not found in:\n%s', matFile);
end

S = tmp.DS_info;

[~, idx] = sort([S.DS], 'descend');
[~, rank] = sort(idx);

S.Rank = rank;
S.DSzscored = zscore([S.DS]);

end
