function create_regressors_basco_v19_reappraisal(cfg)
% CREATE_REGRESSORS_BASCO_V19_REAPPRAISAL
% Generate the trial-wise BASCO v19 event model.
%
% Conditions:
%   1. Lavender
%      120 odor onsets, each shifted by 0.7 s.
%
%   2. TP Puff
%      28 actual puff time points during pairing.
%
%   3. TP NoPuff
%      Puff-like time points for all trials without a physical puff:
%      40 pre + 12 pairing-no-puff + 40 post = 92.
%
% All events are modeled with duration 0 and without parametric modulators.

if ~isfolder(cfg.regressorsDir)
    mkdir(cfg.regressorsDir);
end

rows = cell(numel(cfg.subjectIDs), 7);

for subjectIndex = 1:numel(cfg.subjectIDs)

    subjectID = cfg.subjectIDs{subjectIndex};
    animalNumber = cfg.subjectNumbers(subjectIndex);

    protocolFile = find_subject_protocol_file_fc( ...
        cfg.protocolDir, ...
        subjectID, ...
        animalNumber ...
    );

    assert(~isempty(protocolFile) && isfile(protocolFile), ...
        'Processed protocol file not found for %s.', subjectID);

    loaded = load(protocolFile, 'events');

    assert(isfield(loaded, 'events'), ...
        'Variable "events" missing in:\n%s', protocolFile);

    events = loaded.events;

    assert(numel(events) >= 120, ...
        '%s contains only %d events; expected at least 120.', ...
        subjectID, ...
        numel(events) ...
    );

    requiredFields = {
        'fv_on_del5'
        'puff_time_del5'
        'puff_or_not'
    };

    for fieldIndex = 1:numel(requiredFields)
        assert(isfield(events, requiredFields{fieldIndex}), ...
            '%s: events lacks field "%s".', ...
            subjectID, ...
            requiredFields{fieldIndex} ...
        );
    end

    pairing = 41:80;

    puffPairing = pairing( ...
        [events(pairing).puff_or_not] == 1 ...
    );

    noPuffPairing = pairing( ...
        [events(pairing).puff_or_not] == 0 ...
    );

    assert(numel(puffPairing) == cfg.regressors.expectedPuff, ...
        '%s has %d puff trials; expected %d.', ...
        subjectID, ...
        numel(puffPairing), ...
        cfg.regressors.expectedPuff ...
    );

    assert(numel(noPuffPairing) == 12, ...
        '%s has %d pairing no-puff trials; expected 12.', ...
        subjectID, ...
        numel(noPuffPairing) ...
    );

    noPuffAll = [1:40 noPuffPairing 81:120];

    regressors = repmat( ...
        struct('name', '', 'onset', [], 'duration', 0, 'pm', []), ...
        1, ...
        3 ...
    );

    regressors(1).name = 'Lavender';
    regressors(1).onset = ...
        [events(1:120).fv_on_del5] + cfg.regressors.odorDelay;

    regressors(2).name = 'TP Puff';
    regressors(2).onset = ...
        [events(puffPairing).puff_time_del5];

    regressors(3).name = 'TP NoPuff';
    regressors(3).onset = ...
        [events(noPuffAll).puff_time_del5];

    assert(numel(regressors(1).onset) == ...
        cfg.regressors.expectedLavender);

    assert(numel(regressors(2).onset) == ...
        cfg.regressors.expectedPuff);

    assert(numel(regressors(3).onset) == ...
        cfg.regressors.expectedNoPuff);

    outputFile = fullfile( ...
        cfg.regressorsDir, ...
        [subjectID cfg.regressors.suffix] ...
    );

    save(outputFile, 'regressors');

    rows(subjectIndex, :) = {
        subjectID
        protocolFile
        outputFile
        numel(regressors(1).onset)
        numel(regressors(2).onset)
        numel(regressors(3).onset)
        strjoin(string({regressors.name}), ' | ')
    };

    fprintf('Saved BASCO v19 regressors: %s\n', outputFile);
end

manifest = cell2table( ...
    rows, ...
    'VariableNames', ...
    {'Subject_ID', 'Protocol_File', 'Regressor_File', ...
     'N_Lavender', 'N_TP_Puff', 'N_TP_NoPuff', 'Regressor_Names'} ...
);

writetable( ...
    manifest, ...
    fullfile(cfg.manifestDir, 'regressor_manifest_v19.csv') ...
);

end
