function create_correlation_matrices_basco_reappraisal(manifest, cfg)
% CREATE_CORRELATION_MATRICES_BASCO_REAPPRAISAL
% Create the 10 primary 52 × 52 Pearson FC matrices per subject.

assert(exist('wwf_covmat_hres_jr', 'file') == 2, ...
    'wwf_covmat_hres_jr.m is not available on the MATLAB path.');

assert(isfile(cfg.atlas.labels), ...
    ['FC atlas-label file not found:\n%s\n' ...
     'Supply the exact 52-ROI bilateral atlas labels or set ' ...
     'NOSEMAZE_FC_ATLAS_LABELS.'], ...
    cfg.atlas.labels ...
);

assert(isfile(cfg.atlas.nifti), ...
    ['FC atlas NIfTI not found:\n%s\n' ...
     'Supply the exact 52-ROI bilateral atlas or set ' ...
     'NOSEMAZE_FC_ATLAS_NIFTI.'], ...
    cfg.atlas.nifti ...
);

requiredDirs = {
    cfg.correlationMatrixDir
    cfg.roiDataDir
    cfg.manifestDir
};

for i = 1:numel(requiredDirs)
    if ~isfolder(requiredDirs{i})
        mkdir(requiredDirs{i});
    end
end

matrixRows = cell(numel(cfg.primaryMatrixSuffixes), 5);

for conditionIndex = 1:numel(cfg.primaryMatrixSuffixes)

    suffix = cfg.primaryMatrixSuffixes{conditionIndex};

    betaFiles = strings(height(manifest), 1);

    for subjectIndex = 1:height(manifest)

        subjectID = char(manifest.Subject_ID(subjectIndex));

        betaFile = fullfile( ...
            cfg.betaSeriesDir, ...
            sprintf( ...
                '%s_betaseries_%s_%s.nii', ...
                subjectID, ...
                cfg.version.basco, ...
                suffix ...
            ) ...
        );

        assert(isfile(betaFile), ...
            'Missing beta-series file for %s / %s:\n%s', ...
            subjectID, ...
            suffix, ...
            betaFile ...
        );

        betaFiles(subjectIndex) = string(betaFile);
    end

    % The row order is now explicitly the subject-manifest order.
    Pcur = char(betaFiles);

    [cormat, subj] = wwf_covmat_hres_jr( ...
        cfg.atlas.labels, ...
        Pcur, ...
        cfg.atlas.nifti ...
    );

    assert(numel(cormat) == height(manifest), ...
        ['wwf_covmat_hres_jr returned %d subjects for %s; ' ...
         'expected %d.'], ...
        numel(cormat), ...
        suffix, ...
        height(manifest) ...
    );

    for subjectIndex = 1:numel(cormat)

        matrixSize = size(cormat{subjectIndex});

        assert( ...
            isequal(matrixSize, ...
                [cfg.atlas.expectedROIcount cfg.atlas.expectedROIcount]), ...
            ['FC matrix %s / subject %d is %d × %d, expected %d × %d.\n' ...
             'This usually indicates that the wrong atlas/parcellation was used.'], ...
            suffix, ...
            subjectIndex, ...
            matrixSize(1), ...
            matrixSize(2), ...
            cfg.atlas.expectedROIcount, ...
            cfg.atlas.expectedROIcount ...
        );
    end

    if ~isempty(subj) && isfield(subj(1), 'roi')
        assert(numel(subj(1).roi) == cfg.atlas.expectedROIcount, ...
            ['ROI metadata contains %d ROIs; expected %d.\n' ...
             'Use the combined/bilateral 52-ROI FC atlas.'], ...
            numel(subj(1).roi), ...
            cfg.atlas.expectedROIcount ...
        );
    end

    matrixFile = fullfile( ...
        cfg.correlationMatrixDir, ...
        sprintf('cormat_%s_%s.mat', cfg.version.basco, suffix) ...
    );

    roiFile = fullfile( ...
        cfg.roiDataDir, ...
        sprintf('roidata_%s_%s.mat', cfg.version.basco, suffix) ...
    );

    subjectIDs = manifest.Subject_ID; %#ok<NASGU>
    save(matrixFile, 'cormat', 'subjectIDs', '-v7.3');
    save(roiFile, 'subj', 'subjectIDs', '-v7.3');

    matrixRows(conditionIndex, :) = {
        suffix
        matrixFile
        roiFile
        height(manifest)
        cfg.atlas.expectedROIcount
    };

    fprintf('Saved primary FC matrix set: %s\n', suffix);
end

matrixManifest = cell2table( ...
    matrixRows, ...
    'VariableNames', ...
    {'Series', 'Correlation_Matrix_File', 'ROI_Data_File', ...
     'N_Subjects', 'N_ROIs'} ...
);

writetable( ...
    matrixManifest, ...
    fullfile(cfg.manifestDir, 'correlation_matrix_manifest_reappraisal.csv') ...
);

assert(height(matrixManifest) == cfg.expectedMatrixCount, ...
    'Expected %d primary matrix sets, created %d.', ...
    cfg.expectedMatrixCount, ...
    height(matrixManifest) ...
);

end
