function create_betaseries_basco_reappraisal(manifest, cfg)
% CREATE_BETASERIES_BASCO_REAPPRAISAL Create manuscript beta-series sets.
%
% Primary outputs correspond to the 10 subject-level matrices described in
% the Supplementary Methods.
%
% Distal CR:
%   Odor1to10
%   Odor11to40
%   Odor_TPNoPuff
%   Odor_TPPuff
%   Odor81to120
%
% Proximal CR:
%   TPnoPuff1to10
%   TPnoPuff11to40
%   TPnoPuff41to80
%   TP-Puff
%   TPnoPuff81to120

assert(isfile(cfg.basco.anaobjFile), ...
    'BASCO anaobj output not found:\n%s', cfg.basco.anaobjFile);

if ~isfolder(cfg.betaSeriesDir)
    mkdir(cfg.betaSeriesDir);
end

loadedAna = load(cfg.basco.anaobjFile, 'anaobj');

assert(isfield(loadedAna, 'anaobj'), ...
    'Variable "anaobj" missing in:\n%s', cfg.basco.anaobjFile);

anaobj = loadedAna.anaobj;

assert(~isempty(anaobj), 'BASCO anaobj is empty.');

anaDef = anaobj{1,1}.Ana{1,1}.AnaDef;

conditionNames = anaDef.Cond;
conditionNBeta = cellfun(@numel, anaDef.RegCondVec);
conditionStart = cumsum([1 conditionNBeta(1:end-1)]);
conditionEnd = cumsum(conditionNBeta);

requiredConditions = {
    cfg.model.conditionLavender
    cfg.model.conditionTpNoPuff
    cfg.model.conditionTpPuff
};

missingConditions = requiredConditions( ...
    ~ismember(requiredConditions, conditionNames) ...
);

if ~isempty(missingConditions)
    error( ...
        ['Required BASCO conditions are missing from AnaDef:\n%s\n\n' ...
         'Available conditions:\n%s'], ...
        strjoin(missingConditions, newline), ...
        strjoin(conditionNames, newline) ...
    );
end

manifestRows = cell(0, 5);

for subjectIndex = 1:height(manifest)

    subjectID = char(manifest.Subject_ID(subjectIndex));
    protocolFile = char(manifest.Protocol_File(subjectIndex));

    assert(isfile(protocolFile), ...
        'Processed protocol file missing for %s:\n%s', ...
        subjectID, ...
        protocolFile ...
    );

    protocol = load(protocolFile, 'events');

    assert(isfield(protocol, 'events'), ...
        'Variable "events" missing in:\n%s', protocolFile);

    events = protocol.events;

    assert(numel(events) >= 120, ...
        '%s has fewer than 120 events.', subjectID);

    assert(isfield(events, 'puff_or_not'), ...
        '%s protocol lacks events.puff_or_not.', subjectID);

    pairingIndices = 41:80;
    pairingPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 1 ...
    );
    pairingNoPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 0 ...
    );

    betaDir = fullfile( ...
        cfg.inputDir, ...
        subjectID, ...
        ['betaseries_' cfg.version.basco] ...
    );

    betaFiles = dir(fullfile(betaDir, 'beta_*.nii'));
    betaFiles = betaFiles(~[betaFiles.isdir]);

    assert(~isempty(betaFiles), ...
        'No BASCO beta images found for %s in:\n%s', subjectID, betaDir);

    % Sort by numeric beta index rather than filesystem order.
    betaNumbers = nan(numel(betaFiles), 1);

    for fileIndex = 1:numel(betaFiles)
        token = regexp( ...
            betaFiles(fileIndex).name, ...
            '^beta_(\d+)\.nii$', ...
            'tokens', ...
            'once' ...
        );

        assert(~isempty(token), ...
            'Unexpected beta filename: %s', betaFiles(fileIndex).name);

        betaNumbers(fileIndex) = str2double(token{1});
    end

    [~, order] = sort(betaNumbers);
    betaFiles = betaFiles(order);

    betaPaths = strings(numel(betaFiles), 1);

    for fileIndex = 1:numel(betaFiles)
        betaPaths(fileIndex) = string( ...
            fullfile(betaFiles(fileIndex).folder, betaFiles(fileIndex).name) ...
        );
    end

    for conditionIndex = 1:numel(conditionNames)

        conditionName = conditionNames{conditionIndex};
        idx = conditionStart(conditionIndex):conditionEnd(conditionIndex);

        if cfg.writeGenericConditionSeries
            safeName = strrep(conditionName, ' ', '-');
            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, ...
                idx, ...
                cfg, ...
                subjectID, ...
                safeName, ...
                'generic' ...
            ); %#ok<AGROW>
        end

        if strcmp(conditionName, cfg.model.conditionLavender)

            assert(numel(idx) >= 120, ...
                'Lavender condition for %s has fewer than 120 betas.', ...
                subjectID);

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx(1:10), cfg, subjectID, ...
                'Odor1to10', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx(11:40), cfg, subjectID, ...
                'Odor11to40', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx(pairingNoPuff), cfg, subjectID, ...
                'Odor_TPNoPuff', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx(pairingPuff), cfg, subjectID, ...
                'Odor_TPPuff', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx(81:120), cfg, subjectID, ...
                'Odor81to120', 'primary' ...
            ); %#ok<AGROW>

            if cfg.writeLegacyConvenienceSeries
                manifestRows(end+1, :) = write_series_record( ...
                    betaPaths, idx(1:40), cfg, subjectID, ...
                    'Odor1to40', 'legacy_optional' ...
                ); %#ok<AGROW>

                manifestRows(end+1, :) = write_series_record( ...
                    betaPaths, idx(41:80), cfg, subjectID, ...
                    'Odor41to80', 'legacy_optional' ...
                ); %#ok<AGROW>

                manifestRows(end+1, :) = write_series_record( ...
                    betaPaths, idx(81:110), cfg, subjectID, ...
                    'Odor81to110', 'legacy_optional' ...
                ); %#ok<AGROW>
            end

        elseif strcmp(conditionName, cfg.model.conditionTpNoPuff)

            nNoPuff = numel(pairingNoPuff);
            expectedCount = 40 + nNoPuff + 40;

            assert(numel(idx) >= expectedCount, ...
                ['TP NoPuff condition for %s contains %d betas; ' ...
                 'expected at least %d (=40 pre + %d pairing-no-puff + 40 test).'], ...
                subjectID, ...
                numel(idx), ...
                expectedCount, ...
                nNoPuff ...
            );

            preIdx = idx(1:40);
            pairingIdx = idx(41:(40+nNoPuff));
            testIdx = idx((41+nNoPuff):(40+nNoPuff+40));

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, preIdx(1:10), cfg, subjectID, ...
                'TPnoPuff1to10', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, preIdx(11:40), cfg, subjectID, ...
                'TPnoPuff11to40', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, pairingIdx, cfg, subjectID, ...
                'TPnoPuff41to80', 'primary' ...
            ); %#ok<AGROW>

            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, testIdx, cfg, subjectID, ...
                'TPnoPuff81to120', 'primary' ...
            ); %#ok<AGROW>

            if cfg.writeLegacyConvenienceSeries
                manifestRows(end+1, :) = write_series_record( ...
                    betaPaths, preIdx, cfg, subjectID, ...
                    'TPnoPuff1to40', 'legacy_optional' ...
                ); %#ok<AGROW>

                manifestRows(end+1, :) = write_series_record( ...
                    betaPaths, testIdx(1:min(30, numel(testIdx))), ...
                    cfg, subjectID, ...
                    'TPnoPuff81to110', 'legacy_optional' ...
                ); %#ok<AGROW>
            end

        elseif strcmp(conditionName, cfg.model.conditionTpPuff)

            % The full TP Puff condition is the proximal-CR
            % pairing-with-puff beta series.
            manifestRows(end+1, :) = write_series_record( ...
                betaPaths, idx, cfg, subjectID, ...
                'TP-Puff', 'primary' ...
            ); %#ok<AGROW>
        end
    end

    % Validate exactly the manuscript-required primary suffixes.
    for matrixIndex = 1:numel(cfg.primaryMatrixSuffixes)

        expectedFile = beta_output_file( ...
            cfg, ...
            subjectID, ...
            cfg.primaryMatrixSuffixes{matrixIndex} ...
        );

        assert(isfile(expectedFile), ...
            'Missing primary beta-series output for %s:\n%s', ...
            subjectID, ...
            expectedFile ...
        );
    end

    fprintf('Created primary BASCO beta series for %s.\n', subjectID);
end

betaManifest = cell2table( ...
    manifestRows, ...
    'VariableNames', ...
    {'Subject_ID', 'Series', 'File', 'N_Betas', 'Role'} ...
);

writetable( ...
    betaManifest, ...
    fullfile(cfg.manifestDir, 'betaseries_manifest_reappraisal.csv') ...
);

fprintf('\nCreated %d primary beta-series types per subject.\n', ...
    cfg.expectedMatrixCount);

end


function row = write_series_record( ...
    betaPaths, ...
    betaIndices, ...
    cfg, ...
    subjectID, ...
    suffix, ...
    role ...
)

outFile = beta_output_file(cfg, subjectID, suffix);

write_beta4d_fc(betaPaths, betaIndices, outFile);

row = {
    subjectID
    suffix
    outFile
    numel(betaIndices)
    role
};

row = reshape(row, 1, []);

end


function outFile = beta_output_file(cfg, subjectID, suffix)

outFile = fullfile( ...
    cfg.betaSeriesDir, ...
    sprintf( ...
        '%s_betaseries_%s_%s.nii', ...
        subjectID, ...
        cfg.version.basco, ...
        suffix ...
    ) ...
);

end


function write_beta4d_fc(betaPaths, betaIndices, outFile)

if isempty(betaIndices)
    error('Cannot create empty beta series:\n%s', outFile);
end

if isfile(outFile)
    delete(outFile);
end

for outputVolume = 1:numel(betaIndices)

    betaIndex = betaIndices(outputVolume);

    assert(betaIndex >= 1 && betaIndex <= numel(betaPaths), ...
        'Beta index %d is outside available range 1:%d.', ...
        betaIndex, ...
        numel(betaPaths) ...
    );

    V = spm_vol(char(betaPaths(betaIndex)));
    Vout = V;
    Vout.fname = outFile;
    Vout.n(1) = outputVolume;

    spm_write_vol(Vout, spm_read_vols(V));
end

end
