function validate_primary_fc_outputs(manifest, cfg)
% VALIDATE_PRIMARY_FC_OUTPUTS Validate 10 primary beta-series/matrix sets.

fprintf('\nValidating primary BASCO FC outputs...\n');

assert(height(manifest) == numel(cfg.subjectIDs), ...
    'Manifest contains %d subjects; expected %d.', ...
    height(manifest), ...
    numel(cfg.subjectIDs) ...
);

for conditionIndex = 1:numel(cfg.primaryMatrixSuffixes)

    suffix = cfg.primaryMatrixSuffixes{conditionIndex};

    for subjectIndex = 1:height(manifest)

        subjectID = char(manifest.Subject_ID(subjectIndex));

        betaFile = fullfile( ...
            cfg.betaSeriesDir, ...
            sprintf( ...
                '%s_betaseries_%s_%s.nii', ...
                subjectID, ...
                cfg.version.basco, ...
                suffix ...
            ) ...
        );

        assert(isfile(betaFile), ...
            'Missing beta series:\n%s', betaFile);
    end

    matrixFile = fullfile( ...
        cfg.correlationMatrixDir, ...
        sprintf('cormat_%s_%s.mat', cfg.version.basco, suffix) ...
    );

    assert(isfile(matrixFile), ...
        'Missing correlation matrix:\n%s', matrixFile);

    loaded = load(matrixFile, 'cormat');

    assert(isfield(loaded, 'cormat'), ...
        'Variable "cormat" missing in:\n%s', matrixFile);

    assert(numel(loaded.cormat) == height(manifest), ...
        '%s contains %d matrices; expected %d.', ...
        matrixFile, ...
        numel(loaded.cormat), ...
        height(manifest) ...
    );
end

fprintf('Primary FC output validation passed: %d subjects × %d matrix types.\n', ...
    height(manifest), ...
    cfg.expectedMatrixCount ...
);

end
