% panel_B_HRF_comparison.m
% Jonathan Reinwald
%
% Reviewer-facing HRF comparison for Supplementary Figure S3B.
%
% Compares:
%   1. study-specific mouse HRF:
%      custom animal spm_hrf.m used in the original analysis
%
%   2. canonical human HRF:
%      standard SPM12 spm_hrf.m
%
% Both HRFs are evaluated at dt = 0.1 s. Each spm_hrf implementation is
% evaluated in isolation to prevent function shadowing.
%
% Expected repository structure:
%
% NoSeMaze-Connectomics/
% ├── figures/supplement/Figure_S3/
% │   └── panel_B_HRF_comparison.m
% │
% ├── src/matlab/
% │   ├── helpers/hrf/
% │   │   ├── mouse/
% │   │   │   └── spm_hrf.m
% │   │   ├── human/
% │   │   │   └── spm_hrf.m
% │   │   └── common/
% │   │       └── spm_Gpdf.m
% │   └── helpers/
% │       └── docDataSrc.m     (optional)
% │
% └── results/supplement/Figure_S3/Figure_S3B/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the script location. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repo/figures/supplement/Figure_S3/panel_B_HRF_comparison.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

matlabDir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab' ...
);

mouseHrfDir = fullfile( ...
    matlabDir, ...
    'helpers',...
    'hrf', ...
    'mouse' ...
);

humanHrfDir = fullfile( ...
    matlabDir, ...    
    'helpers',...
    'hrf', ...
    'human' ...
);

commonHrfDir = fullfile( ...
    matlabDir, ...
    'helpers',...
    'hrf', ...
    'common' ...
);

helpersDir = fullfile( ...
    matlabDir, ...
    'helpers' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results', ...
    'supplement', ...
    'Figure_S3', ...
    'Figure_S3B' ...
);

%% Add only general helpers
%
% Do NOT recursively add src/matlab/ here because that would place both
% mouse/hrf/spm_hrf.m and human/hrf/spm_hrf.m on the MATLAB path at once.
% Each HRF implementation is added temporarily and evaluated separately.

if isfolder(helpersDir)
    addpath(genpath(helpersDir));
end

%% Required HRF files

mouseHrfFile = fullfile( ...
    mouseHrfDir, ...
    'spm_hrf.m' ...
);

humanHrfFile = fullfile( ...
    humanHrfDir, ...
    'spm_hrf.m' ...
);

spmGpdfFile = fullfile( ...
    commonHrfDir, ...
    'spm_Gpdf.m' ...
);

requiredFiles = {
    mouseHrfFile
    humanHrfFile
    spmGpdfFile
};

missingFiles = requiredFiles( ...
    ~cellfun(@isfile, requiredFiles) ...
);

if ~isempty(missingFiles)
    error( ...
        'Required HRF files are missing:\n\n%s', ...
        strjoin(missingFiles, newline) ...
    );
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Analysis settings

dt = 0.1;
timeSeconds = (0:dt:32)';

mouseColor = [0.5, 0, 0];
humanColor = [0, 0, 0.5];

lineWidth = 3;

%% Evaluate mouse and human HRFs separately

mouseHrf = evaluateHrfFromFolder( ...
    mouseHrfDir, ...
    commonHrfDir, ...
    dt ...
);

humanHrf = evaluateHrfFromFolder( ...
    humanHrfDir, ...
    commonHrfDir, ...
    dt ...
);

mouseHrf = mouseHrf(:);
humanHrf = humanHrf(:);

%% Validate output lengths

if numel(mouseHrf) ~= numel(timeSeconds)
    error([ ...
        'Mouse HRF contains %d samples, but %d were expected for ' ...
        '0:0.1:32 s.' ...
    ], ...
        numel(mouseHrf), ...
        numel(timeSeconds) ...
    );
end

if numel(humanHrf) ~= numel(timeSeconds)
    error([ ...
        'Human HRF contains %d samples, but %d were expected for ' ...
        '0:0.1:32 s.' ...
    ], ...
        numel(humanHrf), ...
        numel(timeSeconds) ...
    );
end

%% Peak information for transparent reporting

[mousePeakValue, mousePeakIndex] = max(mouseHrf);
[humanPeakValue, humanPeakIndex] = max(humanHrf);

mousePeakTime = timeSeconds(mousePeakIndex);
humanPeakTime = timeSeconds(humanPeakIndex);

%% Create Figure S3B

fig = figure( ...
    'Name', ...
    'Figure S3B: mouse and human HRF comparison', ...
    'Visible', ...
    'on', ...
    'Color', ...
    'white', ...
    'Position', ...
    [100, 100, 650, 500] ...
);

ax = axes(fig);
hold(ax, 'on');

mouseLine = plot( ...
    ax, ...
    timeSeconds, ...
    mouseHrf, ...
    'LineWidth', ...
    lineWidth, ...
    'Color', ...
    mouseColor ...
);

humanLine = plot( ...
    ax, ...
    timeSeconds, ...
    humanHrf, ...
    '--', ...
    'LineWidth', ...
    lineWidth, ...
    'Color', ...
    humanColor ...
);

box(ax, 'off');

% Retain historical displayed interval.
ax.XLim = [0, 15];
ax.XTick = 0:2:14;

xlabel(ax, 'Time [s]');
ylabel(ax, 'A.U.');

ax.FontSize = 14;
ax.LineWidth = 2;

legend( ...
    ax, ...
    [mouseLine, humanLine], ...
    {'mouse HRF', 'human HRF'}, ...
    'Location', ...
    'best', ...
    'Box', ...
    'off' ...
);

title( ...
    ax, ...
    'Figure S3B: HRF comparison', ...
    'Interpreter', ...
    'none' ...
);

%% Export source data

sourceData = table( ...
    timeSeconds, ...
    mouseHrf, ...
    humanHrf, ...
    'VariableNames', {
        'Time_s'
        'Mouse_HRF'
        'Human_HRF'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_S3B_HRF_comparison.csv' ...
    ) ...
);

%% Export peak summary

peakSummary = table( ...
    ["mouse"; "human"], ...
    [mousePeakTime; humanPeakTime], ...
    [mousePeakValue; humanPeakValue], ...
    'VariableNames', {
        'HRF'
        'PeakTime_s'
        'PeakValue'
    } ...
);

writetable( ...
    peakSummary, ...
    fullfile( ...
        outputDir, ...
        'Statistics_Figure_S3B_HRF_peak_summary.csv' ...
    ) ...
);

%% Metadata

metadata = table( ...
    string('Figure S3B'), ...
    dt, ...
    string('0:0.1:32'), ...
    string('0-15 s'), ...
    string(mouseHrfFile), ...
    string(humanHrfFile), ...
    string(spmGpdfFile), ...
    'VariableNames', {
        'Figure'
        'SamplingInterval_s'
        'ComputedTimeRange_s'
        'DisplayedTimeRange'
        'MouseHRF_File'
        'HumanHRF_File'
        'SPM_Gpdf_File'
    } ...
);

writetable( ...
    metadata, ...
    fullfile( ...
        outputDir, ...
        'AnalysisMetadata_Figure_S3B_HRF_comparison.csv' ...
    ) ...
);

%% Save complete results

save( ...
    fullfile( ...
        outputDir, ...
        'Figure_S3B_HRF_comparison_complete_results.mat' ...
    ), ...
    'timeSeconds', ...
    'mouseHrf', ...
    'humanHrf', ...
    'mousePeakTime', ...
    'humanPeakTime', ...
    'mousePeakValue', ...
    'humanPeakValue', ...
    'dt', ...
    'mouseHrfFile', ...
    'humanHrfFile', ...
    'spmGpdfFile' ...
);

%% Optional source-script documentation

if ~isempty(which('docDataSrc'))

    try
        docDataSrc( ...
            fig, ...
            outputDir, ...
            scriptFile, ...
            true ...
        );

    catch documentationError

        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export figure

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S3B_HRF_comparison.pdf' ...
    ), ...
    'ContentType', ...
    'vector', ...
    'BackgroundColor', ...
    'white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S3B_HRF_comparison.png' ...
    ), ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white' ...
);

savefig( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S3B_HRF_comparison.fig' ...
    ) ...
);

fprintf('\nCompleted Supplementary Figure S3B.\n');
fprintf('Mouse HRF peak: %.2f s\n', mousePeakTime);
fprintf('Human HRF peak: %.2f s\n', humanPeakTime);
fprintf('Outputs saved to:\n%s\n', outputDir);

%% ========================================================================
% Local function
%% ========================================================================

function hrf = evaluateHrfFromFolder( ...
    hrfFolder, ...
    commonFolder, ...
    dt ...
)
% Evaluate the spm_hrf.m found in hrfFolder while preventing conflicts with
% other spm_hrf implementations on the MATLAB path.

    originalPath = path;

    cleanupObject = onCleanup( ...
        @() path(originalPath) ...
    ); %#ok<NASGU>

    addpath(commonFolder, '-begin');
    addpath(hrfFolder, '-begin');

    clear spm_hrf spm_Gpdf;

    resolvedHrf = which('spm_hrf');
    resolvedGpdf = which('spm_Gpdf');

    expectedHrf = fullfile( ...
        hrfFolder, ...
        'spm_hrf.m' ...
    );

    expectedGpdf = fullfile( ...
        commonFolder, ...
        'spm_Gpdf.m' ...
    );

    if ~strcmpi(resolvedHrf, expectedHrf)
        error([ ...
            'MATLAB resolved spm_hrf to:\n%s\n\n' ...
            'Expected:\n%s' ...
        ], ...
            resolvedHrf, ...
            expectedHrf ...
        );
    end

    if ~strcmpi(resolvedGpdf, expectedGpdf)
        error([ ...
            'MATLAB resolved spm_Gpdf to:\n%s\n\n' ...
            'Expected:\n%s' ...
        ], ...
            resolvedGpdf, ...
            expectedGpdf ...
        );
    end

    hrf = spm_hrf(dt);

    clear spm_hrf spm_Gpdf;
end
