% figure_S18_added_connections_by_threshold.m
% Jonathan Reinwald
%
% Supplementary Figure S18
%
% Distribution of functional-connectivity values added when increasing
% network density in 5% steps from 10% to 50%.
%
% PRE  = TPnoPuff trials 11-40
% TEST = TPnoPuff trials 81-120
%
% Conditioning and control cohorts are shown together for each
% threshold interval.
%
% This script reuses the graph-structure files already used for Figure 4A.
% No raw cormat files are required.
%
% Expected repository inputs:
%
% data/processed/fMRI/Figure_4/
% ├── conditioning/
% │   ├── gstruc_TPnoPuff11to40_p.mat
% │   └── gstruc_TPnoPuff81to120_p.mat
% └── control/
%     ├── gstruc_TPnoPuff11to40_p.mat
%     └── gstruc_TPnoPuff81to120_p.mat
%
% Optional helper:
%   src/matlab/docDataSrc.m
%
% Outputs:
%   results/supplement/Figure_S18/
%
% -------------------------------------------------------------------------

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/supplement/Figure_S18/figure_S18_added_connections_by_threshold.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile(repoRoot,'src','matlab');

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s',srcDir);
end

addpath(genpath(srcDir));

conditioningDir = fullfile( ...
    repoRoot,'data','processed','fMRI', ...
    'Figure_4','conditioning' ...
);

controlDir = fullfile( ...
    repoRoot,'data','processed','fMRI', ...
    'Figure_4','control' ...
);

outputDir = fullfile( ...
    repoRoot,'results','supplement','Figure_S18' ...
);

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Analysis settings

blockPre  = 'TPnoPuff11to40';
blockTest = 'TPnoPuff81to120';

% Original threshold indices:
%   ix = 1,6,11,...,41
% corresponding to displayed densities:
%   10,15,20,...,50 %
thresholdIndices = 1:5:41;
thresholdLabels = thresholdIndices + 9;

binWidth = 0.01;

% Colors retained exactly from the original script
colors = {
    [1,0,0]
    [0,1,0]
    [1,0,1]
    [0,1,1]
    [0,0,1]
    [.5,0,0]
    [0,.5,0]
    [.5,0,.5]
    [0,.5,.5]
    [0,0,.5]
};

% Main plotting colors retained from original script
taskTestColor    = [0,160/255,227/255];
taskPreColor     = [204/255,51/255,204/255];
controlTestColor = taskTestColor .* 0.5;
controlPreColor  = taskPreColor .* 0.5;

%% Input files

conditioningPreFile = fullfile( ...
    conditioningDir, ...
    ['gstruc_' blockPre '_p.mat'] ...
);

conditioningTestFile = fullfile( ...
    conditioningDir, ...
    ['gstruc_' blockTest '_p.mat'] ...
);

controlPreFile = fullfile( ...
    controlDir, ...
    ['gstruc_' blockPre '_p.mat'] ...
);

controlTestFile = fullfile( ...
    controlDir, ...
    ['gstruc_' blockTest '_p.mat'] ...
);

requiredFiles = {
    conditioningPreFile
    conditioningTestFile
    controlPreFile
    controlTestFile
};

missingFiles = requiredFiles(~cellfun(@isfile,requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required files are missing:\n\n%s', ...
        strjoin(missingFiles,newline) ...
    );
end

%% Load graph-structure data

conditioningPreLoaded  = load(conditioningPreFile,'gstruc');
conditioningTestLoaded = load(conditioningTestFile,'gstruc');
controlPreLoaded       = load(controlPreFile,'gstruc');
controlTestLoaded      = load(controlTestFile,'gstruc');

gConditioningPre  = conditioningPreLoaded.gstruc;
gConditioningTest = conditioningTestLoaded.gstruc;
gControlPre       = controlPreLoaded.gstruc;
gControlTest      = controlTestLoaded.gstruc;

%% Input checks

allStructs = {
    gConditioningPre
    gConditioningTest
    gControlPre
    gControlTest
};

for i = 1:numel(allStructs)

    current = allStructs{i};

    if size(current,1) < max(thresholdIndices)
        error( ...
            'Input %d contains only %d threshold levels; index %d is required.', ...
            i, ...
            size(current,1), ...
            max(thresholdIndices) ...
        );
    end

    if ~isfield(current,'o_CIJ_thresh')
        error('Input %d does not contain field o_CIJ_thresh.',i);
    end
end

nConditioningPre = size(gConditioningPre,2);
nConditioningTest = size(gConditioningTest,2);
nControlPre = size(gControlPre,2);
nControlTest = size(gControlTest,2);

if nConditioningPre ~= nConditioningTest
    error( ...
        'Conditioning PRE/TEST animal counts differ: %d vs %d.', ...
        nConditioningPre,nConditioningTest ...
    );
end

if nControlPre ~= nControlTest
    error( ...
        'Control PRE/TEST animal counts differ: %d vs %d.', ...
        nControlPre,nControlTest ...
    );
end

fprintf('\nSupplementary Figure S18 input check\n');
fprintf('Conditioning PRE:  %d animals\n',nConditioningPre);
fprintf('Conditioning TEST: %d animals\n',nConditioningTest);
fprintf('Control PRE:       %d animals\n',nControlPre);
fprintf('Control TEST:      %d animals\n',nControlTest);
fprintf('Thresholds:        %s %%\n\n', ...
    strjoin(string(thresholdLabels),', '));

%% Collect all FC values at each threshold

conditioningTestValues = collectThresholdValues( ...
    gConditioningTest,thresholdIndices ...
);

conditioningPreValues = collectThresholdValues( ...
    gConditioningPre,thresholdIndices ...
);

controlTestValues = collectThresholdValues( ...
    gControlTest,thresholdIndices ...
);

controlPreValues = collectThresholdValues( ...
    gControlPre,thresholdIndices ...
);

%% Temporary histogram figure
%
% Retains the original MATLAB histogram calculation with BinWidth = 0.01.
% The histogram handles are then used to calculate the number of
% connections added between successive density thresholds.

tempFig = figure( ...
    'Name','Figure S18 histogram calculation', ...
    'Visible','off', ...
    'Color','white' ...
);

%% Conditioning

subplot(2,1,1);
hold on;

hConditioningTest = gobjects(1,numel(thresholdIndices));
hConditioningPre  = gobjects(1,numel(thresholdIndices));

for k = 1:numel(thresholdIndices)

    hConditioningTest(k) = histogram( ...
        conditioningTestValues{k}, ...
        'BinWidth',binWidth, ...
        'EdgeColor',colors{k}, ...
        'LineStyle','-', ...
        'LineWidth',1, ...
        'DisplayStyle','stairs' ...
    );
end

for k = 1:numel(thresholdIndices)

    hConditioningPre(k) = histogram( ...
        conditioningPreValues{k}, ...
        'BinWidth',binWidth, ...
        'EdgeColor',colors{k}, ...
        'LineStyle',':', ...
        'LineWidth',1, ...
        'DisplayStyle','stairs' ...
    );
end

title('Conditioning');

%% Control

subplot(2,1,2);
hold on;

hControlTest = gobjects(1,numel(thresholdIndices));
hControlPre  = gobjects(1,numel(thresholdIndices));

for k = 1:numel(thresholdIndices)

    hControlTest(k) = histogram( ...
        controlTestValues{k}, ...
        'BinWidth',binWidth, ...
        'EdgeColor',colors{k}, ...
        'LineStyle','-', ...
        'LineWidth',1, ...
        'DisplayStyle','stairs' ...
    );
end

for k = 1:numel(thresholdIndices)

    hControlPre(k) = histogram( ...
        controlPreValues{k}, ...
        'BinWidth',binWidth, ...
        'EdgeColor',colors{k}, ...
        'LineStyle',':', ...
        'LineWidth',1, ...
        'DisplayStyle','stairs' ...
    );
end

title('Control');

%% Validate histogram edges
%
% The original analysis subtracts histogram bin counts at adjacent
% thresholds. This requires identical bin edges. Explicitly verify this
% before performing the subtraction.

validateHistogramEdges(hConditioningTest,'conditioning TEST');
validateHistogramEdges(hConditioningPre,'conditioning PRE');
validateHistogramEdges(hControlTest,'control TEST');
validateHistogramEdges(hControlPre,'control PRE');

% Histograms only need identical bin edges across thresholds WITHIN
% each series. The original script allowed conditioning/control and
% PRE/TEST series to have different edge ranges.
conditioningTestEdges = hConditioningTest(1).BinEdges;
conditioningPreEdges  = hConditioningPre(1).BinEdges;
controlTestEdges      = hControlTest(1).BinEdges;
controlPreEdges       = hControlPre(1).BinEdges;

% Store counts before closing the temporary histogram figure.
conditioningTestCounts = getHistogramCounts(hConditioningTest);
conditioningPreCounts  = getHistogramCounts(hConditioningPre);
controlTestCounts      = getHistogramCounts(hControlTest);
controlPreCounts       = getHistogramCounts(hControlPre);

%% Calculate added connections between successive thresholds

nIntervals = numel(thresholdIndices) - 1;

addedConditioningTest = cell(1,nIntervals);
addedConditioningPre  = cell(1,nIntervals);
addedControlTest      = cell(1,nIntervals);
addedControlPre       = cell(1,nIntervals);

for intervalIndex = 1:nIntervals

    addedConditioningTest{intervalIndex} = ...
        conditioningTestCounts(:,intervalIndex+1)' - ...
        conditioningTestCounts(:,intervalIndex)';

    addedConditioningPre{intervalIndex} = ...
        conditioningPreCounts(:,intervalIndex+1)' - ...
        conditioningPreCounts(:,intervalIndex)';

    addedControlTest{intervalIndex} = ...
        controlTestCounts(:,intervalIndex+1)' - ...
        controlTestCounts(:,intervalIndex)';

    addedControlPre{intervalIndex} = ...
        controlPreCounts(:,intervalIndex+1)' - ...
        controlPreCounts(:,intervalIndex)';

    % Retain original behavior: negative count differences are set to zero
    addedConditioningTest{intervalIndex}( ...
        addedConditioningTest{intervalIndex} < 0) = 0;

    addedConditioningPre{intervalIndex}( ...
        addedConditioningPre{intervalIndex} < 0) = 0;

    addedControlTest{intervalIndex}( ...
        addedControlTest{intervalIndex} < 0) = 0;

    addedControlPre{intervalIndex}( ...
        addedControlPre{intervalIndex} < 0) = 0;
end

close(tempFig);

%% Main Figure S18

fig = figure( ...
    'Name','Supplementary Figure S18', ...
    'Visible','on', ...
    'Color','white', ...
    'Units','Normalized', ...
    'OuterPosition',[0,0.04,0.35,1] ...
);

for intervalIndex = 1:nIntervals

    subplot(4,2,intervalIndex);
    hold on;

    % Conditioning TEST
    histogram( ...
        'BinCounts',addedConditioningTest{intervalIndex}, ...
        'BinEdges',conditioningTestEdges, ...
        'EdgeColor','none', ...
        'FaceColor',taskTestColor, ...
        'FaceAlpha',0.1, ...
        'LineWidth',1.5 ...
    );

    histogram( ...
        'BinCounts',addedConditioningTest{intervalIndex}, ...
        'BinEdges',conditioningTestEdges, ...
        'EdgeColor',taskTestColor, ...
        'LineWidth',1.5, ...
        'DisplayStyle','stairs' ...
    );

    % Conditioning PRE
    histogram( ...
        'BinCounts',addedConditioningPre{intervalIndex}, ...
        'BinEdges',conditioningPreEdges, ...
        'EdgeColor','none', ...
        'FaceColor',taskPreColor, ...
        'FaceAlpha',0.1, ...
        'LineWidth',1.5 ...
    );

    histogram( ...
        'BinCounts',addedConditioningPre{intervalIndex}, ...
        'BinEdges',conditioningPreEdges, ...
        'EdgeColor',taskPreColor, ...
        'LineWidth',1.5, ...
        'DisplayStyle','stairs' ...
    );

    % Control TEST
    histogram( ...
        'BinCounts',addedControlTest{intervalIndex}, ...
        'BinEdges',controlTestEdges, ...
        'EdgeColor','none', ...
        'FaceColor',controlTestColor, ...
        'FaceAlpha',0.1, ...
        'LineWidth',1.5, ...
        'LineStyle',':' ...
    );

    histogram( ...
        'BinCounts',addedControlTest{intervalIndex}, ...
        'BinEdges',controlTestEdges, ...
        'EdgeColor',controlTestColor, ...
        'LineWidth',1.5, ...
        'LineStyle','-.', ...
        'DisplayStyle','stairs' ...
    );

    % Control PRE
    histogram( ...
        'BinCounts',addedControlPre{intervalIndex}, ...
        'BinEdges',controlPreEdges, ...
        'EdgeColor','none', ...
        'FaceColor',controlPreColor, ...
        'FaceAlpha',0.1, ...
        'LineWidth',1.5, ...
        'LineStyle',':' ...
    );

    histogram( ...
        'BinCounts',addedControlPre{intervalIndex}, ...
        'BinEdges',controlPreEdges, ...
        'EdgeColor',controlPreColor, ...
        'LineWidth',1.5, ...
        'LineStyle','-.', ...
        'DisplayStyle','stairs' ...
    );

    ax = gca;

    ax.YLim = [0,600];
    ax.XLim = [0,0.8];

    ax.XTick = 0:0.1:0.8;
    ax.XTickLabel = 0:0.1:0.8;

    ax.LineWidth = 1.2;
    ax.FontSize = 8;

    ylabel(ax,{'count','(added connections)'});
    xlabel(ax,{'FC','(added connections)'});

    title( ...
        sprintf( ...
            'Added connections: %d%% to %d%% sparsity thresh.', ...
            thresholdLabels(intervalIndex), ...
            thresholdLabels(intervalIndex+1) ...
        ), ...
        'FontSize',8 ...
    );
end

%% Source data: original threshold histograms

writeHistogramSourceData( ...
    conditioningTestEdges, ...
    conditioningTestCounts, ...
    thresholdLabels, ...
    fullfile( ...
        outputDir, ...
        ['SourceData_Conditioning_' blockTest '.csv'] ...
    ) ...
);

writeHistogramSourceData( ...
    conditioningPreEdges, ...
    conditioningPreCounts, ...
    thresholdLabels, ...
    fullfile( ...
        outputDir, ...
        ['SourceData_Conditioning_' blockPre '.csv'] ...
    ) ...
);

writeHistogramSourceData( ...
    controlTestEdges, ...
    controlTestCounts, ...
    thresholdLabels, ...
    fullfile( ...
        outputDir, ...
        ['SourceData_Control_' blockTest '.csv'] ...
    ) ...
);

writeHistogramSourceData( ...
    controlPreEdges, ...
    controlPreCounts, ...
    thresholdLabels, ...
    fullfile( ...
        outputDir, ...
        ['SourceData_Control_' blockPre '.csv'] ...
    ) ...
);

%% Source data: added-connection distributions
%
% Each series keeps its own histogram edges, matching the original script.

for intervalIndex = 1:nIntervals

    writeAddedConnectionsSourceData( ...
        conditioningPreEdges, ...
        addedConditioningPre{intervalIndex}, ...
        fullfile(outputDir,sprintf( ...
            'SourceData_addedConnections_Conditioning_PRE_%dto%d.csv', ...
            thresholdLabels(intervalIndex),thresholdLabels(intervalIndex+1))) ...
    );

    writeAddedConnectionsSourceData( ...
        conditioningTestEdges, ...
        addedConditioningTest{intervalIndex}, ...
        fullfile(outputDir,sprintf( ...
            'SourceData_addedConnections_Conditioning_TEST_%dto%d.csv', ...
            thresholdLabels(intervalIndex),thresholdLabels(intervalIndex+1))) ...
    );

    writeAddedConnectionsSourceData( ...
        controlPreEdges, ...
        addedControlPre{intervalIndex}, ...
        fullfile(outputDir,sprintf( ...
            'SourceData_addedConnections_Control_PRE_%dto%d.csv', ...
            thresholdLabels(intervalIndex),thresholdLabels(intervalIndex+1))) ...
    );

    writeAddedConnectionsSourceData( ...
        controlTestEdges, ...
        addedControlTest{intervalIndex}, ...
        fullfile(outputDir,sprintf( ...
            'SourceData_addedConnections_Control_TEST_%dto%d.csv', ...
            thresholdLabels(intervalIndex),thresholdLabels(intervalIndex+1))) ...
    );
end

%% Analysis metadata

metadata = table( ...
    string('Figure S18'), ...
    string(blockPre), ...
    string(blockTest), ...
    string(strjoin(string(thresholdLabels),',')), ...
    binWidth, ...
    nConditioningPre, ...
    nControlPre, ...
    string(makeRepoRelative(conditioningPreFile,repoRoot)), ...
    string(makeRepoRelative(conditioningTestFile,repoRoot)), ...
    string(makeRepoRelative(controlPreFile,repoRoot)), ...
    string(makeRepoRelative(controlTestFile,repoRoot)), ...
    'VariableNames', { ...
        'Figure'
        'PRE'
        'TEST'
        'DensityThresholdsPercent'
        'HistogramBinWidth'
        'N_Conditioning'
        'N_Control'
        'Conditioning_Pre_File'
        'Conditioning_Test_File'
        'Control_Pre_File'
        'Control_Test_File'
    } ...
);

writetable( ...
    metadata, ...
    fullfile(outputDir,'AnalysisMetadata_Figure_S18.csv') ...
);

result = struct;

result.thresholdIndices = thresholdIndices;
result.thresholdLabels = thresholdLabels;
result.binWidth = binWidth;

result.conditioning.pre.edges = conditioningPreEdges;
result.conditioning.pre.counts = conditioningPreCounts;
result.conditioning.pre.added = addedConditioningPre;

result.conditioning.test.edges = conditioningTestEdges;
result.conditioning.test.counts = conditioningTestCounts;
result.conditioning.test.added = addedConditioningTest;

result.control.pre.edges = controlPreEdges;
result.control.pre.counts = controlPreCounts;
result.control.pre.added = addedControlPre;

result.control.test.edges = controlTestEdges;
result.control.test.counts = controlTestCounts;
result.control.test.added = addedControlTest;

result.metadata = metadata;

save( ...
    fullfile(outputDir,'Results_Figure_S18_AddedConnections.mat'), ...
    'result' ...
);

%% Optional provenance

if ~isempty(which('docDataSrc'))
    try
        docDataSrc(fig,outputDir,scriptFile,true);
    catch documentationError
        warning( ...
            'docDataSrc failed: %s', ...
            documentationError.message ...
        );
    end
end

%% Export

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S18_Connection_Added_TaskVsControl_thresholdPlot.pdf' ...
    ), ...
    'ContentType','vector', ...
    'BackgroundColor','white' ...
);

exportgraphics( ...
    fig, ...
    fullfile( ...
        outputDir, ...
        'Figure_S18_Connection_Added_TaskVsControl_thresholdPlot.png' ...
    ), ...
    'Resolution',300, ...
    'BackgroundColor','white' ...
);

fprintf('\nSupplementary Figure S18 completed.\n');
fprintf('Results saved to:\n%s\n',outputDir);


%% ========================================================================
% Local functions
%% ========================================================================

function values = collectThresholdValues(gstruc,thresholdIndices)

    values = cell(1,numel(thresholdIndices));

    for k = 1:numel(thresholdIndices)

        thresholdIndex = thresholdIndices(k);

        currentValues = [];

        for subjectIndex = 1:size(gstruc,2)

            currentMatrix = ...
                gstruc(thresholdIndex,subjectIndex).o_CIJ_thresh;

            currentValues = [
                currentValues
                currentMatrix(:)
            ]; %#ok<AGROW>
        end

        values{k} = currentValues;
    end
end


function validateHistogramEdges(handles,label)

    reference = handles(1).BinEdges;

    for k = 2:numel(handles)

        if ~isequal(handles(k).BinEdges,reference)
            error( ...
                ['Histogram bin edges differ across thresholds for %s. ' ...
                 'Cannot reproduce original bin-count subtraction safely.'], ...
                label ...
            );
        end
    end
end


function counts = getHistogramCounts(handles)

    nBins = numel(handles(1).BinCounts);
    nThresholds = numel(handles);

    counts = nan(nBins,nThresholds);

    for k = 1:nThresholds
        counts(:,k) = handles(k).BinCounts';
    end
end


function writeHistogramSourceData(edges,counts,thresholdLabels,outputFile)

    sourceData = table( ...
        edges(1:end-1)', ...
        edges(2:end)', ...
        'VariableNames',{'edge_from','edge_to'} ...
    );

    for k = 1:numel(thresholdLabels)

        variableName = sprintf('count_%d',thresholdLabels(k));
        sourceData.(variableName) = counts(:,k);
    end

    writetable(sourceData,outputFile);
end

function writeAddedConnectionsSourceData(edges,counts,outputFile)

    sourceData = table( ...
        edges(1:end-1)', ...
        edges(2:end)', ...
        counts', ...
        'VariableNames',{'edge_from','edge_to','count_added'} ...
    );

    writetable(sourceData,outputFile);
end

function rel = makeRepoRelative(pathString,repoRoot)

    p = strrep(char(pathString),'\','/');
    r = strrep(char(repoRoot),'\','/');

    if startsWith(lower(p),lower(r))
        rel = extractAfter(string(p),strlength(r));
        rel = regexprep(rel,'^[\\/]+','');
    else
        rel = string(p);
    end
end

