function create_regressors_reappraisal(cfg)
% CREATE_REGRESSORS_REAPPRAISAL Create first-level task regressors.
%
% This cleaned version retains only the active v26 model from the supplied
% historical create_regressors_reappraisal_jr.m.
%
% The many historical alternative/sensitivity models remain available in
% legacy/create_regressors_reappraisal_jr_legacy.m.

if ~strcmp(cfg.regressorModel, 'v26')
    error([ ...
        'Only the fully specified active v26 model has been migrated. ' ...
        'Requested model: %s' ...
    ], cfg.regressorModel);
end

if ~isfolder(cfg.protocolDir)
    error('Processed protocol directory not found:\n%s', cfg.protocolDir);
end

if ~isfolder(cfg.regressorsDir)
    mkdir(cfg.regressorsDir);
end

metadataRows = cell(numel(cfg.subjectNumbers), 3);

for subjectIndex = 1:numel(cfg.subjectNumbers)

    animalNumber = cfg.subjectNumbers(subjectIndex);
    subjectID = cfg.subjectIDs{subjectIndex};

    protocolFile = find_subject_protocol_file( ...
        cfg.protocolDir, ...
        animalNumber ...
    );

    loaded = load(protocolFile, 'events');

    if ~isfield(loaded, 'events')
        error('Protocol file lacks variable "events":\n%s', protocolFile);
    end

    events = loaded.events;

    if numel(events) < 120
        error( ...
            '%s contains only %d events; expected at least 120.', ...
            subjectID, ...
            numel(events) ...
        );
    end

    requiredEventFields = {
        'fv_on_del5'
        'puff_time_del5'
        'puff_or_not'
    };

    for fieldIndex = 1:numel(requiredEventFields)
        if ~isfield(events, requiredEventFields{fieldIndex})
            error( ...
                '%s: events lacks field "%s".', ...
                subjectID, ...
                requiredEventFields{fieldIndex} ...
            );
        end
    end

    odorDelay = cfg.odorDelay;

    pairingIndices = 41:80;
    pairingNoPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 0 ...
    );
    pairingPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 1 ...
    );

    regressors = repmat( ...
        struct('name', '', 'onset', [], 'duration', 0, 'pm', []), ...
        1, ...
        12 ...
    );

    % Odor-onset regressors
    regressors(1) = make_regressor( ...
        'Lavender_Bl1_1to10', ...
        [events(1:10).fv_on_del5] + odorDelay ...
    );

    regressors(2) = make_regressor( ...
        'Lavender_Bl1_11to40', ...
        [events(11:40).fv_on_del5] + odorDelay ...
    );

    regressors(3) = make_regressor( ...
        'Lavender_Bl2_NoPuff', ...
        [events(pairingNoPuff).fv_on_del5] + odorDelay ...
    );

    regressors(4) = make_regressor( ...
        'Lavender_Bl2_Puff', ...
        [events(pairingPuff).fv_on_del5] + odorDelay ...
    );

    regressors(5) = make_regressor( ...
        'Lavender_Bl3_early', ...
        [events(81:100).fv_on_del5] + odorDelay ...
    );

    regressors(6) = make_regressor( ...
        'Lavender_Bl3_late', ...
        [events(101:120).fv_on_del5] + odorDelay ...
    );

    % Nominal puff-time regressors
    regressors(7) = make_regressor( ...
        'TP_Puff_Bl1_1to10', ...
        [events(1:10).puff_time_del5] ...
    );

    regressors(8) = make_regressor( ...
        'TP_Puff_Bl1_11to40', ...
        [events(11:40).puff_time_del5] ...
    );

    regressors(9) = make_regressor( ...
        'TP_Puff_Bl2_NoPuff', ...
        [events(pairingNoPuff).puff_time_del5] ...
    );

    regressors(10) = make_regressor( ...
        'TP_Puff_Bl2_Puff', ...
        [events(pairingPuff).puff_time_del5] ...
    );

    regressors(11) = make_regressor( ...
        'TP_Puff_Bl3_early', ...
        [events(81:100).puff_time_del5] ...
    );

    regressors(12) = make_regressor( ...
        'TP_Puff_Bl3_late', ...
        [events(101:120).puff_time_del5] ...
    );

    outputFile = fullfile( ...
        cfg.regressorsDir, ...
        sprintf('%s_%s.mat', subjectID, cfg.regressorModel) ...
    );

    save(outputFile, 'regressors');

    metadataRows(subjectIndex, :) = {
        subjectID
        protocolFile
        outputFile
    };

    fprintf('Saved regressors: %s\n', outputFile);
end

metadata = cell2table( ...
    metadataRows, ...
    'VariableNames', ...
    {'Subject_ID', 'Protocol_File', 'Regressor_File'} ...
);

metadata.Model = repmat( ...
    string(cfg.regressorModel), ...
    height(metadata), ...
    1 ...
);

metadata.OdorDelay_s = repmat( ...
    cfg.odorDelay, ...
    height(metadata), ...
    1 ...
);

writetable( ...
    metadata, ...
    fullfile(cfg.regressorsDir, 'regressor_manifest.csv') ...
);

end


function regressor = make_regressor(name, onset)

regressor = struct();

regressor.name = name;
regressor.onset = onset(:)';
regressor.duration = 0;
regressor.pm = [];

end
