function create_regressors_reappraisal_v22(cfg)
% CREATE_REGRESSORS_REAPPRAISAL_V22
% Generate the primary v22 first-level task regressors for the
% reappraisal/conditioning cohort.
%
% Primary v22 model:
%
% Odor onset:
%   1. Lavender_Bl1_1to10
%   2. Lavender_Bl1_11to40
%   3. Lavender_Bl2_NoPuff
%   4. Lavender_Bl2_Puff
%   5. Lavender_Bl3
%
% Nominal puff time:
%   6. TP_Puff_Bl1_1to10
%   7. TP_Puff_Bl1_11to40
%   8. TP_Puff_Bl2_NoPuff
%   9. TP_Puff_Bl2_Puff
%  10. TP_Puff_Bl3
%
% All regressors are event-related (duration = 0) and have no parametric
% modulators. Odor onset is shifted by cfg.odorDelay seconds.
%
% The distinction from historical v26 is that Block 3 is NOT separated into
% early and late halves in v22.

if ~strcmp(cfg.regressorModel, 'v22')
    error('This function generates only the primary v22 regressor model.');
end

if ~isfolder(cfg.protocolDir)
    error('Processed protocol directory not found:\n%s', cfg.protocolDir);
end

if ~isfolder(cfg.regressorsDir)
    mkdir(cfg.regressorsDir);
end

metadataRows = cell(numel(cfg.subjectNumbers), 4);

for subjectIndex = 1:numel(cfg.subjectNumbers)

    animalNumber = cfg.subjectNumbers(subjectIndex);
    subjectID = cfg.subjectIDs{subjectIndex};

    protocolFile = find_subject_protocol_file( ...
        cfg.protocolDir, ...
        animalNumber ...
    );

    loaded = load(protocolFile, 'events');

    if ~isfield(loaded, 'events')
        error('Protocol file lacks variable "events":\n%s', protocolFile);
    end

    events = loaded.events;

    if numel(events) < 120
        error( ...
            '%s contains only %d events; expected at least 120.', ...
            subjectID, ...
            numel(events) ...
        );
    end

    requiredEventFields = {
        'fv_on_del5'
        'puff_time_del5'
        'puff_or_not'
    };

    for fieldIndex = 1:numel(requiredEventFields)
        if ~isfield(events, requiredEventFields{fieldIndex})
            error( ...
                '%s: events lacks field "%s".', ...
                subjectID, ...
                requiredEventFields{fieldIndex} ...
            );
        end
    end

    odorDelay = cfg.odorDelay;

    pairingIndices = 41:80;

    pairingNoPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 0 ...
    );

    pairingPuff = pairingIndices( ...
        [events(pairingIndices).puff_or_not] == 1 ...
    );

    regressors = repmat( ...
        struct('name', '', 'onset', [], 'duration', 0, 'pm', []), ...
        1, ...
        10 ...
    );

    %% Odor-onset regressors

    regressors(1) = make_regressor( ...
        'Lavender_Bl1_1to10', ...
        [events(1:10).fv_on_del5] + odorDelay ...
    );

    regressors(2) = make_regressor( ...
        'Lavender_Bl1_11to40', ...
        [events(11:40).fv_on_del5] + odorDelay ...
    );

    regressors(3) = make_regressor( ...
        'Lavender_Bl2_NoPuff', ...
        [events(pairingNoPuff).fv_on_del5] + odorDelay ...
    );

    regressors(4) = make_regressor( ...
        'Lavender_Bl2_Puff', ...
        [events(pairingPuff).fv_on_del5] + odorDelay ...
    );

    regressors(5) = make_regressor( ...
        'Lavender_Bl3', ...
        [events(81:120).fv_on_del5] + odorDelay ...
    );

    %% Nominal puff-time regressors

    regressors(6) = make_regressor( ...
        'TP_Puff_Bl1_1to10', ...
        [events(1:10).puff_time_del5] ...
    );

    regressors(7) = make_regressor( ...
        'TP_Puff_Bl1_11to40', ...
        [events(11:40).puff_time_del5] ...
    );

    regressors(8) = make_regressor( ...
        'TP_Puff_Bl2_NoPuff', ...
        [events(pairingNoPuff).puff_time_del5] ...
    );

    regressors(9) = make_regressor( ...
        'TP_Puff_Bl2_Puff', ...
        [events(pairingPuff).puff_time_del5] ...
    );

    regressors(10) = make_regressor( ...
        'TP_Puff_Bl3', ...
        [events(81:120).puff_time_del5] ...
    );

    outputFile = fullfile( ...
        cfg.regressorsDir, ...
        sprintf('%s_%s.mat', subjectID, cfg.regressorModel) ...
    );

    save(outputFile, 'regressors');

    metadataRows(subjectIndex, :) = {
        subjectID
        protocolFile
        outputFile
        strjoin(string({regressors.name}), ' | ')
    };

    fprintf('Saved v22 regressors: %s\n', outputFile);
end

metadata = cell2table( ...
    metadataRows, ...
    'VariableNames', ...
    {'Subject_ID', 'Protocol_File', 'Regressor_File', 'Regressor_Names'} ...
);

metadata.Model = repmat( ...
    string(cfg.regressorModel), ...
    height(metadata), ...
    1 ...
);

metadata.OdorDelay_s = repmat( ...
    cfg.odorDelay, ...
    height(metadata), ...
    1 ...
);

writetable( ...
    metadata, ...
    fullfile(cfg.regressorsDir, 'regressor_manifest_v22.csv') ...
);

end


function regressor = make_regressor(name, onset)

regressor = struct();

regressor.name = name;
regressor.onset = onset(:)';
regressor.duration = 0;
regressor.pm = [];

end
