function cfg = fc_basco_reappraisal_config(repoRoot)
% FC_BASCO_REAPPRAISAL_CONFIG Primary BASCO functional-connectivity model.
%
% Confirmed historical primary settings:
%   BASCO version        v11
%   trial-wise model     v19
%   EPI                  unsmoothed normalized/wavelet-despiked data
%   HRF                  HRFlongTC_withoutOnset_from2sHRF-GLM
%   nuisance covariates  identical to voxelwise-GLM v1
%   atlas                AllenBrain_2021_v2_inPax_merged
%   hemisphere handling  homologous left/right labels combined into one ROI
%
% The voxelwise GLM v22 and the FC/BASCO v19 model are intentionally
% different model definitions.

arguments
    repoRoot (1,:) char
end

cfg = struct();

%% Analysis identity

cfg.cohort = 'reappraisal';
cfg.version.basco = 'v11';
cfg.version.regressors = 'v19';

%% Subjects

cfg.subjectNumbers = 1:24;
cfg.subjectIDs = arrayfun( ...
    @(n) sprintf('ZI_M%02d', n), ...
    cfg.subjectNumbers, ...
    'UniformOutput', false ...
);

%% Preprocessed EPI
%
% FC and graph analyses use the UNSMOOTHED branch.
% Smoothed data were used only for testing/seed-based analyses.

localFmriRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'preprocessing', ...
    'reappraisal' ...
);

externalFmriRoot = getenv('NOSEMAZE_REAPPRAISAL_FMRI_PROCESSED_ROOT');

if isfolder(localFmriRoot)
    cfg.preprocessedFmriRoot = localFmriRoot;
elseif ~isempty(externalFmriRoot)
    cfg.preprocessedFmriRoot = externalFmriRoot;
else
    cfg.preprocessedFmriRoot = localFmriRoot;
end

cfg.epi.prefix = ...
    'wave_10cons_med1000_msk_wrst_a1_u_despiked_del5_';
cfg.epi.suffix = '_c1_c2t_wds';
cfg.epi.smoothed = false;
cfg.epi.forbiddenTokens = {'msk_s4_', 'msk_s6_'};

%% Processed event timing

cfg.protocolDir = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'RHD', ...
    'reappraisal', ...
    'processed_protocol_files' ...
);

%% BASCO-derived data

cfg.fcRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'processed', ...
    'fMRI', ...
    'functional_connectivity', ...
    'reappraisal', ...
    'basco', ...
    cfg.version.basco ...
);

cfg.manifestDir = fullfile(cfg.fcRoot, 'manifests');
cfg.regressorsDir = fullfile( ...
    cfg.fcRoot, ...
    ['regressors_' cfg.version.regressors] ...
);
cfg.inputDir = fullfile(cfg.fcRoot, 'input');
cfg.toolboxOutputDir = fullfile(cfg.fcRoot, 'toolbox_output');
cfg.betaSeriesDir = fullfile(cfg.fcRoot, 'beta_series');
cfg.correlationMatrixDir = fullfile(cfg.fcRoot, 'correlation_matrices');
cfg.roiDataDir = fullfile(cfg.fcRoot, 'roi_data');

cfg.subjectManifestCsv = fullfile( ...
    cfg.manifestDir, ...
    'fc_subject_manifest_reappraisal.csv' ...
);
cfg.subjectManifestMat = fullfile( ...
    cfg.manifestDir, ...
    'fc_subject_manifest_reappraisal.mat' ...
);

cfg.files.metainfo = fullfile( ...
    cfg.inputDir, ...
    sprintf('metainfo_%s.mat', cfg.version.basco) ...
);

%% BASCO v19 regressors
%
% v19 has three trial-wise conditions:
%   Lavender   = all 120 odor onsets
%   TP Puff    = 28 actual puff time points
%   TP NoPuff  = 92 puff-like time points
%                (40 pre + 12 pairing-no-puff + 40 post)

cfg.regressors.suffix = ['_' cfg.version.regressors '.mat'];
cfg.regressors.odorDelay = 0.7;  % s, mini-PID estimate
cfg.regressors.expectedLavender = 120;
cfg.regressors.expectedPuff = 28;
cfg.regressors.expectedNoPuff = 92;

%% Nuisance regressors
%
% The BASCO file is byte-for-byte/data-identical to the primary v1 GLM
% nuisance source; it is simply copied/renamed for BASCO.

cfg.nuisance.sourceFilename = ...
    'regressors_despiked_motcsf_der.txt';

cfg.nuisance.bascoFilename = ...
    'rp_regressors_despiked_motcsf_der_v11.txt';

cfg.nuisance.expectedColumns = 14;

%% HRF

cfg.hrf.tcBased = 'longTC';
cfg.hrf.estimateLength = 'from2sHRF-GLM';
cfg.hrf.onset = 'withoutOnset';
cfg.hrf.infoPath = ...
    [cfg.hrf.onset '_' cfg.hrf.estimateLength];

cfg.hrf.name = ...
    ['HRF' cfg.hrf.tcBased '_' cfg.hrf.infoPath];

cfg.hrf.dir = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab', ...
    'preprocessing', ...
    'toolboxes', ...
    'spm12_animal', ...
    cfg.hrf.tcBased, ...
    ['hrf_' cfg.hrf.infoPath] ...
);

%% BASCO analysis definition

scriptDir = fileparts(mfilename('fullpath'));

cfg.model.anadefFile = fullfile( ...
    scriptDir, ...
    'model', ...
    'anadef_reappraisal.m' ...
);

cfg.model.conditionLavender = 'Lavender';
cfg.model.conditionTpPuff = 'TP Puff';
cfg.model.conditionTpNoPuff = 'TP NoPuff';

cfg.model.TR = 1.2;
cfg.model.fmri_t = 22;
cfg.model.fmri_t0 = 1;
cfg.model.HRFDERIVS = [0 0];

cfg.model.VoxelAnalysis = true;
cfg.model.ROIAnalysis = false;

% Historical BASCO specification mask.
maskOverride = getenv('NOSEMAZE_REAPPRAISAL_DARTEL_MASK');

if ~isempty(maskOverride)
    cfg.model.specMask = maskOverride;
else
    cfg.model.specMask = fullfile( ...
        repoRoot, ...
        'data', ...
        'processed', ...
        'fMRI', ...
        'preprocessing', ...
        'reappraisal', ...
        'reference', ...
        'mask_template_6_polished.nii' ...
    );
end

%% Atlas
%
% Exact historical files:
%   AllenBrain_2021_v2_inPax_merged_jr.txt
%   AllenBrain_2021_v2_inPax_merged.nii
%
% The text file groups multiple atlas labels into one anatomical ROI. Thus
% homologous left/right labels (for example left S1 and right S1) are
% summarized into one S1 node before the correlation matrix is calculated.

cfg.atlas.name = 'AllenBrain_2021_v2_inPax_merged';
cfg.atlas.leftRightCombination = true;
cfg.atlas.expectedROIcount = 52;

atlasRoot = fullfile( ...
    repoRoot, ...
    'data', ...
    'reference', ...
    'atlases', ...
    'AllenBrain_2021_v2' ...
);

cfg.atlas.labels = fullfile( ...
    atlasRoot, ...
    'AllenBrain_2021_v2_inPax_merged_jr.txt' ...
);

cfg.atlas.nifti = fullfile( ...
    atlasRoot, ...
    'AllenBrain_2021_v2_inPax_merged.nii' ...
);

%% Primary 10 FC matrices

cfg.primaryMatrixSuffixes = {
    'Odor1to10'
    'Odor11to40'
    'Odor_TPNoPuff'
    'Odor_TPPuff'
    'Odor81to120'
    'TPnoPuff1to10'
    'TPnoPuff11to40'
    'TPnoPuff41to80'
    'TP-Puff'
    'TPnoPuff81to120'
};

cfg.expectedMatrixCount = 10;

%% Toolboxes

toolboxRoot = fullfile( ...
    repoRoot, ...
    'src', ...
    'matlab', ...
    'preprocessing', ...
    'toolboxes' ...
);

cfg.toolboxes.basco = fullfile(toolboxRoot, 'BASCO');
cfg.toolboxes.spm12Animal = fullfile(toolboxRoot, 'spm12_animal');
cfg.toolboxes.nbs = fullfile(toolboxRoot, 'NBS1.2');
cfg.toolboxes.bct = fullfile(toolboxRoot, '2019_03_03_BCT');

cfg.toolboxes.spm12 = getenv('SPM12_DIR');
cfg.toolboxes.marsbar = getenv('MARSBAR_DIR');

%% BASCO output

cfg.basco.anaobjFile = fullfile( ...
    cfg.toolboxOutputDir, ...
    sprintf('out_estimated_reappraisal_%s.mat', cfg.version.basco) ...
);

%% Optional legacy convenience beta-series outputs

cfg.writeGenericConditionSeries = false;
cfg.writeLegacyConvenienceSeries = false;

end
