% panel_B_deltaC_BOLD.m
% Jonathan Reinwald
%
% Supplementary Figure S13B: whole-brain Delta C adaptation vs BOLD
% extracted from the Delta-C-sensitive vHC cluster shown in Figure S13A.
%
% Delta C predictor:
%   g_delta_C TEST - g_delta_C PRE
%
% Graph data are reused from Figure 4C-E (45-50% density).
%
% Required beta file:
%   data/processed/fMRI/Figure_S13/Figure_S13B/mask_vHC_T01_corrdeltaC.mat

clear;
close all;
clc;

%% Locate repository root

scriptFile = mfilename('fullpath');

if isempty(scriptFile)
    error([ ...
        'MATLAB could not determine the location of this script. ' ...
        'Run the complete saved script rather than selected lines.' ...
    ]);
end

scriptDir = fileparts(scriptFile);

% repository/figures/supplement/Figure_S13/panel_B_deltaC_BOLD.m
repoRoot = fileparts(fileparts(fileparts(scriptDir)));

%% Repository-relative paths

srcDir = fullfile(repoRoot,'src','matlab');

if ~isfolder(srcDir)
    error('MATLAB source directory not found:\n%s',srcDir);
end

addpath(genpath(srcDir));

aucDir = fullfile( ...
    repoRoot, ...
    'data','processed','fMRI', ...
    'Figure_4','Figure_4C_E','conditioning' ...
);

inputDir = fullfile( ...
    repoRoot, ...
    'data','processed','fMRI', ...
    'Figure_S13','Figure_S13B' ...
);

outputDir = fullfile( ...
    repoRoot, ...
    'results','supplement', ...
    'Figure_S13','Figure_S13B' ...
);

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Required helpers

requiredFunctions = {
    'notBoxPlot_modified'
    'permutest'
    'sigstar'
};

missingFunctions = requiredFunctions( ...
    cellfun(@(x) isempty(which(x)), requiredFunctions) ...
);

if ~isempty(missingFunctions)
    error([ ...
        'Required MATLAB helper functions not found:\n%s\n\n' ...
        'Place them somewhere under src/matlab/.' ...
    ], strjoin(missingFunctions,newline));
end

if isempty(ver('stats'))
    error([ ...
        'Statistics and Machine Learning Toolbox is required ' ...
        'for corr, ttest and lsline.' ...
    ]);
end

%% Input files

aucPreFile = fullfile( ...
    aucDir, ...
    'auc_struc_TPnoPuff11to40_45to50_p.mat' ...
);

aucTestFile = fullfile( ...
    aucDir, ...
    'auc_struc_TPnoPuff81to120_45to50_p.mat' ...
);

betaFile = fullfile( ...
    inputDir, ...
    'mask_vHC_T01_corrdeltaC.mat' ...
);

requiredFiles = {
    aucPreFile
    aucTestFile
    betaFile
};

missingFiles = requiredFiles(~cellfun(@isfile,requiredFiles));

if ~isempty(missingFiles)
    error( ...
        'Required files missing:\n\n%s', ...
        strjoin(missingFiles,newline) ...
    );
end

%% Load Delta C graph metric

preLoaded = load(aucPreFile);
testLoaded = load(aucTestFile);

if ~isfield(preLoaded,'auc_struc') || ~isfield(testLoaded,'auc_struc')
    error('Expected variable "auc_struc" missing from Figure 4 AUC files.');
end

aucPre = preLoaded.auc_struc;
aucTest = testLoaded.auc_struc;

if ~isfield(aucPre,'g_delta_C') || ~isfield(aucTest,'g_delta_C')
    error('g_delta_C missing from AUC structure.');
end

% auc_struc is a 1 x N struct array: one element per animal
deltaCPre  = [aucPre.g_delta_C]';
deltaCTest = [aucTest.g_delta_C]';

% Figure S13B predictor
deltaCInput = deltaCTest - deltaCPre;

%% Load vHC beta values

[betaPre,betaTest,betaDiff] = extractBetaVectors(betaFile);

%% Input checks

if numel(deltaCInput) ~= numel(betaPre)
    error( ...
        'Sample-size mismatch: DeltaC n=%d; beta n=%d.', ...
        numel(deltaCInput), ...
        numel(betaPre) ...
    );
end

fprintf('\nSupplementary Figure S13B input check\n');
fprintf('Animals: %d\n',numel(deltaCInput));
fprintf('Predictor: g_delta_C TEST - PRE\n');
fprintf('Beta file: %s\n\n',betaFile);

%% Analysis and figure

makeFigure( ...
    'Figure_S13B', ...
    'DeltaC_TestMinusPre', ...
    deltaCInput, ...
    betaPre, ...
    betaTest, ...
    outputDir, ...
    10000, ...
    1234, ...
    scriptFile ...
);

%% Source data

sourceData = table( ...
    (1:numel(deltaCInput))', ...
    deltaCPre, ...
    deltaCTest, ...
    deltaCInput, ...
    betaPre, ...
    betaTest, ...
    betaDiff, ...
    'VariableNames', {
        'SubjectIndex'
        'DeltaC_Pre'
        'DeltaC_Test'
        'DeltaC_TestMinusPre'
        'BOLD_Pre'
        'BOLD_Test'
        'BOLD_TestMinusPre'
    } ...
);

writetable( ...
    sourceData, ...
    fullfile( ...
        outputDir, ...
        'SourceData_Figure_S13B.csv' ...
    ) ...
);

fprintf('Supplementary Figure S13B completed.\n');
fprintf('Results saved to:\n%s\n',outputDir);


%% ========================================================================
% Local functions
%% ========================================================================

function p = getScalarPermutationP(pValues)

    if isempty(pValues)
        p = NaN;
        return;
    end

    pValues = pValues(:);

    if numel(pValues) > 1
        warning([ ...
            'permutest returned %d p-values. ' ...
            'Using the smallest p-value.' ...
        ], numel(pValues));
    end

    p = min(pValues);
end


function [betaPre,betaTest,betaDiff] = extractBetaVectors(betaFile)

    loaded = load(betaFile);

    if ~isfield(loaded,'res')
        error( ...
            'Variable "res" missing from beta file:\n%s', ...
            betaFile ...
        );
    end

    res = loaded.res;

    if ~isfield(res,'mean_betaNeg') || ~isfield(res,'mean_betaPos')
        error([ ...
            'Expected res.mean_betaNeg and res.mean_betaPos are ' ...
            'missing from:\n%s' ...
        ], betaFile);
    end

    % Same convention as Figure 6F:
    %   PRE  = mean_betaNeg
    %   TEST = mean_betaPos
    betaPre = [res.mean_betaNeg]';
    betaTest = [res.mean_betaPos]';
    betaDiff = betaTest - betaPre;
end


function makeFigure( ...
    panelName, ...
    predictorName, ...
    predictor, ...
    betaPre, ...
    betaTest, ...
    outputDir, ...
    numberOfPermutations, ...
    randomSeed, ...
    scriptFile ...
)

    betaDiff = betaTest - betaPre;

    %% Correlations

    [rPreP,pPreP] = corr( ...
        predictor,betaPre, ...
        'Type','Pearson', ...
        'Rows','complete' ...
    );

    [rPreS,pPreS] = corr( ...
        predictor,betaPre, ...
        'Type','Spearman', ...
        'Rows','complete' ...
    );

    [rTestP,pTestP] = corr( ...
        predictor,betaTest, ...
        'Type','Pearson', ...
        'Rows','complete' ...
    );

    [rTestS,pTestS] = corr( ...
        predictor,betaTest, ...
        'Type','Spearman', ...
        'Rows','complete' ...
    );

    [rDiffP,pDiffP] = corr( ...
        predictor,betaDiff, ...
        'Type','Pearson', ...
        'Rows','complete' ...
    );

    [rDiffS,pDiffS] = corr( ...
        predictor,betaDiff, ...
        'Type','Spearman', ...
        'Rows','complete' ...
    );

    %% PRE vs TEST statistics

    [hPaired,pPaired,~,pairedStats] = ttest(betaPre,betaTest);

    rng(randomSeed,'twister');

    [clusters,pPermValues,tSums,permDist] = permutest( ...
        betaPre', ...
        betaTest', ...
        true, ...
        0.05, ...
        numberOfPermutations, ...
        true ...
    );

    pPerm = getScalarPermutationP(pPermValues);

    %% Colors retained from original script

    preColor  = [204/255,51/255,204/255];
    testColor = [0,160/255,227/255];
    diffColor = (preColor + testColor) ./ 2;

    %% Figure

    fig = figure( ...
        'Name',sprintf('%s: %s vs BOLD',panelName,predictorName), ...
        'Visible','on', ...
        'Color','white', ...
        'Position',[100,80,1050,720] ...
    );

    %% PRE vs TEST

    subplot(2,3,1);

    bb = notBoxPlot_modified([betaPre,betaTest]);

    for i = 1:numel(bb)
        bb(i).data.MarkerSize = 6;
        bb(i).data.MarkerEdgeColor = 'none';
        bb(i).semPtch.EdgeColor = 'none';
        bb(i).sdPtch.EdgeColor = 'none';
    end

    bb(1).data.MarkerFaceColor = preColor;
    bb(1).mu.Color = preColor;
    bb(1).semPtch.FaceColor = [255/255,102/255,204/255];
    bb(1).sdPtch.FaceColor = [255/255,204/255,204/255];

    bb(2).data.MarkerFaceColor = testColor;
    bb(2).mu.Color = testColor;
    bb(2).semPtch.FaceColor = [75/255,207/255,227/255];
    bb(2).sdPtch.FaceColor = [150/255,255/255,227/255];

    ax1 = gca;
    box(ax1,'off');

    ylabel(ax1,'mean BOLD');

    ax1.XTick = [1,2];
    ax1.XTickLabel = {'Pre','Test'};
    ax1.XLim = [0.5,2.5];
    ax1.FontSize = 10;
    ax1.FontWeight = 'bold';
    ax1.LineWidth = 1.5;

    if isfinite(pPerm) && pPerm < 0.05
        sigstar({[1,2]},pPerm,0,10);
    end

    text( ...
        ax1, ...
        ax1.XLim(1)+0.1*diff(ax1.XLim), ...
        ax1.YLim(1)+0.2*diff(ax1.YLim), ...
        sprintf('p_{perm} = %.4g',pPerm), ...
        'Interpreter','tex' ...
    );

    %% Predictor vs PRE / TEST

    subplot(2,3,[2,3]);

    s1 = scatter(predictor,betaPre,40,'filled');
    hold on;
    s2 = scatter(predictor,betaTest,40,'filled');

    s1.MarkerEdgeColor = 'none';
    s2.MarkerEdgeColor = 'none';

    s1.MarkerFaceColor = preColor;
    s2.MarkerFaceColor = testColor;

    ax2 = gca;
    box(ax2,'off');
    axis(ax2,'square');

    xlabel(ax2,predictorName,'Interpreter','none');
    ylabel(ax2,'mean BOLD');

    ax2.FontSize = 10;
    ax2.FontWeight = 'bold';
    ax2.LineWidth = 1.5;

    ll = lsline;

    if numel(ll) >= 2
        ll(1).Color = testColor;
        ll(1).LineWidth = 1.5;
        ll(2).Color = preColor;
        ll(2).LineWidth = 1.5;
    end

    x1 = ax2.XLim(1)+0.10*diff(ax2.XLim);
    x2 = ax2.XLim(1)+0.55*diff(ax2.XLim);
    y1 = ax2.YLim(1)+0.10*diff(ax2.YLim);
    y2 = ax2.YLim(1)+0.20*diff(ax2.YLim);
    y3 = ax2.YLim(1)+0.90*diff(ax2.YLim);
    y4 = ax2.YLim(1)+0.80*diff(ax2.YLim);

    text(ax2,x1,y1,sprintf('p = %.3g',pPreP), ...
        'Color',preColor,'FontWeight','bold');
    text(ax2,x2,y1,sprintf('r = %.3f',rPreP), ...
        'Color',preColor,'FontWeight','bold');

    text(ax2,x1,y2,sprintf('p = %.3g',pTestP), ...
        'Color',testColor,'FontWeight','bold');
    text(ax2,x2,y2,sprintf('r = %.3f',rTestP), ...
        'Color',testColor,'FontWeight','bold');

    text(ax2,x1,y3,sprintf('p_s = %.3g',pPreS), ...
        'Color',preColor,'FontWeight','bold');
    text(ax2,x2,y3,sprintf('\rho_s = %.3f',rPreS), ...
        'Color',preColor,'FontWeight','bold','Interpreter','tex');

    text(ax2,x1,y4,sprintf('p_s = %.3g',pTestS), ...
        'Color',testColor,'FontWeight','bold');
    text(ax2,x2,y4,sprintf('\rho_s = %.3f',rTestS), ...
        'Color',testColor,'FontWeight','bold','Interpreter','tex');

    %% Predictor vs TEST-PRE BOLD

    subplot(2,3,[5,6]);

    sd = scatter(predictor,betaDiff,40,'filled');
    sd.MarkerEdgeColor = 'none';
    sd.MarkerFaceColor = diffColor;

    ax3 = gca;
    box(ax3,'off');
    axis(ax3,'square');

    xlabel(ax3,predictorName,'Interpreter','none');
    ylabel(ax3,{'mean BOLD','(Test - Pre)'});

    ax3.FontSize = 10;
    ax3.FontWeight = 'bold';
    ax3.LineWidth = 1.5;

    ld = lsline;
    ld.Color = diffColor;
    ld.LineWidth = 1.5;

    x1 = ax3.XLim(1)+0.10*diff(ax3.XLim);
    x2 = ax3.XLim(1)+0.55*diff(ax3.XLim);
    y1 = ax3.YLim(1)+0.10*diff(ax3.YLim);
    y2 = ax3.YLim(1)+0.20*diff(ax3.YLim);

    text(ax3,x1,y1,sprintf('p = %.3g',pDiffP), ...
        'Color',diffColor,'FontWeight','bold');
    text(ax3,x2,y1,sprintf('r = %.3f',rDiffP), ...
        'Color',diffColor,'FontWeight','bold');

    text(ax3,x1,y2,sprintf('p_s = %.3g',pDiffS), ...
        'Color',diffColor,'FontWeight','bold');
    text(ax3,x2,y2,sprintf('\rho_s = %.3f',rDiffS), ...
        'Color',diffColor,'FontWeight','bold','Interpreter','tex');

    sgtitle( ...
        sprintf('%s | %s',panelName,predictorName), ...
        'Interpreter','none' ...
    );

    %% Statistics export

    statsTable = table( ...
        [
            "Predictor_vs_PRE_Pearson"
            "Predictor_vs_PRE_Spearman"
            "Predictor_vs_TEST_Pearson"
            "Predictor_vs_TEST_Spearman"
            "Predictor_vs_Delta_Pearson"
            "Predictor_vs_Delta_Spearman"
            "PRE_vs_TEST_PairedTTest"
            "PRE_vs_TEST_Permutation"
        ], ...
        [
            rPreP
            rPreS
            rTestP
            rTestS
            rDiffP
            rDiffS
            pairedStats.tstat
            NaN
        ], ...
        [
            pPreP
            pPreS
            pTestP
            pTestS
            pDiffP
            pDiffS
            pPaired
            pPerm
        ], ...
        'VariableNames', {
            'Statistic'
            'Estimate'
            'P'
        } ...
    );

    writetable( ...
        statsTable, ...
        fullfile( ...
            outputDir, ...
            'Statistics_Figure_S13B.csv' ...
        ) ...
    );

    %% Complete result MAT

    result = struct;

    result.predictorName = predictorName;
    result.predictor = predictor;

    result.betaPre = betaPre;
    result.betaTest = betaTest;
    result.betaDiff = betaDiff;

    result.statistics = statsTable;

    result.pairedTTest = struct( ...
        'h',hPaired, ...
        'p',pPaired, ...
        'stats',pairedStats ...
    );

    result.permutation = struct( ...
        'clusters',clusters, ...
        'pValues',pPermValues, ...
        'p',pPerm, ...
        'tSums',tSums, ...
        'distribution',permDist, ...
        'numberOfPermutations',numberOfPermutations, ...
        'randomSeed',randomSeed ...
    );

    save( ...
        fullfile( ...
            outputDir, ...
            'Results_Figure_S13B.mat' ...
        ), ...
        'result' ...
    );

    %% Optional provenance

    if ~isempty(which('docDataSrc'))
        try
            docDataSrc(fig,outputDir,scriptFile,true);
        catch documentationError
            warning( ...
                'docDataSrc failed: %s', ...
                documentationError.message ...
            );
        end
    end

    %% Export figure

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            'Figure_S13B.pdf' ...
        ), ...
        'ContentType','vector', ...
        'BackgroundColor','white' ...
    );

    exportgraphics( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            'Figure_S13B.png' ...
        ), ...
        'Resolution',300, ...
        'BackgroundColor','white' ...
    );
end
